import { toTraditional } from "@/lib/journal-locales";
import type { ReportLocale } from "@/lib/report-i18n";
export const celestialLocales = ["en", "zh", "zh-TW", "ru"] as const;
export const celestialHref = (path: string, locale: ReportLocale) =>
  locale === "en" ? path : `${path}?locale=${locale}`;
export const celestialAlternates = (path: string) => ({
  en: path,
  "zh-Hans": `${path}?locale=zh`,
  "zh-Hant": `${path}?locale=zh-TW`,
  ru: `${path}?locale=ru`,
  "x-default": path,
});
function traditional<T>(value: T): T {
  if (typeof value === "string") return toTraditional(value) as T;
  if (Array.isArray(value)) return value.map(traditional) as T;
  if (value && typeof value === "object")
    return Object.fromEntries(
      Object.entries(value).map(([k, v]) => [k, traditional(v)]),
    ) as T;
  return value;
}
const en = {
  home: "Home",
  astrology: "Birth chart",
  tarot: "Tarot studio",
  back: "Back to DestinyPixel",
  free: "Free · no account needed",
  loading: "A moment…",
  error: "We couldn't complete that. Check your details and try again.",
  retry: "Try again",
  aiReady: "Reading ready",
  method: "How this works",
  ai: "Help me interpret",
  aiBusy: "Connecting the symbols…",
  aiNote:
    "Only when you ask: chart positions, or your revealed cards, question and optional context, are sent to DeepSeek. Birth details are not attached to the tarot request. Leave identifying details out of your question and context.",
  aiUnavailable:
    "AI interpretation is temporarily unavailable. Your chart and cards are still here; you can explore them yourself or try again later.",
  aiLimited:
    "The free interpretation limit has been reached. Please try again later; your chart and cards remain available.",
  reflection:
    "Symbolic reflection, not a scientific personality assessment or a prediction. Keep important decisions grounded in your circumstances.",
  astroTitle:
    "Free Natal Birth Chart Calculator & AI Interpretation | DestinyPixel",
  astroDescription:
    "Calculate a detailed tropical natal chart with ten planets, rising sign, whole-sign houses, retrograde motion and aspects. Explore an interactive chart and optional AI interpretation.",
  astroEyebrow: "YOUR MOMENT IN THE SKY",
  astroHeading: "A sky full of details.\nA new way to see yourself.",
  astroIntro:
    "Your Sun is only the beginning. Explore the Moon, your rising sign and the connections between ten planets in one personal birth chart.",
  astroCta: "Create my birth chart",
  date: "Birth date",
  time: "Local birth time",
  city: "Birthplace",
  chooseCity: "Choose a city",
  custom: "Another location · enter coordinates",
  latitude: "Latitude (−90 to 90)",
  longitude: "Longitude (−180 to 180)",
  timezone: "IANA time zone",
  timezoneHelp:
    "For example Europe/London or America/New_York. Use the zone for your birthplace; historical daylight saving is applied automatically.",
  exactTime:
    "Use the time on your birth record. The rising sign and houses depend on it. If the time is unknown, don't treat a guessed chart as exact.",
  formTitle: "Begin with your birth details",
  privacy:
    "Calculated on our server. Your chart is stored in your account only when you choose to save it; birth details are never placed in the URL.",
  calculate: "Reveal my chart",
  example: "EXAMPLE CHART · NOT YOUR RESULTS",
  result: "YOUR NATAL CHART",
  sun: "Sun",
  moon: "Moon",
  rising: "Rising",
  mc: "Midheaven",
  planets: "Planets",
  houses: "Houses",
  aspects: "Aspects",
  elementTitle: "The elemental balance",
  elements: ["Fire", "Earth", "Air", "Water"],
  house: "House",
  retrograde: "Retrograde",
  direct: "Direct",
  degree: "Position",
  orb: "Orb",
  noAspects: "No major aspects within the selected six-degree orb.",
  planetHint: "Choose a planet in the chart or list to explore its role.",
  wheelExplore: "EXPLORE YOUR CHART",
  wheelPreview: "HOVER PREVIEW",
  wheelPinned: "SELECTION PINNED",
  wheelClear: "Show full chart",
  wheelHelp: "Hover over a planet or aspect line to preview its meaning. Click to pin it; on a phone, simply tap. Tap again, tap an empty area, or use Show full chart to clear the highlight.",
  houseHint:
    "One full zodiac sign per house. The rising sign begins House 1; the Midheaven is shown separately and may fall outside House 10.",
  aspectHint:
    "Major aspects between planets, with a uniform 6° maximum orb. These are angular relationships, not compatibility scores.",
  astroMethod:
    "Positions use Astronomy Engine's geocentric tropical ecliptic of date, calculated from the actual UTC birth instant. The Ascendant is the eastern horizon/ecliptic intersection. Houses use the Whole Sign system. Retrograde indicates apparent backward motion over a one-day interval. The element diagram counts ten planets equally; it does not measure personal qualities. AI interprets the calculated chart and never supplies astronomical positions.",
  astroFaqs: [
    {
      q: "Do I need AI to calculate my birth chart?",
      a: "No. All planetary positions, chart angles, houses and aspects are calculated without AI. AI is optional and adds a written symbolic reading of the same chart.",
    },
    {
      q: "Why might my chart differ from another website?",
      a: "Check the birth time, date-specific time zone, coordinates, tropical versus sidereal zodiac, and house system. This calculator uses the tropical zodiac and Whole Sign houses, not Placidus.",
    },
    {
      q: "What if my local birth time falls in a daylight-saving transition?",
      a: "Nonexistent or ambiguous local times are rejected rather than silently choosing the wrong instant. Check the original birth record and the local clock change before proceeding.",
    },
  ],
  signs: [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
  ],
  planetNames: [
    "Sun",
    "Moon",
    "Mercury",
    "Venus",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Pluto",
  ],
  planetRoles: [
    "Identity, vitality and what you want to create.",
    "Emotional habits, comfort and the need for belonging.",
    "How you think, learn and put things into words.",
    "What you appreciate and how you build connection.",
    "How you act, assert yourself and meet resistance.",
    "Where you seek growth, meaning and possibility.",
    "Responsibility, boundaries and the work of becoming skilled.",
    "Independence, change and unconventional ideas.",
    "Imagination, empathy and places where boundaries blur.",
    "Deep change, attachment and your relationship with power.",
  ],
  signStyles: [
    "Direct, initiating and willing to experiment.",
    "Steady, sensory and drawn to tangible value.",
    "Curious, conversational and open to different perspectives.",
    "Protective, receptive and attentive to emotional context.",
    "Expressive, generous and eager to bring something to life.",
    "Observant, practical and interested in improvement.",
    "Relational, balancing and aware of different points of view.",
    "Intense, discerning and drawn beneath the surface.",
    "Exploring, candid and motivated by a wider horizon.",
    "Deliberate, structured and willing to build over time.",
    "Independent, conceptual and interested in the collective.",
    "Imaginative, compassionate and responsive to atmosphere.",
  ],
  houseNames: [
    "Self & first impressions",
    "Values & resources",
    "Learning & conversation",
    "Home & roots",
    "Creativity & pleasure",
    "Routines & daily work",
    "Partnership & agreements",
    "Shared resources & intimacy",
    "Beliefs & exploration",
    "Calling & public life",
    "Friends & community",
    "Solitude & inner life",
  ],
  aspectNames: {
    conjunction: "Conjunction",
    sextile: "Sextile",
    square: "Square",
    trine: "Trine",
    opposition: "Opposition",
  },
  aspectMeanings: {
    conjunction:
      "Two functions meet in the same place; noticing their overlap can help you use both consciously.",
    sextile:
      "A possible opening for cooperation; it usually needs your participation to become useful.",
    square:
      "Different priorities ask for adjustment. A workable habit can turn tension into movement.",
    trine:
      "An easy connection to draw on, while noticing what you may take for granted.",
    opposition:
      "Two poles invite balance. Make space for both instead of treating one as the whole story.",
  },
  tarotTitle:
    "Free Interactive Tarot: Shuffle, Pick Cards & Choose Spreads | DestinyPixel",
  tarotDescription:
    "Shuffle a complete 78-card tarot deck, choose your own cards and turn them over. Explore free placement, one-card, three-card, relationship and Celtic Cross spreads with optional AI readings.",
  tarotEyebrow: "A LITTLE SPACE FOR A DIFFERENT PERSPECTIVE",
  tarotHeading: "Your question.\nYour hands. Your cards.",
  tarotIntro:
    "Take a breath, mix the deck and choose what calls to you. Lay out a familiar spread or make the whole table your own.",
  freeMode: "Free table",
  backToTable: "Back to the table",
  spreadMode: "Guided spreads",
  freeHelp:
    "Choose cards from the deck, then drag them anywhere on the table with a finger or mouse. Tap to reveal a card, then tap again for its meaning. Use the controls to rotate or return it. Arrow keys move the selected card too.",
  spreadHelp:
    "Choose a spread. Tap an empty position, then choose any face-down card below. Tap each placed card to reveal it; tap again for its meaning. Select a filled position to replace its card.",
  spreadLabel: "Your spread",
  spreads: {
    single: "One card · a focus",
    three: "Three cards · a path",
    relationship: "Connection · 5 cards",
    choice: "Two paths · 5 cards",
    celtic: "Celtic Cross · 10 cards",
  },
  positions: {
    single: ["A focus for now"],
    three: ["What brought you here", "What is present", "A possible next step"],
    relationship: [
      "Your perspective",
      "Their possible perspective",
      "What connects you",
      "Where you differ",
      "A step you can take",
    ],
    choice: [
      "What matters most",
      "Path A · opening",
      "Path A · challenge",
      "Path B · opening",
      "Path B · challenge",
    ],
    celtic: [
      "Present situation",
      "Crossing influence",
      "Underlying pattern",
      "Recent past",
      "Conscious focus",
      "Possible direction",
      "Your approach",
      "Surroundings",
      "Hopes and concerns",
      "Potential outcome",
    ],
  },
  reversals: "Include reversed cards",
  shuffle: "Shuffle remaining cards",
  shuffleTouch: "Swipe across the deck to mix it by hand",
  shuffled: "Deck mixed",
  reset: "Start a new reading",
  resetCheck: "Clear the table and begin again?",
  deckTitle: "Follow your curiosity. Choose a card.",
  deckShortTitle: "Choose a card",
  shuffleShort: "Shuffle",
  dropHint: "Drag up to the table, or tap to place",
  ribbonStart: "Shuffle first, then choose a card below.",
  ribbonHelp: "Slide to browse. Tap a raised card again, drag it up, or use the place button.",
  previousCard: "Previous card",
  nextCard: "Next card",
  drawSelected: "Place on table",
  deckHelp:
    "Every face stays hidden until you turn it over on the table. The deck has 78 different cards; selected cards cannot be drawn twice.",
  remaining: "remaining",
  cardBack: "Face-down card",
  position: "Position",
  pick: "Choose",
  selected: "Selected position",
  empty: "Choose a card below",
  reveal: "Turn over",
  conceal: "Turn face down",
  returnCard: "Return to deck",
  rotate: "Rotate",
  upright: "Upright",
  reversed: "Reversed",
  cardMeaning: "Explore this card",
  question: "What would you like to ask? (required for a reading)",
  viewCard: "Card meaning",
  closeCard: "Close card meaning",
  detailCta: "Ask about this reading",
  detailTitle: "A reading for your situation",
  questionRequired: "Add a question before requesting your detailed reading.",
  details: "Your situation (optional)",
  detailsPlaceholder: "What has happened so far? What are you weighing up, and what matters most to you?",
  detailsNote: "More specific context helps the reading address your situation. You can leave this blank. Avoid names, contact information and other identifying details.",
  questionPlaceholder:
    "How can I approach the next conversation in this relationship?",
  questionNote:
    "Stay with one question. No need to include names or private details.",
  readyHint:
    "Reveal every selected card to request an interpretation. Guided spreads must be complete.",
  emptyTable: "A blank table. A little possibility.",
  emptyTableHint: "Shuffle, then choose your first card from the deck below.",
  shuffledCount: "Mixes",
  allRevealed: "Your cards are ready to read",
  tarotMethod:
    "This is a digital 78-card Rider–Waite–Smith deck. Shuffling uses browser cryptographic randomness and never changes cards to fit your question. Optional reversals are assigned when cards are mixed. The free table supports all 78 cards; positions and rotation are yours to arrange. Card meanings are our concise editorial interpretations. AI only reads the cards you have chosen, in their stated positions and orientations. It cannot know another person's private thoughts or guarantee future events.",
  artCredit:
    "Original artwork: Pamela Colman Smith · Rider–Waite–Smith, Pam-A scans via Wikimedia Commons (public domain).",
  source: "Card artwork & sources",
  tarotFaqs: [
    {
      q: "Can I choose my own tarot cards?",
      a: "Yes. The deck is spread face down after shuffling. Choose any card and place it in a selected spread position, or use the free table to arrange it yourself.",
    },
    {
      q: "Can I change cards or read without AI?",
      a: "Yes. Return a card to the deck or select a spread position and choose a replacement. Turn cards over one by one and read the built-in meanings. The AI button is entirely optional.",
    },
    {
      q: "Which tarot spreads are available?",
      a: "One card, three cards, a five-card relationship spread, a five-card two-paths spread, and the ten-card Celtic Cross. The free table lets you create your own layout.",
    },
  ],
};
export type CelestialCopy = typeof en;
const zh: CelestialCopy = {
  home: "首页",
  astrology: "星盘",
  tarot: "塔罗牌桌",
  back: "返回 DestinyPixel",
  free: "免费体验 · 无需注册",
  loading: "稍等片刻…",
  error: "暂时没能完成，请检查输入资料后重试。",
  retry: "重试",
  aiReady: "解读已生成",
  method: "计算与解读方式",
  ai: "帮我解读",
  aiBusy: "正在串起这些线索…",
  aiNote:
    "只在你点击后：星盘位置，或已翻开的牌、问题与选填背景，会发送至 DeepSeek。塔罗请求不会自动附带出生资料；请勿在问题或背景中填写身份信息。",
  aiUnavailable:
    "AI 解读暂时不可用。星盘和牌面仍保留，你可以自行查看，或稍后重试。",
  aiLimited: "本次免费解读额度暂时用完，请稍后再试。星盘和牌桌仍可继续使用。",
  reflection:
    "用于象征性探索与自我观察，不是科学人格测评，也不保证未来事件。重要决定请结合现实情况。",
  astroTitle: "免费星盘查询：上升星座、行星宫位与 AI 解读 | DestinyPixel",
  astroDescription:
    "输入出生日期、时间和地点，生成十颗星体、上升星座、整宫制宫位、逆行与相位的详细星盘。点选星体探索，也可获取 AI 解读。",
  astroEyebrow: "从出生那一刻，认识更完整的自己",
  astroHeading: "不止一个星座。\n看见你的整个星空。",
  astroIntro:
    "太阳代表的只是其中一面。让月亮、上升与十颗星体之间的联系，组成一张可以慢慢探索的出生星盘。",
  astroCta: "绘制我的星盘",
  date: "出生日期",
  time: "当地出生时间",
  city: "出生地点",
  chooseCity: "选择城市",
  custom: "其他地点 · 输入经纬度",
  latitude: "纬度（−90 至 90）",
  longitude: "经度（−180 至 180）",
  timezone: "IANA 时区",
  timezoneHelp:
    "例如 Asia/Shanghai、Europe/London。请选择出生地点的时区，系统会按出生日期处理夏令时。",
  exactTime:
    "请尽量使用出生记录上的时间，上升与宫位会随时间变化。不知道时刻时，猜测的结果不能当作准确星盘。",
  formTitle: "从你的出生信息开始",
  privacy: "资料通过服务器计算。只有你点击保存时，星盘才会存入账号；出生资料不会放入网址。",
  calculate: "展开我的星盘",
  example: "示例星盘 · 并非你的测算结果",
  result: "你的出生星盘",
  sun: "太阳",
  moon: "月亮",
  rising: "上升",
  mc: "天顶",
  planets: "行星",
  houses: "宫位",
  aspects: "相位",
  elementTitle: "四元素分布",
  elements: ["火", "土", "风", "水"],
  house: "宫",
  retrograde: "逆行",
  direct: "顺行",
  degree: "位置",
  orb: "容许度",
  noAspects: "六度容许范围内暂无主要相位。",
  planetHint: "点选图上的星体，或从列表中选择，看看它代表生活中的哪一面。",
  wheelExplore: "探索你的星盘",
  wheelPreview: "悬停预览",
  wheelPinned: "已固定选中",
  wheelClear: "查看全盘",
  wheelHelp: "鼠标滑过星体或相位线，即可预览；点击后固定高亮。手机直接点选即可，再点一次、点空白处，或点「查看全盘」取消。",
  houseHint:
    "采用整宫制：上升所在星座为第一宫，每个星座占一整宫。天顶单独标记，不一定落在第十宫。",
  aspectHint:
    "展示星体之间的主要角度关系，统一采用 6° 容许度。相位不是好坏评分。",
  astroMethod:
    "使用 Astronomy Engine 计算真实出生时刻的地心、热带黄道星体位置。上升为东方地平线与黄道的交点，宫位采用整宫制，逆行为一天区间内的视运动方向。四元素图对十颗星体等权计数，并非人格强弱测量。AI 只负责解释已算出的星盘，不生成天文位置。",
  astroFaqs: [
    {
      q: "星盘计算需要 AI 吗？",
      a: "不需要。星体、上升、天顶、宫位和相位由程序确定性计算。AI 是可选的文字解读，用来串联同一张星盘里的象征含义。",
    },
    {
      q: "为什么与其他网站的星盘不同？",
      a: "先核对出生时间、历史时区、经纬度、热带或恒星黄道，以及宫制。本站采用热带黄道与整宫制，不是普拉西德宫制。",
    },
    {
      q: "出生时刻碰到夏令时切换怎么办？",
      a: "系统会拒绝不存在或有歧义的当地时刻，不会悄悄替你选一个。请先核对出生记录与当地那一天的调时情况。",
    },
  ],
  signs: [
    "白羊座",
    "金牛座",
    "双子座",
    "巨蟹座",
    "狮子座",
    "处女座",
    "天秤座",
    "天蝎座",
    "射手座",
    "摩羯座",
    "水瓶座",
    "双鱼座",
  ],
  planetNames: [
    "太阳",
    "月亮",
    "水星",
    "金星",
    "火星",
    "木星",
    "土星",
    "天王星",
    "海王星",
    "冥王星",
  ],
  planetRoles: [
    "自我认同、生命力，以及你希望创造什么。",
    "情绪习惯、安全感与归属需要。",
    "思考、学习和把想法说出来的方式。",
    "你欣赏什么，以及怎样建立亲密连接。",
    "行动、表达主张与面对阻力的方式。",
    "你在哪里寻找成长、意义和可能性。",
    "责任、边界，以及长期磨炼一项能力。",
    "独立、变化和不循常规的想法。",
    "想象、共情，以及容易模糊的边界。",
    "深层转变、执着与面对力量的方式。",
  ],
  signStyles: [
    "直接、主动，愿意先尝试再调整。",
    "稳定、重感受，关注切实的价值。",
    "好奇、善交流，愿意接触不同观点。",
    "敏感、有保护欲，重视情绪环境。",
    "善于表达、慷慨，希望让事物焕发生命力。",
    "观察细致、务实，关注可以改进之处。",
    "重视关系、平衡，能看见不同立场。",
    "投入、洞察，想了解表象之下的事情。",
    "坦率、爱探索，需要更宽广的视野。",
    "有规划、有结构，愿意用时间积累。",
    "独立、重理念，也关心群体与未来。",
    "富于想象和同情心，容易感受环境氛围。",
  ],
  houseNames: [
    "自我与第一印象",
    "价值与资源",
    "学习与沟通",
    "家庭与根基",
    "创作与快乐",
    "日常与工作习惯",
    "伴侣与契约",
    "共享资源与亲密",
    "信念与远行",
    "事业与公众角色",
    "朋友与群体",
    "独处与内在世界",
  ],
  aspectNames: {
    conjunction: "合相",
    sextile: "六合",
    square: "刑相",
    trine: "三合",
    opposition: "对冲",
  },
  aspectMeanings: {
    conjunction:
      "两种功能在同一处相遇，理解它们的重叠，有助于更有意识地使用彼此。",
    sextile: "存在互相配合的机会，通常需要主动参与，才会转化成实际帮助。",
    square: "不同需求需要磨合，一个可持续的小习惯，可能让张力变成行动。",
    trine: "相对顺畅的连接可以成为优势，也值得留意哪些长处被你当成理所当然。",
    opposition: "两个方向都需要空间，试着找到平衡，而不是只选择其中一面。",
  },
  tarotTitle: "免费在线塔罗：自由洗牌、选牌、排阵与 AI 解读 | DestinyPixel",
  tarotDescription:
    "完整78张经典塔罗牌，支持手指或鼠标洗牌、自选牌、自由摆放和逐张翻牌。单张、三张、感情、选择与凯尔特十字排阵，可选 AI 解读。",
  tarotEyebrow: "为眼前的问题，留一点安静的空间",
  tarotHeading: "心里一个问题。\n手里一副可能。",
  tarotIntro:
    "慢下来，洗一洗牌，选择此刻想拿起的那张。跟随熟悉的排阵，也可以把整张牌桌留给自己。",
  freeMode: "自由牌桌",
  backToTable: "回到牌桌",
  spreadMode: "排阵模式",
  freeHelp:
    "从下方牌堆选择，再用手指或鼠标拖动到牌桌任意位置。点牌翻开，再点查看牌义；工具栏可旋转或放回。键盘方向键也可移动。",
  spreadHelp:
    "先选排阵，点一个空牌位，再从下方挑选背面牌。点已放好的牌翻开，再点查看牌义；选中已有牌的牌位，也能换一张。",
  spreadLabel: "选择排阵",
  spreads: {
    single: "一张牌 · 当下提醒",
    three: "三张牌 · 来路与下一步",
    relationship: "五张牌 · 关系探索",
    choice: "五张牌 · 两条道路",
    celtic: "十张牌 · 凯尔特十字",
  },
  positions: {
    single: ["此刻的关注点"],
    three: ["走到这里的来路", "当下的状态", "可能的下一步"],
    relationship: [
      "你的视角",
      "对方可能的视角",
      "彼此的连接",
      "需要磨合之处",
      "你能采取的一步",
    ],
    choice: [
      "最在意的事情",
      "道路 A · 机会",
      "道路 A · 挑战",
      "道路 B · 机会",
      "道路 B · 挑战",
    ],
    celtic: [
      "当前处境",
      "交叉的影响",
      "内在根源",
      "近期过去",
      "意识中的关注",
      "可能的发展",
      "你的应对方式",
      "周围环境",
      "希望与顾虑",
      "潜在结果",
    ],
  },
  reversals: "加入逆位",
  shuffle: "洗匀剩余牌",
  shuffleTouch: "在牌堆上左右划动，亲手洗牌",
  shuffled: "牌已洗匀",
  reset: "重新开始一局",
  resetCheck: "清空当前牌桌，重新开始吗？",
  deckTitle: "顺着直觉，选一张。",
  deckShortTitle: "选一张，放到牌桌",
  shuffleShort: "洗牌",
  dropHint: "向上拖到牌桌，也可以点选放牌",
  ribbonStart: "先点洗牌，再从下方挑选。",
  ribbonHelp: "滑动挑牌；再点探出的牌、向上拖，或点按钮放到牌桌。",
  previousCard: "前一张牌",
  nextCard: "后一张牌",
  drawSelected: "放到牌桌",
  deckHelp:
    "翻开前，牌面始终隐藏。完整78张互不重复，已拿到桌上的牌不会被再次抽到。",
  remaining: "张待选",
  cardBack: "背面牌",
  position: "牌位",
  pick: "选择",
  selected: "当前牌位",
  empty: "从下方选择一张",
  reveal: "翻开",
  conceal: "盖回",
  returnCard: "放回牌堆",
  rotate: "旋转",
  upright: "正位",
  reversed: "逆位",
  cardMeaning: "看看这张牌",
  question: "你想问什么？（详解必填）",
  viewCard: "查看牌义",
  closeCard: "关闭牌义",
  detailCta: "结合我的问题详细解读",
  detailTitle: "围绕你的问题，进一步解读",
  questionRequired: "请先写下你想问的事，再开始详细解读。",
  details: "详细情况（选填）",
  detailsPlaceholder: "可以写事情的背景、目前的进展，以及你最在意或犹豫的部分。",
  detailsNote: "可以留空。描述越具体，解读越能贴合你的问题。请勿填写姓名、联系方式等身份信息。",
  questionPlaceholder: "例如：我该如何面对这段关系接下来的沟通？",
  questionNote: "一次只关注一个问题，不必填写姓名或私人资料。",
  readyHint: "翻开所有已选牌后，即可请 AI 帮忙解读；排阵模式需先填满牌位。",
  emptyTable: "一张空牌桌，留给你的可能。",
  emptyTableHint: "先洗牌，再从下方选出第一张。",
  shuffledCount: "洗牌次数",
  allRevealed: "你的牌已经可以解读了",
  tarotMethod:
    "使用完整78张韦特体系塔罗牌。洗牌采用浏览器的安全随机数，不会按你的问题调整牌面。开启逆位时，洗牌会同时随机设置方向。自由牌桌可使用全部78张牌，位置和角度由你安排。牌义是本站整理的简要解读，AI 只解释你实际抽到的牌、牌位与正逆位；它不能知道别人的真实心思，也不能保证未来事件。",
  artCredit:
    "原画：Pamela Colman Smith · 韦特体系 Pam-A 版本，扫描图来自 Wikimedia Commons（公有领域）。",
  source: "牌面来源与署名",
  tarotFaqs: [
    {
      q: "可以自己洗牌、挑牌吗？",
      a: "可以。洗牌后会将牌的背面全部排开，由你亲自挑选。排阵模式放进指定牌位，自由模式则可以随意拖动摆放。",
    },
    {
      q: "可以换牌，或不使用 AI 吗？",
      a: "可以。牌可放回牌堆，也可以选中牌位后重新挑一张。逐张翻开后能查看基础牌义，AI 解读按钮完全自选。",
    },
    {
      q: "有哪些塔罗排阵？",
      a: "提供单张、三张、五张关系探索、五张两条道路和十张凯尔特十字。你也可以在自由牌桌中摆出自己的排阵。",
    },
  ],
};
const ru: CelestialCopy = {
  home: "Главная",
  astrology: "Натальная карта",
  tarot: "Таро",
  back: "Вернуться в DestinyPixel",
  free: "Бесплатно · без регистрации",
  loading: "Одну минуту…",
  error: "Не удалось завершить. Проверьте данные и попробуйте ещё раз.",
  retry: "Повторить",
  aiReady: "Толкование готово",
  method: "Как это работает",
  ai: "Помочь с толкованием",
  aiBusy: "Соединяем символы…",
  aiNote:
    "Только по вашему запросу: положения планет или открытые карты, вопрос и необязательный контекст отправляются в DeepSeek. Имя и дата рождения не передаются ИИ. Не указывайте личные данные в вопросе.",
  aiUnavailable:
    "Толкование ИИ временно недоступно. Карта и расклад сохранены на экране — изучите их самостоятельно или повторите позже.",
  aiLimited:
    "Лимит бесплатных толкований временно исчерпан. Попробуйте позже; карта и колода остаются доступны.",
  reflection:
    "Символический взгляд для размышления, а не научный тест личности или предсказание. Важные решения соотносите с реальными обстоятельствами.",
  astroTitle:
    "Бесплатная натальная карта: асцендент, дома и аспекты | DestinyPixel",
  astroDescription:
    "Рассчитайте тропическую натальную карту с десятью планетами, асцендентом, полнознаковыми домами, ретроградностью и аспектами. Интерактивная карта и необязательное толкование ИИ.",
  astroEyebrow: "НЕБО В МОМЕНТ ВАШЕГО РОЖДЕНИЯ",
  astroHeading: "Больше, чем знак Солнца.\nВаша карта целиком.",
  astroIntro:
    "Исследуйте Луну, асцендент и связи между десятью планетами — шаг за шагом, в одной личной карте рождения.",
  astroCta: "Построить мою карту",
  date: "Дата рождения",
  time: "Местное время рождения",
  city: "Место рождения",
  chooseCity: "Выберите город",
  custom: "Другое место · координаты",
  latitude: "Широта (от −90 до 90)",
  longitude: "Долгота (от −180 до 180)",
  timezone: "Часовой пояс IANA",
  timezoneHelp:
    "Например Europe/Moscow или America/New_York. Укажите пояс места рождения: исторический переход на летнее время учитывается автоматически.",
  exactTime:
    "Используйте время из записи о рождении: от него зависят асцендент и дома. Если время неизвестно, предположение не даст точную карту.",
  formTitle: "Начните с данных рождения",
  privacy:
    "Расчёт выполняется на сервере. Карта сохраняется в аккаунте только по вашему выбору; данные рождения не включаются в адрес страницы.",
  calculate: "Открыть мою карту",
  example: "ПРИМЕР КАРТЫ · НЕ ВАШ РЕЗУЛЬТАТ",
  result: "ВАША НАТАЛЬНАЯ КАРТА",
  sun: "Солнце",
  moon: "Луна",
  rising: "Асцендент",
  mc: "Середина неба",
  planets: "Планеты",
  houses: "Дома",
  aspects: "Аспекты",
  elementTitle: "Баланс стихий",
  elements: ["Огонь", "Земля", "Воздух", "Вода"],
  house: "Дом",
  retrograde: "Ретроградная",
  direct: "Прямое движение",
  degree: "Положение",
  orb: "Орбис",
  noAspects: "Основных аспектов с орбисом до шести градусов нет.",
  planetHint:
    "Выберите планету на карте или в списке, чтобы узнать её символическую роль.",
  wheelExplore: "ИССЛЕДУЙТЕ КАРТУ",
  wheelPreview: "ПРЕДПРОСМОТР",
  wheelPinned: "ВЫБОР ЗАКРЕПЛЁН",
  wheelClear: "Вся карта",
  wheelHelp: "Наведите курсор на планету или линию аспекта для подсказки; нажмите, чтобы закрепить. На телефоне коснитесь элемента. Повторное нажатие, касание пустого места или кнопка «Вся карта» снимает выделение.",
  houseHint:
    "Каждому дому соответствует целый знак. Знак асцендента — первый дом. Середина неба отмечена отдельно и может находиться вне десятого дома.",
  aspectHint:
    "Основные угловые связи планет с единым максимальным орбисом 6°. Это не оценка совместимости.",
  astroMethod:
    "Astronomy Engine рассчитывает геоцентрические положения в тропической эклиптике даты по точному моменту UTC. Асцендент — пересечение эклиптики с восточным горизонтом. Используется полнознаковая система домов. Ретроградность определяется по видимому движению за сутки. Стихии подсчитываются для десяти планет с одинаковым весом и не измеряют личность. ИИ толкует готовую карту, а не вычисляет положения.",
  astroFaqs: [
    {
      q: "Нужен ли ИИ для расчёта натальной карты?",
      a: "Нет. Положения планет, углы, дома и аспекты вычисляются без ИИ. По желанию ИИ добавит символическое письменное толкование этой же карты.",
    },
    {
      q: "Почему результат отличается от другого сайта?",
      a: "Сверьте время, исторический часовой пояс, координаты, тропический или сидерический зодиак и систему домов. Здесь используются тропический зодиак и полнознаковые дома, не Плацидус.",
    },
    {
      q: "Что происходит при переводе часов?",
      a: "Несуществующее или неоднозначное местное время не принимается автоматически. Сверьте запись о рождении с правилами перевода часов в тот день.",
    },
  ],
  signs: [
    "Овен",
    "Телец",
    "Близнецы",
    "Рак",
    "Лев",
    "Дева",
    "Весы",
    "Скорпион",
    "Стрелец",
    "Козерог",
    "Водолей",
    "Рыбы",
  ],
  planetNames: [
    "Солнце",
    "Луна",
    "Меркурий",
    "Венера",
    "Марс",
    "Юпитер",
    "Сатурн",
    "Уран",
    "Нептун",
    "Плутон",
  ],
  planetRoles: [
    "Самоощущение, жизненная сила и то, что хочется создавать.",
    "Эмоциональные привычки, уют и потребность в принадлежности.",
    "Мышление, обучение и выражение мыслей словами.",
    "То, что вы цените, и способы строить близость.",
    "Действие, самоутверждение и встреча с сопротивлением.",
    "Поиск роста, смысла и новых возможностей.",
    "Ответственность, границы и постепенное мастерство.",
    "Независимость, перемены и нестандартные идеи.",
    "Воображение, сочувствие и размытые границы.",
    "Глубокие изменения, привязанности и отношение к силе.",
  ],
  signStyles: [
    "Прямота, инициатива и готовность пробовать.",
    "Устойчивость, чувственность и осязаемая ценность.",
    "Любопытство, общение и разные точки зрения.",
    "Забота, восприимчивость и внимание к чувствам.",
    "Выразительность, щедрость и творческий импульс.",
    "Наблюдательность, практичность и улучшение деталей.",
    "Отношения, равновесие и учёт разных позиций.",
    "Глубина, проницательность и внимание к скрытому.",
    "Исследование, откровенность и широкий горизонт.",
    "Структура, выдержка и последовательное развитие.",
    "Независимость, идеи и интерес к сообществу.",
    "Воображение, сострадание и чувствительность к атмосфере.",
  ],
  houseNames: [
    "Личность и первое впечатление",
    "Ценности и ресурсы",
    "Учёба и общение",
    "Дом и корни",
    "Творчество и удовольствие",
    "Режим и ежедневная работа",
    "Партнёрство и договорённости",
    "Общие ресурсы и близость",
    "Убеждения и открытия",
    "Призвание и публичная жизнь",
    "Друзья и сообщество",
    "Уединение и внутренний мир",
  ],
  aspectNames: {
    conjunction: "Соединение",
    sextile: "Секстиль",
    square: "Квадрат",
    trine: "Трин",
    opposition: "Оппозиция",
  },
  aspectMeanings: {
    conjunction:
      "Две функции сходятся вместе. Заметив их связь, легче пользоваться обеими осознанно.",
    sextile:
      "Возможность сотрудничества, для которой обычно нужно ваше участие.",
    square:
      "Разные потребности требуют настройки. Полезная привычка может превратить напряжение в действие.",
    trine:
      "Естественная связь, на которую можно опереться, не принимая её как должное.",
    opposition:
      "Два полюса просят равновесия. Дайте место обоим, а не только одной стороне.",
  },
  tarotTitle:
    "Таро онлайн бесплатно: тасуйте, выбирайте карты и расклады | DestinyPixel",
  tarotDescription:
    "Полная колода из 78 карт. Выбирайте, перемещайте и открывайте карты самостоятельно. Свободный стол, расклады на одну и три карты, отношения и Кельтский крест с толкованием ИИ по желанию.",
  tarotEyebrow: "ПРОСТРАНСТВО ДЛЯ ДРУГОГО ВЗГЛЯДА",
  tarotHeading: "Ваш вопрос.\nВаши руки. Ваши карты.",
  tarotIntro:
    "Сделайте вдох, перемешайте колоду и выберите карту. Попробуйте знакомый расклад или устройте стол по-своему.",
  freeMode: "Свободный стол",
  backToTable: "К столу",
  spreadMode: "Готовые расклады",
  freeHelp:
    "Выберите карты в колоде и перетаскивайте их пальцем или мышью. Нажмите на карту, чтобы открыть, и ещё раз — для значения. Повернуть или вернуть её можно кнопками. Стрелки клавиатуры также перемещают карту.",
  spreadHelp:
    "Выберите расклад и пустую позицию, затем любую закрытую карту внизу. Нажмите на выложенную карту, чтобы открыть, и ещё раз — для значения. Выберите занятую позицию, чтобы заменить карту.",
  spreadLabel: "Расклад",
  spreads: {
    single: "Одна карта · фокус",
    three: "Три карты · путь",
    relationship: "Отношения · 5 карт",
    choice: "Два пути · 5 карт",
    celtic: "Кельтский крест · 10 карт",
  },
  positions: {
    single: ["Фокус настоящего"],
    three: [
      "Что привело сюда",
      "Что происходит сейчас",
      "Возможный следующий шаг",
    ],
    relationship: [
      "Ваш взгляд",
      "Возможный взгляд другого",
      "Что вас соединяет",
      "Где вы различаетесь",
      "Ваш следующий шаг",
    ],
    choice: [
      "Что важнее всего",
      "Путь А · возможность",
      "Путь А · трудность",
      "Путь Б · возможность",
      "Путь Б · трудность",
    ],
    celtic: [
      "Текущая ситуация",
      "Пересекающее влияние",
      "Глубинная основа",
      "Недавнее прошлое",
      "Сознательный фокус",
      "Возможное направление",
      "Ваш подход",
      "Окружение",
      "Надежды и тревоги",
      "Возможный итог",
    ],
  },
  reversals: "Перевёрнутые карты",
  shuffle: "Перемешать оставшиеся",
  shuffleTouch: "Проведите по колоде, чтобы перемешать вручную",
  shuffled: "Колода перемешана",
  reset: "Новый расклад",
  resetCheck: "Очистить стол и начать заново?",
  deckTitle: "Следуйте любопытству. Выберите карту.",
  deckShortTitle: "Выберите карту",
  shuffleShort: "Перемешать",
  dropHint: "Потяните к столу или нажмите, чтобы выложить",
  ribbonStart: "Перемешайте колоду и выберите карту ниже.",
  ribbonHelp: "Листайте карты. Нажмите приподнятую ещё раз, потяните вверх или используйте кнопку.",
  previousCard: "Предыдущая карта",
  nextCard: "Следующая карта",
  drawSelected: "На стол",
  deckHelp:
    "Лицевая сторона скрыта, пока вы не откроете карту на столе. В колоде 78 разных карт; выложенная карта не выпадет повторно.",
  remaining: "осталось",
  cardBack: "Закрытая карта",
  position: "Позиция",
  pick: "Выбрать",
  selected: "Выбранная позиция",
  empty: "Выберите карту внизу",
  reveal: "Открыть",
  conceal: "Закрыть",
  returnCard: "Вернуть в колоду",
  rotate: "Повернуть",
  upright: "Прямая",
  reversed: "Перевёрнутая",
  cardMeaning: "Исследовать карту",
  question: "Что вы хотите спросить? (для толкования обязательно)",
  viewCard: "Значение карты",
  closeCard: "Закрыть значение карты",
  detailCta: "Перейти к вопросу",
  detailTitle: "Толкование вашей ситуации",
  questionRequired: "Сначала напишите вопрос для подробного толкования.",
  details: "Подробности ситуации (необязательно)",
  detailsPlaceholder: "Что уже произошло? Между чем вы выбираете и что для вас важнее всего?",
  detailsNote: "Конкретный контекст помогает связать толкование с вашей ситуацией. Можно оставить поле пустым. Не указывайте имена, контакты и другие личные данные.",
  questionPlaceholder: "Что поможет мне яснее понять эту ситуацию?",
  questionNote: "Один вопрос за раз. Имена и личные сведения не нужны.",
  readyHint:
    "Откройте все выбранные карты для толкования. В готовом раскладе нужно заполнить все позиции.",
  emptyTable: "Пустой стол. Новые возможности.",
  emptyTableHint: "Перемешайте колоду и выберите первую карту внизу.",
  shuffledCount: "Перемешиваний",
  allRevealed: "Карты готовы к толкованию",
  tarotMethod:
    "Цифровая колода Райдера—Уэйта—Смит содержит 78 карт. Для тасования используется криптографическая случайность браузера: вопрос не влияет на выбор карт. При включённой опции перевёрнутость назначается во время тасования. Свободный стол вмещает все 78 карт. Краткие значения — наша редакционная интерпретация. ИИ читает только выбранные карты с их позициями и ориентацией. Он не знает чужих мыслей и не гарантирует будущих событий.",
  artCredit:
    "Рисунки: Памела Колман Смит · Райдер—Уэйт—Смит, сканы Pam-A с Wikimedia Commons (общественное достояние).",
  source: "Источники иллюстраций",
  tarotFaqs: [
    {
      q: "Можно ли самому выбрать карты Таро?",
      a: "Да. После тасования колода разложена рубашками вверх. Выберите любую карту для позиции расклада или свободно разместите её на столе.",
    },
    {
      q: "Можно ли заменить карты и обойтись без ИИ?",
      a: "Да. Верните карту в колоду или выберите занятую позицию и замените карту. Встроенные значения доступны после переворота. ИИ используется только по желанию.",
    },
    {
      q: "Какие расклады доступны?",
      a: "Одна карта, три карты, пять карт на отношения, пять карт для двух путей и Кельтский крест из десяти карт. На свободном столе можно создать свой расклад.",
    },
  ],
};
export function celestialCopy(locale: ReportLocale): CelestialCopy {
  return locale === "zh-TW"
    ? traditional(zh)
    : locale === "zh"
      ? zh
      : locale === "ru"
        ? ru
        : en;
}
