import type { ReportLocale } from "@/lib/report-i18n";
import { toTraditional } from "@/lib/journal-locales";
const en = {
  save: "Save to my account", update: "Update saved record", saved: "Saved to your account", busy: "Saving…", account: "My account", open: "Open saved record",
  title: "Keep this reading", note: "Save this chart or card layout and its current AI reading to your private account. Reopening a saved reading does not run AI again. You can delete it from your account.",
  withoutAi: "No AI reading yet: this saves the chart or cards only. After generating an interpretation, save again to include it.",
  login: "Log in", register: "Create account", authTitle: "A home for your reading", authNote: "Your result stays here. After logging in or registering, it will be saved automatically.",
  email: "Email", password: "Password", confirmPassword: "Confirm password", mismatch: "The passwords do not match.", close: "Close", submitting: "Please wait…", error: "Could not save. Your result is still on this page; please try again.", authError: "Could not sign in. Check your details and try again.", invalidCredentials: "Email or password is incorrect.", emailTaken: "An account already uses this email. Please log in.", limited: "Too many attempts. Please wait a few minutes and try again.", recovery: "Password help (opens a new tab)",
  listTitle: "My astrology & tarot records", adminTitle: "Astrology & tarot records", listNote: "Return to your saved charts, card layouts and interpretations. AI is not run again when you open a record.", adminNote: "Record metadata only. Deleting a record removes its stored chart or cards and interpretation from the member’s account.", empty: "No saved records yet. Save one from the astrology or tarot page.", astrology: "Birth chart", tarot: "Tarot reading", ai: "AI reading included", basic: "Chart / cards only", remove: "Delete", deleting: "Deleting…", deleteConfirm: "Delete this saved record and its interpretation? This cannot be undone.", cancel: "Cancel", more: "Load more", refresh: "Refresh", loading: "Loading saved records…", unavailable: "Records could not be loaded. Please try again.", missing: "This record is unavailable or belongs to another account.", loginToView: "Log in to the account that saved this record.", savedDate: "Last saved", member: "Account ID", question: "Your saved question", noReading: "An AI interpretation was not saved with this record.", newReading: "Start a new reading", private: "Private saved record", emptyCard: "Face down", flip: "Turn over", consent: "By continuing, you agree to the service terms and privacy notice.", terms: "Service terms", privacy: "Privacy",
};
const zh: typeof en = {
  save: "保存到我的账号", update: "更新已保存的记录", saved: "已保存到你的账号", busy: "正在保存…", account: "我的账号", open: "查看已保存记录",
  title: "把这次解读留下来", note: "将当前星盘或牌阵及已生成的 AI 解读保存到私人账号。再次打开直接阅读，不会重新调用 AI；你可以在账号中删除。",
  withoutAi: "当前还没有 AI 解读，本次只保存星盘或牌阵。之后生成解读，再点一次保存即可补充进去。",
  login: "登录", register: "注册账号", authTitle: "为这次解读安一个家", authNote: "结果会保留在当前页面。登录或注册成功后，自动完成保存。",
  email: "邮箱", password: "密码", confirmPassword: "确认密码", mismatch: "两次输入的密码不一致。", close: "关闭", submitting: "请稍候…", error: "保存未成功，结果仍在当前页面，请重试。", authError: "登录未成功，请核对信息后重试。", invalidCredentials: "邮箱或密码不正确。", emailTaken: "这个邮箱已有账号，请直接登录。", limited: "尝试次数较多，请稍等几分钟后重试。", recovery: "找回密码（新窗口打开）",
  listTitle: "我的星盘与塔罗记录", adminTitle: "星盘与塔罗记录管理", listNote: "随时回来查看保存的星盘、牌阵和解读，打开记录不会重新运行 AI。", adminNote: "这里只列示记录信息。删除后，会员账号中保存的星盘或牌阵及其解读也会一并移除。", empty: "还没有保存记录，可以从星盘或塔罗页面保存。", astrology: "出生星盘", tarot: "塔罗记录", ai: "含 AI 解读", basic: "仅星盘 / 牌阵", remove: "删除", deleting: "正在删除…", deleteConfirm: "删除这份保存记录及其解读？删除后无法恢复。", cancel: "取消", more: "加载更多", refresh: "刷新", loading: "正在读取保存记录…", unavailable: "暂时无法读取记录，请重试。", missing: "记录不存在、已删除，或不属于当前账号。", loginToView: "请登录保存这份记录的账号。", savedDate: "最近保存", member: "账号编号", question: "当时的问题", noReading: "这份记录尚未保存 AI 解读。", newReading: "开始新一次探索", private: "私人保存记录", emptyCard: "尚未翻开", flip: "翻开", consent: "继续即表示你同意服务说明和隐私说明。", terms: "服务说明", privacy: "隐私说明",
};
const ru: typeof en = {
  save: "Сохранить в аккаунт", update: "Обновить запись", saved: "Сохранено в аккаунте", busy: "Сохраняем…", account: "Мой аккаунт", open: "Открыть запись",
  title: "Сохраните этот разбор", note: "Сохраните карту или расклад вместе с готовым разбором ИИ в личном аккаунте. При повторном открытии ИИ не запускается. Запись можно удалить из аккаунта.", withoutAi: "Разбора ИИ пока нет: сохраняется только карта или расклад. После получения разбора сохраните запись ещё раз.",
  login: "Войти", register: "Создать аккаунт", authTitle: "Ваше место для разборов", authNote: "Результат останется на этой странице. После входа или регистрации он сохранится автоматически.", email: "Электронная почта", password: "Пароль", confirmPassword: "Повторите пароль", mismatch: "Пароли не совпадают.", close: "Закрыть", submitting: "Подождите…", error: "Не удалось сохранить. Результат остался на странице — попробуйте ещё раз.", authError: "Не удалось войти. Проверьте данные.", invalidCredentials: "Неверная почта или пароль.", emailTaken: "Этот адрес уже зарегистрирован. Войдите в аккаунт.", limited: "Слишком много попыток. Повторите через несколько минут.", recovery: "Помощь с паролем (новая вкладка)",
  listTitle: "Мои карты и расклады", adminTitle: "Управление картами и раскладами", listNote: "Возвращайтесь к сохранённым картам, раскладам и разборам без повторного запуска ИИ.", adminNote: "Только метаданные. Удаление убирает сохранённую карту или расклад и разбор из аккаунта участника.", empty: "Пока нет записей. Сохраните результат на странице астрологии или таро.", astrology: "Натальная карта", tarot: "Расклад таро", ai: "С разбором ИИ", basic: "Только карта / расклад", remove: "Удалить", deleting: "Удаляем…", deleteConfirm: "Удалить эту запись вместе с разбором? Отменить удаление нельзя.", cancel: "Отмена", more: "Загрузить ещё", refresh: "Обновить", loading: "Загружаем записи…", unavailable: "Не удалось загрузить записи. Попробуйте ещё раз.", missing: "Запись удалена, недоступна или принадлежит другому аккаунту.", loginToView: "Войдите в аккаунт, в котором сохранена эта запись.", savedDate: "Последнее сохранение", member: "ID аккаунта", question: "Сохранённый вопрос", noReading: "Разбор ИИ не сохранён в этой записи.", newReading: "Начать новый разбор", private: "Личная сохранённая запись", emptyCard: "Рубашкой вверх", flip: "Перевернуть", consent: "Продолжая, вы принимаете условия сервиса и политику конфиденциальности.", terms: "Условия сервиса", privacy: "Конфиденциальность",
};
export function recordCopy(locale: ReportLocale): typeof en { return locale === "zh-TW" ? Object.fromEntries(Object.entries(zh).map(([k,v])=>[k,toTraditional(v)])) as typeof en : locale === "zh" ? zh : locale === "ru" ? ru : en; }
export const memberAccountHref = (locale: ReportLocale) => `/account${locale.startsWith("zh") ? "?locale=zh" : ""}`;
