"use client";

import { encodeTotemSnapshot } from "@/lib/totem/share";
import type { TotemShareSnapshot } from "@/lib/totem/types";

function cleanClone(svg: SVGSVGElement) {
  const clone = svg.cloneNode(true) as SVGSVGElement;

  clone.querySelectorAll('[data-ui-only="true"]').forEach((node) => node.remove());
  clone.querySelectorAll("[tabindex]").forEach((node) => node.removeAttribute("tabindex"));
  clone.querySelectorAll<SVGElement>("[data-base-opacity]").forEach((node) => {
    // Export the composed overview rather than restoring every low-priority
    // route to its raw model opacity. This keeps the ornamental hierarchy in
    // PNG/SVG identical to the on-screen unselected state.
    node.style.opacity = node.dataset.exportOpacity ?? node.style.opacity;
    if (node.dataset.selected && node.dataset.kind !== "core") {
      node.removeAttribute("filter");
    }
    node.removeAttribute("data-selected");
  });
  clone
    .querySelector('[data-geometry-root="true"]')
    ?.setAttribute("transform", "translate(500 500) scale(1) translate(-500 -500)");
  clone.removeAttribute("aria-labelledby");
  clone.removeAttribute("aria-describedby");
  clone.setAttribute("xmlns", "http://www.w3.org/2000/svg");
  clone.setAttribute("width", "2048");
  clone.setAttribute("height", "2048");
  clone.setAttribute("data-reveal", "complete");

  return clone;
}

export function serializeTotemSvg(svg: SVGSVGElement) {
  const clone = cleanClone(svg);
  const source = new XMLSerializer().serializeToString(clone);

  return `<?xml version="1.0" encoding="UTF-8"?>\n${source}`;
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 500);
}

export function downloadTotemSvg(svg: SVGSVGElement, fingerprint: string) {
  const blob = new Blob([serializeTotemSvg(svg)], {
    type: "image/svg+xml;charset=utf-8",
  });
  downloadBlob(blob, `birth-totem-${fingerprint.toLowerCase()}.svg`);
}

export async function createTotemPng(svg: SVGSVGElement) {
  const svgBlob = new Blob([serializeTotemSvg(svg)], {
    type: "image/svg+xml;charset=utf-8",
  });
  const objectUrl = URL.createObjectURL(svgBlob);

  try {
    const image = new Image();
    image.decoding = "async";
    image.src = objectUrl;
    await image.decode();

    const canvas = document.createElement("canvas");
    canvas.width = 2048;
    canvas.height = 2048;
    const context = canvas.getContext("2d");

    if (!context) throw new Error("Canvas export is unavailable in this browser.");
    context.drawImage(image, 0, 0, canvas.width, canvas.height);

    return await new Promise<Blob>((resolve, reject) => {
      canvas.toBlob(
        (blob) => (blob ? resolve(blob) : reject(new Error("PNG export failed."))),
        "image/png",
        1,
      );
    });
  } finally {
    URL.revokeObjectURL(objectUrl);
  }
}

export async function downloadTotemPng(svg: SVGSVGElement, fingerprint: string) {
  const blob = await createTotemPng(svg);
  downloadBlob(blob, `birth-totem-${fingerprint.toLowerCase()}.png`);
}

export async function shareTotem(
  svg: SVGSVGElement,
  fingerprint: string,
  locale: string,
  snapshot: TotemShareSnapshot,
) {
  const token = encodeTotemSnapshot(snapshot);
  const url = new URL("/tuteng", window.location.origin);
  url.searchParams.set("locale", locale);
  // Fragments stay in the browser and are not sent to Vercel/CDN request logs.
  url.hash = new URLSearchParams({ totem: token }).toString();
  const localized =
    locale === "ru"
      ? {
          title: "DestinyPixel · Тотем рождения",
          text: "Детерминированный тотем DestinyPixel. Ссылка содержит только производную структуру — без имени, даты, времени и места.",
        }
      : locale === "zh" || locale === "zh-TW"
        ? {
            title: `DestinyPixel · ${locale === "zh-TW" ? "本命靈構" : "本命灵构"}`,
            text:
              locale === "zh-TW"
                ? "DestinyPixel 生成的可復現本命靈構。連結只含衍生結構，不含姓名、日期、時間和地點。"
                : "DestinyPixel 生成的可复现本命灵构。链接只含衍生结构，不含姓名、日期、时间和地点。",
          }
        : {
            title: "DestinyPixel · Birth Totem",
            text: "A deterministic Birth Totem generated by DestinyPixel. The link contains derived structure only—no name, date, time, or location.",
          };
  const shareData = {
    title: localized.title,
    text: localized.text,
    url: url.toString(),
  };

  if (navigator.share) {
    const probe = new File([""], "birth-totem.png", { type: "image/png" });
    if (navigator.canShare?.({ files: [probe] })) {
      const blob = await createTotemPng(svg);
      const file = new File([blob], `birth-totem-${fingerprint.toLowerCase()}.png`, {
        type: "image/png",
      });
      try {
        await navigator.share({ ...shareData, files: [file] });
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError") return "cancelled" as const;
        throw error;
      }
    } else {
      try {
        await navigator.share(shareData);
      } catch (error) {
        if (error instanceof DOMException && error.name === "AbortError") return "cancelled" as const;
        throw error;
      }
    }
    return "shared" as const;
  }

  await navigator.clipboard.writeText(url.toString());
  return "copied" as const;
}
