import type { ReportLocale } from "@/lib/report-i18n";
import { toTraditional } from "@/lib/journal-locales";
import type { ElementConnection } from "./elements";
const en = {
  heading: "The way your two animals love", intro: "Your Day Pillar gives each of you one of our 60 animal portraits. Start with the personalities behind the cards, then explore how your five elements interact.", character: "Your animal portrait", personality: "At heart", love: "When you love", relationship: "Your five-element connection", same: "Shared element", nourishes: "A nourishing connection", controls: "A balancing connection", equal: "shares the element of", feeds: "nourishes", tempers: "tempers", between: "How this may feel together", practice: "Make space for each other", balance: "Your five-element landscape", balanceNote: "Relative counts of the four visible stems and four branch elements. These show our symbolic distribution, not measured personality traits, strength assessments or which element you need.", boundary: "This compares your Day Pillar elements. It is not a complete traditional marriage assessment: support does not guarantee harmony, and a controlling link does not mean a bad match.", sky: "A second perspective: your birth charts", animalAI: "Your animal love story", elementAI: "Your elements, in everyday life",
  stories: {
    same: "You may recognize each other's priorities quickly. That familiarity can feel restful, but the same habits can also amplify each other. Similarity is a starting point for a conversation, not proof you want the same things.",
    nourishes: "In five-element symbolism, {source}'s {from} supports {target}'s {to}. Imagine one person making room for the other's ideas to grow. It becomes a useful relationship prompt when you ask whether care flows both ways, rather than assuming one person must always give.",
    controls: "In five-element symbolism, {source}'s {from} restrains or shapes {target}'s {to}. Treat that image as a conversation about pace, standards and boundaries: an attempt to help can feel like pressure if the other person has not asked for it.",
  },
  actions: { same: "Each name one shared habit you love and one habit you would like to handle differently. Leave room for different answers.", nourishes: "{source}: ask what support is wanted before offering it. {target}: name the care you noticed and choose one concrete way to reciprocate.", controls: "{source}: ask before correcting or stepping in. {target}: explain which help feels useful and where you need to decide for yourself." },
};
const zh: typeof en = {
  heading: "你们的动物，怎样靠近彼此？", intro: "六十日柱，每一种都有自己的动物意象。先读懂你和 TA 各自的性格与爱的习惯，再看看两种五行怎样在关系中相遇。", character: "你的日柱动物", personality: "性格底色", love: "爱里的习惯", relationship: "你们的五行关系", same: "同气相应", nourishes: "相生：给予与承接", controls: "相克：磨合与边界", equal: "同属", feeds: "生", tempers: "克", between: "放进感情里，怎么理解？", practice: "让关系舒服一点的小练习", balance: "你们的五行分布", balanceNote: "按四个天干及四个地支本气统计的相对分布，仅呈现本站的象征性结构，不代表性格测量、日主强弱或喜用神判断。", boundary: "这里比较日干五行，不等于完整合婚。相生不代表一定幸福，相克也不代表不适合；还要结合完整命局与真实相处。", sky: "再换一个角度：星盘里的你们", animalAI: "两只动物的爱情故事", elementAI: "五行落到相处里",
  stories: {
    same: "你们的日干属于同一种五行，可以把它想成相似的节奏：有些在意的事不必解释太多，也可能把同一种习惯一起放大。与其默认「你应该懂我」，不如问问彼此，相似背后有没有不同的需要。",
    nourishes: "五行关系是{from}生{to}，方向为{source}到{target}。可以借这个意象观察：一方怎样提供支持，另一方怎样承接与发挥？关系里最值得照顾的，是给予能否得到回应，而不是让一个人固定扮演付出者。",
    controls: "五行关系是{from}克{to}，方向为{source}到{target}。「克」也包含约束、修整与边界的意象，可以用来讨论你们对节奏和标准的不同要求。好意提醒有没有变成压力，关键在于对方有没有真正的选择权。",
  },
  actions: { same: "各说一个喜欢的共同习惯，再说一个希望保留的不同之处。不要因为相似，就省略表达自己的需要。", nourishes: "{source}：先问对方需要哪种支持；{target}：说出自己看见的付出，再用一件具体的小事回应。照顾应该可以双向流动。", controls: "{source}：提醒或纠正之前先征求意见；{target}：说明哪些帮助让你舒服，哪些决定希望自己做。把边界说清楚，比争谁对谁错更有用。" },
};
const ru: typeof en = {
  heading: "Как любят ваши два животных", intro: "Каждому столпу дня соответствует один из 60 образов животных. Сначала познакомьтесь с характером и привычками в любви, затем сравните пять элементов.", character: "Ваш образ животного", personality: "В основе характера", love: "В любви", relationship: "Связь ваших пяти элементов", same: "Общий элемент", nourishes: "Связь поддержки", controls: "Связь сдерживания", equal: "делит элемент с", feeds: "питает", tempers: "сдерживает", between: "Как это представить в отношениях", practice: "Небольшая практика для двоих", balance: "Распределение пяти элементов", balanceNote: "Относительные доли четырёх стволов и основных элементов четырёх ветвей. Это символическая структура, а не измерение характера, силы карты или нужных вам элементов.", boundary: "Здесь сравниваются элементы дня, а не проводится полный традиционный брачный анализ. Поддержка не гарантирует гармонию, а сдерживание не означает плохую пару.", sky: "Другой ракурс: ваши натальные карты", animalAI: "История любви двух животных", elementAI: "Ваши элементы в повседневной жизни",
  stories: { same: "Ваши элементы дня совпадают. Представьте знакомый ритм: общие приоритеты могут успокаивать, но похожие привычки могут усиливать друг друга. Сходство не означает одинаковых потребностей — о них всё равно нужно говорить.", nourishes: "Связь элементов: {source} ({from}) → {target} ({to}). В символике пяти элементов это направление поддержки. Этот образ помогает обсудить, как один поддерживает идеи другого. Важно проверить взаимность заботы, а не закреплять за одним человеком роль вечного помощника.", controls: "Связь элементов: {source} ({from}) → {target} ({to}). В символике пяти элементов это направление сдерживания. Используйте образ для разговора о темпе, ожиданиях и границах: помощь может ощущаться как давление, если о ней не просили." },
  actions: { same: "Назовите одну общую привычку, которую любите, и одно различие, которое хотите сохранить. Ответы могут не совпасть.", nourishes: "{source}: спросите, какая поддержка нужна. {target}: отметьте полученную заботу и выберите конкретный способ ответить взаимностью.", controls: "{source}: спросите, прежде чем исправлять. {target}: объясните, какая помощь полезна и где вы хотите решать самостоятельно." },
};
export function baziCopy(locale: ReportLocale) { return locale === "zh-TW" ? JSON.parse(toTraditional(JSON.stringify(zh))) as typeof en : ({ en, zh, ru })[locale]; }
export function connectionText(template: string, relation: ElementConnection, people: string[], elements: Record<string, string>) { return template.replaceAll("{source}", people[relation.source]).replaceAll("{target}", people[relation.target]).replaceAll("{from}", elements[relation.sourceElement]).replaceAll("{to}", elements[relation.targetElement]); }
