import type { ReportLocale } from "@/lib/report-i18n";
import { toTraditional } from "@/lib/journal-locales";

const en = {
  title: "Free Love Compatibility: Bazi & Birth Charts | DestinyPixel",
  description: "Compare two birth charts with Bazi and astrology. Explore personality, communication, affection and everyday rhythm, with a free score and AI relationship insights.",
  eyebrow: "TWO BIRTH CHARTS. A NEW CONVERSATION.", heading: "A little closer.\nA little more understood.",
  intro: "Two birthdays, two animal portraits, one shared story. Explore your five-element connection and the little ways you show love—with birth charts as a second perspective.",
  homeTitle: "Two hearts.\nYour kind of love.", homeIntro: "Why do you click—and where do you miss each other? Compare your birth charts and find a kinder way to understand your differences.",
  nav: "Compatibility", cta: "Explore our connection", badge: "Free · No account needed", people: ["Person A", "Person B"], date: "Birth date", time: "Local birth time", city: "Birth city", choose: "Select a city", timeNote: "Use the time recorded at birth. If you do not know it, do not guess: the Moon and hour pillar can change. Supported cities are listed below.",
  submit: "Reveal our connection", loading: "Comparing your birth charts…", consent: "I have permission to use both people's birth details.", privacy: "Birth details are sent securely for calculation, not saved as a report. Only calculated chart data—not birth dates, cities or names—is sent to DeepSeek for the free AI reading.", privacyLink: "Privacy", invalid: "Check both birth dates, times and cities, and confirm permission.", failed: "We could not complete the calculation. Your details are still here; please try again shortly.", limit: "Too many requests. Please wait a little before trying again.",
  result: "YOUR CONNECTION MAP", score: "Connection index", scoreNote: "Our positive 60–100 symbolic scale. Not a success percentage, a scientific test or a verdict on your relationship.", comparisons: "Two perspectives. One conversation.", dimensions: ["Personality", "Communication", "Affection", "Everyday rhythm"], bodies: { Sun: "Sun", Moon: "Moon", Mercury: "Mercury", Venus: "Venus", Mars: "Mars" }, pillars: ["Year", "Month", "Day", "Hour"], bazi: "Four Pillars", day: "Day element", elements: { Wood: "Wood", Fire: "Fire", Earth: "Earth", Metal: "Metal", Water: "Water" },
  traits: {
    fire: ["You may lead with enthusiasm and want room to act.", "You may speak quickly and appreciate a direct answer.", "You may show affection through initiative and shared adventures.", "Movement and fresh experiences may help you reset."],
    earth: ["You may prefer reliability, tangible progress and clear plans.", "You may want specific examples and time to consider them.", "You may show affection through consistency and practical care.", "Predictable routines may help you feel settled."],
    air: ["You may explore possibilities through ideas and conversation.", "You may think out loud and want space for different viewpoints.", "You may connect through conversation, humor and shared interests.", "Mental variety and room to socialize may help you recharge."],
    water: ["You may notice emotional undertones before the practical details.", "You may listen for tone and appreciate reassurance before solutions.", "You may show affection through emotional presence and small, personal gestures.", "Quiet time and emotional check-ins may help you reset."],
  },
  tones: { flow: "An easier meeting point", mixed: "Different routes, room to connect", contrast: "A difference worth talking about" },
  actions: ["Each name one thing you admire about the other—and one difference you want to understand.", "Before advice, ask: ‘Do you want me to listen, help, or give you space?’", "Finish this sentence separately: ‘I feel cared for when you…’ Then swap answers.", "Agree on one shared ritual and one pocket of independent time this week."],
  aiTitle: "A closer look at the two of you", aiLoading: "DeepSeek is writing your free reading. Your calculated results are ready to explore.", aiReady: "Free DeepSeek reading", aiFallback: "The AI reading is temporarily unavailable or its free limit has been reached. Your calculated score and comparison remain available.", aiSections: ["What brings you together", "Where you may miss each other", "Try this together", "Ask each other"],
  method: "How this comparison works", methodBody: "Each dimension combines Bazi symbolism (30%) with tropical astrology (70%). Personality uses the Sun; communication uses Mercury; affection uses Venus and cross-chart Moon–Venus links; everyday rhythm uses the Moon and Mars. Bazi compares day elements, and four-pillar element distributions for daily rhythm. We use major angular links within 6°. The average of four dimensions is mapped onto our deliberately positive 60–100 index. These are DestinyPixel's editorial weights, not validated relationship statistics. Birth times use the city's historical time-zone rules; Bazi also uses a solar-time correction. This edition does not compare rising signs, houses or predict marriage timing.",
  faqTitle: "Before you compare", faqs: [{ q: "Is the result free?", a: "Yes: scores, side-by-side comparisons and a short AI interpretation are free, with fair-use limits on AI requests. No account or payment is required." }, { q: "Does a lower score mean we should separate?", a: "No. The index organizes symbolic themes to discuss. Shared values, respect, communication and how you treat each other matter more than this reading." }, { q: "Do we need both birth times?", a: "Yes, this version requires known local birth times and one of the supported cities. It will not invent a time or a missing location. If a city is absent, contact us to add it rather than choosing a different time zone." }],
  reset: "Compare another pair", more: "Explore an individual birth map", contact: "Request a birth city", preview: "60 ANIMALS · FIVE ELEMENTS · LOVE", spark: "Your way", space: "Their way", together: "Find your shared rhythm", notDiagnosis: "Symbolic prompts for reflection. Check them against your real experience.",
};
export type CompatibilityCopy = typeof en;
const zh: CompatibilityCopy = {
  title: "免费感情适配测试｜双人八字 × 星盘合盘 | DestinyPixel", description: "输入两人的出生资料，免费比较八字与星盘，查看性格、沟通、感情表达和日常节奏的适配评分，获得 DeepSeek 双人相处解读。",
  eyebrow: "两份出生图谱，一次更懂彼此的对话。", heading: "从心动，\n到更懂彼此。", intro: "两张生日意象卡，一段只属于你们的相遇。看看动物性格与五行如何互动，再用星盘补充，找到让彼此感受到爱的方式。", homeTitle: "你和 TA，\n是哪一种心动？", homeIntro: "你的日柱动物，遇上 TA 的会怎样？从六十动物、五行相生相克与星盘，读懂你们表达爱的小习惯。", nav: "感情适配", cta: "免费看看我们的适配", badge: "免费体验 · 无需注册", people: ["你", "TA"], date: "公历出生日期", time: "当地出生时间", city: "出生城市", choose: "请选择城市", timeNote: "请使用出生记录中的当地时间。不知道时辰时请勿随意填写，月亮位置与时柱可能因此变化。目前支持下方列出的城市。",
  submit: "看看我们的相处图谱", loading: "正在比较两人的出生图谱…", consent: "我已获得双方同意，可以使用这些出生资料。", privacy: "出生资料通过加密连接提交计算，不保存为报告。免费 AI 解读仅向 DeepSeek 发送计算后的图谱，不发送生日、城市或姓名。", privacyLink: "隐私说明", invalid: "请核对两人的出生日期、时间、城市，并确认已获得同意。", failed: "暂时未能完成测算。填写的资料已保留，请稍后再试。", limit: "请求较频繁，请稍后再试。",
  result: "你们的相处图谱", score: "相处契合指数", scoreNote: "采用积极呈现的 60–100 分象征性量表，不是关系成功率、科学测验或感情判决。", comparisons: "读懂彼此，也看见差异。", dimensions: ["性格底色", "沟通方式", "感情表达", "日常节奏"], bodies: { Sun: "太阳", Moon: "月亮", Mercury: "水星", Venus: "金星", Mars: "火星" }, pillars: ["年柱", "月柱", "日柱", "时柱"], bazi: "八字四柱", day: "日干五行", elements: { Wood: "木", Fire: "火", Earth: "土", Metal: "金", Water: "水" },
  traits: {
    fire: ["可能更习惯带着热情行动，也希望保有主动选择的空间。", "可能表达直接、反应较快，希望得到明确回应。", "可能通过主动靠近、共同体验与热烈回应表达喜欢。", "活动身体、尝试新鲜事物，可能更容易让你恢复状态。"],
    earth: ["可能更看重可靠、实际进展，以及说到做到的计划。", "可能需要具体例子，也愿意先想清楚再回应。", "可能通过稳定陪伴、实际照顾与兑现承诺表达喜欢。", "可预期的安排和稳定习惯，可能更让你安心。"],
    air: ["可能更愿意交流想法、探索可能，也需要思考的空间。", "可能边说边整理思路，希望不同观点都能被听见。", "可能通过聊天、幽默和共同兴趣建立亲密感。", "适当的社交与新鲜话题，可能有助于你找回活力。"],
    water: ["可能先感受到情绪变化，再去处理事情本身。", "可能更留意语气，在讨论解决办法前希望先被理解。", "可能通过情绪陪伴和贴近对方的小举动表达喜欢。", "安静独处与真诚的情绪交流，可能有助于你放松。"],
  },
  tones: { flow: "比较容易接住彼此", mixed: "表达不同，也有连接空间", contrast: "值得认真聊聊的差异" }, actions: ["各说出一件欣赏对方的事，再说一个想进一步理解的不同之处。", "给建议前先问一句：「你现在想让我听你说、一起想办法，还是给你一点空间？」", "分别补完这句话：「当你做……的时候，我会觉得被爱。」然后交换答案。", "这周约定一个共同的小仪式，也给彼此留出一段独立时间。"],
  aiTitle: "再靠近一点，读懂你们", aiLoading: "DeepSeek 正在整理免费双人解读；基础评分与双方对比已就绪，可以先查看。", aiReady: "DeepSeek 免费双人解读", aiFallback: "AI 解读暂时不可用，或免费请求已达上限。已计算的评分与双方对比仍可正常查看。", aiSections: ["容易靠近的地方", "可能错过彼此的地方", "一起试一试", "问问彼此"],
  method: "这份适配结果是怎么来的？", methodBody: "每个维度由八字象征关系（30%）与西方回归黄道星盘（70%）组成。性格参考太阳；沟通参考水星；感情表达参考金星及双方月亮与金星的交叉关系；日常节奏参考月亮和火星。八字部分比较日干五行，日常节奏还参考四柱五行分布。主要相位使用 6° 容许度，四个维度取平均后呈现在主动设置的 60–100 分量表上。这些是本站的编辑权重，没有经过关系预测统计验证。出生时间按当地历史时区换算，八字另作真太阳时校正。本版不比较上升、宫位，也不预测结婚日期。",
  faqTitle: "开始前，你可能想知道", faqs: [{ q: "需要付费吗？", a: "不需要。评分、双方对比和简短 AI 解读均免费，AI 请求设有合理频率限制，无需注册或填写付款信息。" }, { q: "分数低一点，意味着不适合在一起吗？", a: "不是。指数只是整理值得交流的象征性主题。共同价值观、尊重、沟通与真实相处，比这份解读更重要。" }, { q: "一定要知道双方的出生时间吗？", a: "本版需要准确的当地出生时间，并从支持的城市中选择出生地，不会替你编造时辰。没有你的城市时可以联系我们添加，不建议选择时区不同的城市代替。" }],
  reset: "换一组资料", more: "探索个人完整出生图谱", contact: "申请添加出生城市", preview: "六十动物 · 五行互动 · 爱的表达", spark: "你的表达", space: "TA 的表达", together: "找到你们的共同节奏", notDiagnosis: "作为象征性的自我观察提示，请结合真实相处判断。",
};
const ru: CompatibilityCopy = {
  title: "Совместимость в любви: Ба-цзы и натальные карты | DestinyPixel", description: "Бесплатно сравните две карты рождения: характер, общение, проявления любви и повседневный ритм. Ба-цзы, астрология и интерпретация DeepSeek.",
  eyebrow: "ДВЕ КАРТЫ РОЖДЕНИЯ. НОВЫЙ ДИАЛОГ.", heading: "Чуть ближе.\nЧуть понятнее друг другу.", intro: "Две даты рождения, два образа животных, одна история. Узнайте, как взаимодействуют ваши пять элементов и привычки в любви. Натальные карты дополнят эту картину.", homeTitle: "Вы и ваш партнёр.\nРядом на одной карте.", homeIntro: "Что вас сближает, а где вы не слышите друг друга? Сравните карты рождения и найдите темы для тёплого разговора.", nav: "Совместимость", cta: "Узнать о нашей связи", badge: "Бесплатно · Без регистрации", people: ["Человек А", "Человек Б"], date: "Дата рождения", time: "Местное время рождения", city: "Город рождения", choose: "Выберите город", timeNote: "Укажите время из записи о рождении. Не угадывайте: положение Луны и столп часа могут измениться. Доступные города перечислены в списке.",
  submit: "Сравнить наши карты", loading: "Сравниваем карты рождения…", consent: "У меня есть согласие обоих людей на использование этих данных.", privacy: "Данные передаются по защищённому соединению для расчёта и не сохраняются как отчёт. DeepSeek получает только рассчитанные карты, без дат рождения, городов и имён.", privacyLink: "Конфиденциальность", invalid: "Проверьте даты, время, города и подтвердите согласие.", failed: "Не удалось выполнить расчёт. Введённые данные сохранены в форме; попробуйте ещё раз чуть позже.", limit: "Слишком много запросов. Подождите немного.", result: "КАРТА ВАШЕЙ СВЯЗИ", score: "Индекс созвучия", scoreNote: "Позитивная символическая шкала от 60 до 100. Это не вероятность успеха, не научный тест и не приговор отношениям.", comparisons: "Два взгляда. Один диалог.", dimensions: ["Характер", "Общение", "Проявления любви", "Повседневный ритм"], bodies: { Sun: "Солнце", Moon: "Луна", Mercury: "Меркурий", Venus: "Венера", Mars: "Марс" }, pillars: ["Год", "Месяц", "День", "Час"], bazi: "Четыре столпа", day: "Элемент дня", elements: { Wood: "Дерево", Fire: "Огонь", Earth: "Земля", Metal: "Металл", Water: "Вода" },
  traits: {
    fire: ["Вам может быть близка инициативность и свобода действовать.", "Возможно, вы говорите прямо и ждёте ясного ответа.", "Вы можете выражать любовь через инициативу и общие приключения.", "Движение и новые впечатления могут помочь вам восстановиться."],
    earth: ["Возможно, вы цените надёжность, реальные шаги и понятные планы.", "Вам могут быть нужны конкретные примеры и время обдумать ответ.", "Вы можете выражать любовь через постоянство и практическую заботу.", "Предсказуемый распорядок может дать вам ощущение опоры."],
    air: ["Возможно, вы открываете новое через идеи и разговоры.", "Вы можете размышлять вслух и ценить разные точки зрения.", "Разговоры, юмор и общие интересы могут быть вашим языком близости.", "Разнообразие и общение могут помочь вам перезагрузиться."],
    water: ["Возможно, вы замечаете эмоциональные оттенки раньше деталей.", "Для вас могут быть важны тон и понимание, а уже потом — советы.", "Вы можете выражать любовь через эмоциональную поддержку и личные мелочи.", "Тишина и искренний разговор о чувствах могут помочь вам отдохнуть."],
  }, tones: { flow: "Встречаться легче", mixed: "Разные пути к близости", contrast: "Различие, которое стоит обсудить" }, actions: ["Назовите то, что цените друг в друге, и одно различие, которое хотите понять.", "Прежде чем советовать, спросите: «Тебя выслушать, помочь или дать пространство?»", "Закончите отдельно фразу: «Я чувствую заботу, когда ты…», а затем обменяйтесь ответами.", "Договоритесь об одном общем ритуале и времени для себя на этой неделе."],
  aiTitle: "Чуть ближе друг к другу", aiLoading: "DeepSeek готовит бесплатную интерпретацию. Баллы и сравнение уже доступны.", aiReady: "Бесплатная интерпретация DeepSeek", aiFallback: "Интерпретация временно недоступна или достигнут лимит бесплатных запросов. Расчёт и сравнение остаются доступными.", aiSections: ["Что вас сближает", "Где можно не услышать друг друга", "Попробуйте вместе", "Спросите друг друга"],
  method: "Как устроено сравнение", methodBody: "Каждый раздел сочетает символику Ба-цзы (30%) и тропическую астрологию (70%). Характер — Солнце; общение — Меркурий; любовь — Венера и перекрёстные связи Луны с Венерой; ритм — Луна и Марс. В Ба-цзы сравниваются элементы дня, а для ритма — распределение пяти элементов четырёх столпов. Основные аспекты учитываются с орбисом 6°. Среднее четырёх разделов переводится в позитивную шкалу 60–100. Это авторские веса, а не проверенная статистика отношений. Учитываются исторические часовые пояса; для Ба-цзы применяется солнечная поправка. Асцендент, дома и даты брака не рассчитываются.", faqTitle: "Перед сравнением", faqs: [{ q: "Это бесплатно?", a: "Да. Баллы, сравнение и краткая интерпретация бесплатны. Для ИИ действуют ограничения частоты запросов. Регистрация и оплата не нужны." }, { q: "Низкий балл означает, что нужно расстаться?", a: "Нет. Индекс помогает выбрать символические темы для обсуждения. Уважение, общие ценности и реальные поступки важнее этого результата." }, { q: "Нужно знать время рождения обоих?", a: "Да, в этой версии нужны местное время рождения и город из списка. Мы не придумываем недостающие данные. Если города нет, напишите нам, чтобы добавить его." }], reset: "Сравнить другую пару", more: "Моя индивидуальная карта рождения", contact: "Запросить добавление города", preview: "ХАРАКТЕР · ОБЩЕНИЕ · ЛЮБОВЬ", spark: "Ваш подход", space: "Другой подход", together: "Найдите общий ритм", notDiagnosis: "Символические темы для размышления. Сверяйте их со своим опытом.",
};
const traditional = JSON.parse(toTraditional(JSON.stringify(zh))) as CompatibilityCopy;
export function compatibilityCopy(locale: ReportLocale): CompatibilityCopy { return ({ en, zh, "zh-TW": traditional, ru })[locale]; }
export function compatibilityHref(locale: ReportLocale) { return `/compatibility${locale === "en" ? "" : `?locale=${locale}`}`; }
export const compatibilityLocales = ["en", "zh", "zh-TW", "ru"] as const;
export function compatibilityAlternates() { return { en: compatibilityHref("en"), "zh-Hans": compatibilityHref("zh"), "zh-Hant": compatibilityHref("zh-TW"), ru: compatibilityHref("ru"), "x-default": compatibilityHref("en") }; }
export function signName(sign: string, signCn: string, locale: ReportLocale) {
  if (locale === "zh") return signCn;
  if (locale === "zh-TW") return toTraditional(signCn);
  if (locale === "ru") return ({ Aries: "Овен", Taurus: "Телец", Gemini: "Близнецы", Cancer: "Рак", Leo: "Лев", Virgo: "Дева", Libra: "Весы", Scorpio: "Скорпион", Sagittarius: "Стрелец", Capricorn: "Козерог", Aquarius: "Водолей", Pisces: "Рыбы" } as Record<string, string>)[sign];
  return sign;
}
