import type { ReactNode } from "react";
import { destinySupportHref } from "@/lib/support-contact";
import Image from "next/image";
import CardArtwork from "./card-artwork";
import SectionNavigation from "./section-navigation";
import { journeyCopy, sectionKeys, sectionHref } from "@/lib/section-journeys";
import { pillarName } from "@/lib/day-pillar-library";
import { getPillarImagePath } from "@/lib/archetype-assets";
import { journalLanguageTags } from "@/lib/journal-locales";
import { homeOfferCopy, type HomeReportOffer } from "@/lib/home-offer";
import type { ReportLocale } from "@/lib/report-i18n";
import styles from "./section-journeys.module.css";
export default function HomeGateway({locale,reportOffer,children}:{locale:ReportLocale;reportOffer:HomeReportOffer;children:ReactNode}){
 const c=journeyCopy(locale),offer=homeOfferCopy(locale);
 return <main className={styles.home} lang={journalLanguageTags[locale]} data-server-localized><header className={styles.header}><a className={styles.brand} href={sectionHref('/',locale)}><i/>DestinyPixel</a><nav aria-label="Language" className={styles.languages}>{(['en','zh','zh-TW','ru'] as const).map(l=><a key={l} href={sectionHref('/',l)} aria-current={l===locale?'page':undefined}>{({en:'EN',zh:'简体','zh-TW':'繁體',ru:'RU'})[l]}</a>)}</nav></header><SectionNavigation locale={locale}/><section className={styles.hero}><div><p className={styles.kicker}>{c.eyebrow}</p><h1>{c.title}</h1><p className={styles.lead}>{c.intro}</p><a className={styles.primary} href={sectionHref('/discover',locale)}>{c.sections.discover.action} <span aria-hidden>↗</span></a><a className={styles.textLink} href={sectionHref('/journal/day-pillars',locale)}>{locale==='en'?'Meet all 60 characters':locale==='ru'?'Познакомиться со всеми 60 образами':locale==='zh-TW'?'認識全部六十種意象':'认识全部六十种意象'} →</a></div><figure className={styles.heroCard}><CardArtwork src={getPillarImagePath('癸卯')} name={pillarName('癸卯',locale)} locale={locale} sizes="(max-width:650px) 80vw, 320px"/><figcaption>癸卯 · {pillarName('癸卯',locale)}</figcaption></figure></section><section className={styles.paths} aria-labelledby="four-paths"><h2 id="four-paths">{c.paths}</h2><div className={styles.pathGrid}>{sectionKeys.map((key,i)=>{const s=c.sections[key];return <a className={styles.pathCard} href={sectionHref('/'+key,locale)} key={key} data-home-path={key}><div className={styles.pathVisual} data-kind={key}>{key==='atelier'?<div className={styles.bracelet} aria-hidden>{Array.from({length:16},(_,j)=><i key={j} style={{transform:`rotate(${j*22.5}deg) translateY(-54px)`,background:j%3===0?'#b4a4cc':j%2===0?'#a3bdac':'#ece2cc'}}/>)}</div>:<Image src={key==='sticks'?'/shrine/oracle-vessel-20260917.webp':getPillarImagePath(key==='compatibility'?'乙卯':'丙午')} alt="" width={240} height={320} sizes="(max-width:650px) 38vw, 150px"/>}</div><div><p className={styles.kicker}>0{i+1} · {s.name}</p><h3>{s.title}</h3><p>{s.body}</p><small>{s.result}</small><strong>{s.action} ↗</strong></div></a>;})}</div></section><section className={styles.reportIntro}><div><p className={styles.kicker}>DestinyPixel</p><h2>{c.report}</h2><p>{c.reportNote}</p><p className={styles.offer}>{reportOffer.available&&reportOffer.amount?offer.note.replace('{price}',reportOffer.amount):offer.unavailable} <a href={sectionHref('/product-facts',locale)}>{offer.details} ↗</a></p></div><a className={styles.primary} href="#report">{c.report} ↓</a></section>{children}<footer className={styles.footerLinks}><a href={sectionHref('/tools',locale)}>{c.more}</a><a href={sectionHref('/journal',locale)}>{c.journal}</a><a href={sectionHref('/learn',locale)}>{c.learn}</a><a href={sectionHref('/product-facts',locale)}>{offer.details}</a><a href={destinySupportHref}>{({en:'Contact',zh:'联系','zh-TW':'聯絡',ru:'Связаться с нами'})[locale]}</a></footer></main>;
}
