import type { ReportLocale } from "@/lib/report-i18n";
import { toTraditional } from "@/lib/journal-locales";

const en = {
  title: "Free Day Pillar & Day Master Calculator | DestinyPixel",
  description: "Find your BaZi Day Pillar, Day Master element and day animal from your Gregorian birth date. Explore a free character card and reading. No account needed.",
  home: "DestinyPixel", journal: "Read the stories", eyebrow: "FREE BAZI DAY PILLAR CALCULATOR",
  heading: "Find your Day Pillar.\nMeet your character.",
  intro: "What is your Day Master element? Enter your birth date to see your BaZi Day Pillar and day animal, then explore its personality, relationship and work themes through a free character card.",
  features: ["Free to discover", "No account needed", "Ready in a moment"],
  preview: "A glimpse of the collection", previewBody: "From the gentle Dewy Rabbit to the bold Solar Stallion, every character holds a different kind of possibility.",
  nextTitle: "Meet your character. Then go deeper.",
  steps: [{title:"Find your card",body:"Enter your birthday to reveal one of 60 original characters."},{title:"Read your story",body:"Explore personality, relationship habits, work strengths and a direction for growth."},{title:"Make it yours",body:"Share the card, read the stories or continue to a personal birth map."}],
  faqTitle:"A few things to know",
  faqs:[{q:"Is this really free?",a:"Yes. Finding your birthday card is free and does not require an account or payment details."},{q:"Do I need my birth time?",a:"Only your Gregorian birth date is needed for this first card. A full birth map uses time and place too; a result near midnight can change after calibration."},{q:"What is behind the characters?",a:"The collection draws on a traditional 60-part calendar cycle and five-element symbolism. The character names and illustrations are DestinyPixel’s creative interpretations, rather than a scientific personality test."},{q:"Will my birthday appear when I share?",a:"No. The shared link contains the character type only. The free calculation stays in your browser and your birth date is not uploaded."}],
  finder:{pillarLabel:"Day Pillar",masterLabel:"Day Master",animalLabel:"Day animal",label:"Your birthday",button:"Reveal my free card",busy:"Finding your character…",privacy:"Your birthday stays in this browser.",prompt:"Your story starts here.",promptBody:"Enter your date to meet your character.",error:"Enter a valid birthday between 1800 and today.",unavailable:"The card could not load. Please try again.",result:"YOUR BIRTHDAY CHARACTER",growth:"Your growth edge",share:"Share my character",copied:"Link copied. Your birthday is not included.",manual:"Copy your character link below.",full:"Explore my full birth map",another:"Try another birthday",read:"Read the Oceanic Sequoia story",note:"Based on your calendar date. Birth time and place can refine a result near midnight."},
};
export type DiscoveryCopy = typeof en;
const zh: DiscoveryCopy = {
 title:"免费日柱查询与日主五行｜生日意象卡 | DestinyPixel",description:"输入公历生日，免费查询六十甲子日柱、日主五行和日支生肖，阅读性格、感情与事业意象卡。无需注册；午夜附近的生日需结合时间与地点核对。",home:"DestinyPixel",journal:"读读意象故事",eyebrow:"免费日柱查询 · 日主五行 · 六十甲子",heading:"查查你的日柱，\n认识你的生日意象。",intro:"只需公历生日，查看日柱、日主五行与日支生肖，再从对应的动物卡里，读读性格底色、感情习惯和事业发力点。",features:["免费查看","无需注册","即刻出结果"],preview:"先认识几位意象伙伴",previewBody:"雨露灵兔的细腻，烈日天马的热情，流金蛇影的锋芒……每一种意象，都有值得了解的另一面。",nextTitle:"先找到你的卡，再读更完整的你。",steps:[{title:"找到你的意象",body:"输入公历生日，揭晓六十种原创意象中的一张。"},{title:"读懂它的故事",body:"看看性格里的反差、亲密关系中的习惯与事业发力点。"},{title:"继续你的探索",body:"分享给朋友、读相关故事，或继续探索完整出生图谱。"}],faqTitle:"你可能想知道",faqs:[{q:"真的免费吗？",a:"是的。生日意象卡免费查看，不需要注册账号，也不需要填写支付信息。"},{q:"不知道出生时间，也能测吗？",a:"可以，第一张卡只需要公历生日。完整出生图谱还需要时间与地点；午夜附近的结果，经过校准可能变化。"},{q:"这些意象从哪里来？",a:"这套卡片以六十干支与五行象征为灵感，名字和画面是 DestinyPixel 的原创表达。它提供命理文化体验，不是科学人格测验。"},{q:"分享会暴露生日吗？",a:"不会。分享链接只有卡片类型，没有生日。免费测算在浏览器内完成，出生日期不会上传。"}],finder:{pillarLabel:"日柱",masterLabel:"日主五行",animalLabel:"日支生肖",label:"你的公历生日",button:"免费揭晓我的意象",busy:"正在寻找你的意象…",privacy:"生日只在当前浏览器中使用。",prompt:"你的故事，从这里开始。",promptBody:"输入生日，认识属于你的意象。",error:"请输入1800年至今天之间的有效公历生日。",unavailable:"卡片暂时未能加载，请重试。",result:"你的生日意象",growth:"你的成长方向",share:"分享我的意象卡",copied:"链接已复制，不包含你的生日。",manual:"复制下方链接，分享你的意象。",full:"继续探索完整出生图谱",another:"再测一个生日",read:"阅读海中神木的完整故事",note:"结果按公历日期初算；午夜附近的出生时间与地点校准，可能改变对应意象。"},
};
const ru: DiscoveryCopy = {
 title:"Столп дня Бацзы и элемент личности — бесплатно | DestinyPixel",description:"Узнайте столп дня Бацзы, элемент личности и животное дня по дате рождения. Бесплатный расчёт и карточка с темами характера и отношений. Без регистрации.",home:"DestinyPixel",journal:"Читать истории",eyebrow:"БЕСПЛАТНЫЙ РАСЧЁТ СТОЛПА ДНЯ БАЦЗЫ",heading:"Узнайте свой столп дня\nи элемент личности.",intro:"Какой у вас элемент личности в Бацзы? Введите дату рождения, чтобы увидеть столп дня и его животное, а затем изучить характер, отношения и работу через бесплатную карточку образа.",features:["Бесплатно","Без регистрации","Мгновенный результат"],preview:"Знакомство с коллекцией",previewBody:"Нежный Кролик росы, смелый Солнечный скакун — за каждым образом своя история возможностей.",nextTitle:"Познакомьтесь с образом. Узнайте больше.",steps:[{title:"Найдите карточку",body:"Введите день рождения, чтобы открыть один из 60 авторских образов."},{title:"Прочтите историю",body:"Изучите характер, привычки в отношениях и направления развития способностей."},{title:"Продолжите путь",body:"Поделитесь карточкой, почитайте истории или откройте полную карту рождения."}],faqTitle:"Полезно знать",faqs:[{q:"Это действительно бесплатно?",a:"Да. Карточка по дню рождения бесплатна, регистрация и платёжные данные не нужны."},{q:"Нужно ли время рождения?",a:"Для первой карточки достаточно даты по григорианскому календарю. Полная карта учитывает время и место; рядом с полуночью результат после уточнения может измениться."},{q:"На чём основаны образы?",a:"В основе — традиционный цикл из 60 сочетаний и символика пяти элементов. Названия и иллюстрации — авторская интерпретация DestinyPixel, а не научный тест личности."},{q:"Будет ли видна моя дата в общей ссылке?",a:"Нет. Ссылка содержит только тип карточки. Бесплатный расчёт выполняется в браузере, дата рождения не загружается на сервер."}],finder:{pillarLabel:"Столп дня",masterLabel:"Элемент личности",animalLabel:"Животное дня",label:"Дата рождения",button:"Открыть мою карточку",busy:"Ищем ваш образ…",privacy:"Дата остаётся в этом браузере.",prompt:"Здесь начинается ваша история.",promptBody:"Введите дату и познакомьтесь со своим образом.",error:"Введите корректную дату рождения между 1800 годом и сегодняшним днём.",unavailable:"Не удалось загрузить карточку. Попробуйте снова.",result:"ВАШ ОБРАЗ ПО ДНЮ РОЖДЕНИЯ",growth:"Направление роста",share:"Поделиться образом",copied:"Ссылка скопирована. Дата рождения в неё не включена.",manual:"Скопируйте ссылку на свой образ ниже.",full:"Изучить полную карту рождения",another:"Другая дата рождения",read:"История Секвойи в океане",note:"Первый результат основан на календарной дате. Уточнение времени и места может изменить его рядом с полуночью."},
};
function traditional<T>(value:T):T { if(typeof value==="string")return toTraditional(value) as T;if(Array.isArray(value))return value.map(traditional) as T;if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,traditional(v)])) as T;return value; }
export function getDiscoveryCopy(locale: ReportLocale): DiscoveryCopy { return locale==="zh-TW"?traditional(zh):locale==="zh"?zh:locale==="ru"?ru:en; }
export const discoveryLocales = ["en","zh","zh-TW","ru"] as const;
export function discoveryHref(locale:ReportLocale) { return locale==="en"?"/discover":`/discover?locale=${locale}`; }
export function discoveryAlternates() { return { en:"/discover","zh-Hans":"/discover?locale=zh","zh-Hant":"/discover?locale=zh-TW",ru:"/discover?locale=ru","x-default":"/discover"}; }
