import type { JournalSourceArticle, JournalTranslation } from "./journal";

const editions: Record<"en" | "zh" | "ru", JournalTranslation> = {
  en: {
    title: "Yuelao love fortune sticks: what to say after your reading",
    description: "Drew a love fortune stick and still don’t know what to say? Try concrete conversation starters for waiting, mixed signals and reconnecting, with a simple next step.",
    topic: "Love, after the reading",
    introduction: "You draw a love fortune stick, read a line about patience, and immediately think of the message they still haven’t answered. Does patience mean waiting another day, sending another text, or finally asking where you stand? The interesting part begins after the draw: turning the feeling it brings up into something you can say. Here are three everyday situations and a small writing exercise to help you leave the reading with a conversation, rather than another hour of checking your phone.",
    takeaway: "Keep the image that speaks to you, then name one thing you noticed, one thing you need and one question the other person can answer for themselves.",
    sections: [
      { id: "keep-one-line", title: "First, choose the line you keep coming back to", paragraphs: ["Read the whole result once, then choose one phrase that stays with you. Beside it, write the specific moment it brought to mind: a cancelled plan, a warm evening followed by silence, or an argument you both avoided finishing. Separate that moment from your interpretation of it. ‘We cancelled twice’ describes something you can discuss; ‘you never cared’ claims to know why it happened. You do not have to suppress the feeling. Giving it a concrete starting point simply leaves more room for a real answer."] },
      { id: "waiting", title: "If the reading makes you think about waiting", paragraphs: ["Imagine that the idea of waiting catches your attention. This is our example, not a quotation from a numbered temple verse. Waiting can be a choice with a clear next step instead of an indefinite test of devotion. You might say: ‘I enjoyed seeing you. Would you like to make another plan this week?’ In an established relationship, try: ‘I’m happy to give this conversation some space. Could we choose a time to come back to it?’ The useful information is whether you can agree on something and whether it happens. A symbol cannot set that agreement for both people."] },
      { id: "mixed-signals", title: "If affection and uncertainty arrive together", paragraphs: ["Someone can be warm in person while leaving you unsure about what they want. Rather than asking the reading to decode the contradiction, use it to identify the question you have been avoiding. For example: ‘I like spending time with you, and I’m looking for a relationship. What are you looking for right now?’ Ask when there is room to listen, not in the middle of a rapid exchange of messages. Their answer may differ from what you hoped. You can then decide whether the relationship they are offering fits you, without needing to win an argument about what the signs meant."] },
      { id: "reconnecting", title: "If you are hoping to reconnect after an argument", paragraphs: ["A hopeful reading can make a dramatic declaration tempting. Start smaller and take responsibility for your own part: ‘I interrupted you yesterday. I want to understand what I missed. Would you be open to talking?’ That invitation does not erase the disagreement, and the other person can decline. If you do talk, choose one incident rather than reopening every past argument. Ask whether they want you to listen first or work on a solution together. If they have clearly asked for no contact, respect that boundary; an encouraging result is not permission to keep reaching out."] },
      { id: "three-lines", title: "Write these three lines before you send a message", paragraphs: ["Keep the note short enough to reread without building a case against anyone. The following is an invented example of a postponed conversation; it is not a user’s report or a promise that the wording will repair a relationship."], steps: ["What I noticed: ‘We said we would discuss our plans, but we haven’t chosen a time.’", "What matters to me: ‘I want to know whether we are planning the same kind of future.’", "What I can ask: ‘Would Sunday afternoon work for a conversation about that?’"] },
      { id: "read-the-source", title: "Where Yuelao, the source note and AI fit", paragraphs: ["On DestinyPixel, the Yuelao collection is the love-focused option in the Chinese fortune-stick experience, with numbers 1–60. Those are this site’s supported numbers, not a claim about every temple’s collection. Choose Yuelao before drawing or looking up a number, and read the source note with the result. Some material is traditional; other text is our modern symbolic reading. Optional AI interpretation adds context to your question. The conversation examples in this article are original editorial exercises, not temple instructions or messages from your partner. You do not need a birthday or a BaZi chart to use the stick experience."], sources: [{ label: "DestinyPixel: Yuelao collection and source notes", href: "/sticks?type=yuelao" }, { label: "Before the draw: asking a useful question", href: "/journal/how-to-ask-fortune-sticks" }] },
      { id: "after-conversation", title: "After the conversation, look at what actually changed", paragraphs: ["Return to the note after the conversation or at the time you agreed to check in. Did you learn what the other person wants? Did either of you make a specific commitment? Does the arrangement feel workable to you? A clear answer can be useful even when it is disappointing. If nothing has changed, another draw does not create new information about the relationship. You can keep the ritual as a quiet moment for yourself while allowing the other person’s words and actions to shape your next decision. The aim is a little more clarity, not a perfect sentence that controls the outcome."] },
    ],
    action: { label: "Explore the Yuelao love oracle", href: "/sticks?type=yuelao" },
  },
  zh: {
    title: "抽到感情签后怎么开口？把月老签读成一次具体对话",
    description: "抽完月老签，仍不知道该等、该问还是该联系？用等待、暧昧和争执后的三个情境，整理能直接开口的表达与下一步。",
    topic: "读完签，再靠近一点",
    introduction: "抽到一支感情签，读到“耐心”的意思，你立刻想起那条迟迟没收到回复的消息。耐心到底是再等一天、再发一句，还是终于问清楚关系？真正需要做的事，常常发生在抽签之后：把被触动的感受，变成一句能说出口的话。下面用三个日常情境和一个小练习，帮你从签意走到对话，而不是继续反复打开聊天窗口。",
    takeaway: "留下最触动你的意象，再写清楚一件看见的事、一个自己的需要，以及一个让对方亲自回答的问题。",
    sections: [
      { id: "keep-one-line", title: "先选一句让你反复想到的话", paragraphs: ["完整读一遍结果，再选一句留在心里的话。旁边写下它让你想起的具体时刻：取消的约会、见面很亲近却突然没了消息，或两个人都没继续谈的争执。把事情和对事情的解释分开。“我们取消了两次约会”是能一起讨论的事实，“你根本不在乎我”则已经替对方解释了原因。你不需要压下委屈，只是先给委屈找一个具体起点，给真实回答留一点位置。"] },
      { id: "waiting", title: "如果签意让你想到“等待”", paragraphs: ["假设你读后最在意的是等待。这是本文的情境示例，不是某一编号的传统签诗。等待可以有明确的下一步，不必变成没有期限的感情考验。刚认识时可以说：“上次见面很开心，你这周想再约一次吗？”已经在一起，则可以说：“我愿意给这个话题一点空间，我们能约个时间回来继续聊吗？”真正能让你了解关系的，是双方能否约定一件事，以及之后是否发生；签里的意象不能替两个人作出约定。"] },
      { id: "mixed-signals", title: "如果亲近和不确定一起出现", paragraphs: ["有的人见面时很热情，却始终没说自己想要什么。与其让签文替你解释这个反差，不如借它找到你一直绕开的那个问题。例如：“我喜欢和你相处，也希望发展一段关系。你现在想要的是怎样的相处？”选一个能听完回答的时机，不要夹在一连串急促的信息里。答案可能不是你希望的，但你终于可以判断对方愿意提供的关系是否适合自己，不必争论那些暗示到底是什么意思。"] },
      { id: "reconnecting", title: "如果你想在争执后重新靠近", paragraphs: ["读到让人抱有希望的内容，很容易想立刻说一大段深情的话。可以从小一点、自己能负责的部分开始：“昨天我打断了你，我想听听当时漏掉了什么。你愿意聊聊吗？”邀请不代表争执已经解决，对方也可以拒绝。若开始聊，先说清一件事，不要一次翻出所有旧账。问问对方希望你先听完，还是一起想办法。若对方已经明确要求不再联系，就尊重这个边界；令人振奋的结果也不是继续打扰的许可。"] },
      { id: "three-lines", title: "发送消息前，先写三句话", paragraphs: ["把笔记写得短一点，能一眼看完就好，不必写成证明对方有错的长信。下面是一个虚构的“约好却没谈成”的示例，不是用户报告，也不承诺这样说就能修复感情。"], steps: ["我看见的事：“我们说好要聊聊以后的安排，但还没定时间。”", "我在意的事：“我想知道，我们期待的是不是同一种未来。”", "我能提出的问题：“周日下午能留一点时间聊这件事吗？”"] },
      { id: "read-the-source", title: "月老签、来源说明和AI分别放在哪里看", paragraphs: ["在DestinyPixel的中国灵签体验里，月老签是偏向感情主题的选择，本站支持1—60号；这个范围不代表所有庙宇都使用同一套签。抽签或查号前先选月老，再把结果旁的来源说明一起读。有些材料来自传统文本，另一些是本站的现代象征解读；可选的AI解释会结合你提出的问题。本文的对话示例是原创练习，不是庙本指示，也不是对方传来的心声。使用抽签不需要生日或八字资料。"], sources: [{ label: "DestinyPixel：月老签与来源说明", href: "/sticks?type=yuelao&locale=zh" }, { label: "抽签之前：怎样提出有用的问题", href: "/journal/how-to-ask-fortune-sticks?locale=zh" }] },
      { id: "after-conversation", title: "聊过之后，看现实里发生了什么", paragraphs: ["聊完，或到了约定再联系的时间，回来看那张笔记：你是否知道了对方的想法？有没有人承诺一件具体的事？这个安排对你是否合适？明确的回答即使让人失望，也能带来有用的信息。如果现实没有变化，再抽一支签不会让你自动知道更多对方的情况。你仍可以把仪式留作自己的安静时刻，同时让对方真实的表达和行动影响下一步。目标是更清楚一点，而不是找到一句能控制结局的完美话术。"] },
    ],
    action: { label: "走进月老签堂", href: "/sticks?type=yuelao&locale=zh" },
  },
  ru: {
    title: "Любовный оракул Юэлао: о чём поговорить после гадания",
    description: "Что делать после любовного гадания на палочках? Примеры разговора об ожидании, неопределённости и примирении, которые помогут выбрать конкретный следующий шаг.",
    topic: "Любовь после гадания",
    introduction: "Вы вытянули любовную палочку, прочли о терпении и сразу вспомнили сообщение, на которое ещё не ответили. Что значит ждать: дать ещё день, написать снова или наконец спросить, какие у вас отношения? Самое интересное начинается после гадания: чувство, которое вызвал образ, можно превратить в разговор. Вот три повседневные ситуации и небольшое письменное упражнение, чтобы после чтения у вас появился следующий шаг, а не ещё один час проверки телефона.",
    takeaway: "Сохраните образ, который вас тронул, затем назовите один наблюдаемый факт, одну свою потребность и один вопрос, на который другой человек сможет ответить сам.",
    sections: [
      { id: "keep-one-line", title: "Начните со строки, к которой мысленно возвращаетесь", paragraphs: ["Прочитайте результат целиком и выберите одну запомнившуюся фразу. Рядом запишите конкретный момент, который она напомнила: отменённую встречу, тёплый вечер и последующее молчание или спор, к которому вы так и не вернулись. Отделите событие от своего объяснения. «Мы дважды отменили встречу» — факт для обсуждения. «Тебе никогда не было дела до меня» — уже утверждение о чужих мотивах. Чувство не нужно подавлять. Конкретная отправная точка лишь оставляет больше места для настоящего ответа."] },
      { id: "waiting", title: "Если в чтении вас зацепила тема ожидания", paragraphs: ["Представьте, что вы задумались об ожидании. Это наш пример, а не цитата из храмового текста под определённым номером. У ожидания может быть понятный следующий шаг: оно не обязано становиться бессрочной проверкой преданности. После знакомства можно сказать: «Мне понравилась наша встреча. Хочешь увидеться ещё раз на этой неделе?» В сложившихся отношениях: «Я готов дать этому разговору немного времени. Давай выберем, когда к нему вернёмся?» Важно, удаётся ли договориться и происходит ли обещанное. Символ не заключает соглашение за двоих."] },
      { id: "mixed-signals", title: "Если близость соседствует с неопределённостью", paragraphs: ["Человек может быть тёплым при встрече и всё же не говорить, чего хочет. Вместо расшифровки этого противоречия через оракул найдите вопрос, которого избегали. Например: «Мне нравится проводить с тобой время, и я хочу отношений. А чего сейчас хочешь ты?» Выберите момент, когда сможете выслушать ответ, а не вставляйте вопрос в поток торопливых сообщений. Ответ может разойтись с вашими надеждами. Зато вы сможете оценить, подходят ли вам предлагаемые отношения, без спора о том, что означали намёки."] },
      { id: "reconnecting", title: "Если хочется сблизиться после ссоры", paragraphs: ["Обнадёживающий результат иногда хочется превратить в большое признание. Начните с меньшего и возьмите ответственность за свою часть: «Вчера я тебя перебил. Мне хочется понять, что я упустил. Ты готов поговорить?» Приглашение не отменяет разногласия; другой человек вправе отказаться. Если разговор состоится, обсудите один эпизод, не поднимая сразу все прежние ссоры. Спросите, нужно ли сначала выслушать или вместе искать решение. Если вас ясно попросили больше не связываться, уважайте границу: даже вдохновляющее чтение не даёт разрешения продолжать писать."] },
      { id: "three-lines", title: "Перед сообщением запишите три короткие строки", paragraphs: ["Пусть заметку можно будет перечитать с одного взгляда: это не обвинительное письмо. Ниже — вымышленный пример отложенного разговора, а не чья-то личная история и не обещание восстановить отношения с помощью правильной формулировки."], steps: ["Наблюдение: «Мы собирались обсудить наши планы, но пока не выбрали время».", "Что для меня важно: «Я хочу понять, одинаково ли мы представляем наше будущее».", "Мой вопрос: «Подойдёт воскресенье после обеда, чтобы об этом поговорить?»"] },
      { id: "read-the-source", title: "Как связаны Юэлао, примечание об источнике и ИИ", paragraphs: ["В китайском оракуле палочек DestinyPixel коллекция Юэлао посвящена отношениям и поддерживает номера 1–60. Это диапазон нашего сайта, а не утверждение о всех храмовых коллекциях. Перед вытягиванием или поиском номера выберите Юэлао и прочитайте примечание об источнике рядом с результатом. Часть материала традиционная, часть — наше современное символическое прочтение. Дополнительная интерпретация ИИ учитывает ваш вопрос. Примеры разговоров в этой статье — авторские упражнения, а не храмовые предписания или сообщения от партнёра. Для палочек не нужны дата рождения или карта бацзы."], sources: [{ label: "DestinyPixel: Юэлао и примечания об источниках", href: "/sticks?type=yuelao&locale=ru" }, { label: "До гадания: как сформулировать вопрос", href: "/journal/how-to-ask-fortune-sticks?locale=ru" }] },
      { id: "after-conversation", title: "После разговора посмотрите, что изменилось", paragraphs: ["Вернитесь к заметке после разговора или в согласованное время. Узнали ли вы, чего хочет другой человек? Договорились ли о конкретном действии? Подходит ли вам этот вариант? Ясный ответ полезен, даже если огорчает. Если в ситуации ничего не изменилось, новая палочка не создаст новых сведений об отношениях. Ритуал может оставаться вашим спокойным личным моментом, а следующий выбор — опираться на реальные слова и поступки. Цель в том, чтобы стало немного понятнее, а не в поиске идеальной фразы, управляющей исходом."] },
    ],
    action: { label: "Открыть любовный оракул Юэлао", href: "/sticks?type=yuelao&locale=ru" },
  },
};

export const loveFortuneArticle: JournalSourceArticle = {
  slug: "yuelao-love-fortune-conversation",
  relatedSlug: "how-to-ask-fortune-sticks",
  publishedAt: "2026-09-22",
  updatedAt: "2026-09-22",
  translations: { en: editions.en, zh: editions.zh },
};
export const loveFortuneRussian = editions.ru;
