import OpenCC from "opencc-js/cn2t";

export const journalLocales = ["en", "zh", "zh-TW", "ru"] as const;
export type JournalLocale = typeof journalLocales[number];
export const journalLanguageTags = { en: "en", zh: "zh-Hans", "zh-TW": "zh-Hant", ru: "ru" } as const;
export const journalLanguageLabels = { en: "EN", zh: "简体", "zh-TW": "繁體", ru: "Русский" } as const;
export const journalOgLocales = { en: "en_US", zh: "zh_CN", "zh-TW": "zh_TW", ru: "ru_RU" } as const;
// Convert characters first. The broad regional phrase dictionary can corrupt
// ordinary prose (for example, 真实例子 becomes 真例項子).
const traditionalCharacters = OpenCC.Converter({ from: "cn", to: "tw" });
export function toTraditional(value: string) {
  return traditionalCharacters(value).replaceAll("反饋", "回饋").replaceAll("香港天文臺", "香港天文台");
}
const en = {"home":"Home","tools":"Tools","journal":"Journal","mainNav":"Main navigation","language":"Article language","footer":"Clear distinctions between symbols, calculations and personal judgment.","footerNav":"Footer navigation","all":"All articles","toolDirectory":"Tool directory","contact":"Contact","breadcrumb":"Breadcrumb","published":"Published","updated":"Updated","contents":"IN THIS GUIDE","sections":"Article sections","takeaway":"START HERE","sources":"SOURCES & FURTHER READING","try":"Try it with a clear idea of what to expect.","related":"CONTINUE READING","eyebrow":"THE DESTINYPIXEL JOURNAL","heading":"Meet the character.\nExplore the story.","intro":"What draws you to someone? Where does your talent meet its opportunity? Explore personality, love and career through the Day Pillars, through all 60 illustrated portraits, alongside birth-chart guides and five-element design. Read in English, Chinese or Russian.","list":"Original articles","read":"Read the guide","editorial":"HOW THESE GUIDES ARE MADE","editorialBody":"Day Pillar portraits draw on traditional symbolism and our original card material, with real situations in love and work. Famous birthdays are checked against published sources and our date calculator. Calendar facts and practical instructions are kept distinct from interpretation.","title":"Journal: Birthday Characters, Love & Life Direction","description":"Explore Bazi Day Pillar personality, love and career stories, with all 60 illustrated animal portraits, plus verified famous birthdays, birth-chart guides and five-element design."};
const zh = {"home":"首页","tools":"玄学工具","journal":"文章","mainNav":"主导航","language":"文章语言","footer":"把象征、计算与个人判断分清楚。","footerNav":"页脚导航","all":"全部文章","toolDirectory":"工具目录","contact":"联系反馈","breadcrumb":"面包屑导航","published":"发布于","updated":"更新于","contents":"文章目录","sections":"文章章节","takeaway":"先记住这一点","sources":"来源与延伸阅读","try":"带着清楚的预期，动手试一次。","related":"继续阅读","eyebrow":"DESTINYPIXEL 原创文章","heading":"你的性格，有故事。\n你的日柱，有看点。","intro":"你为什么会被一个人吸引？什么样的工作能发挥你的长处？从甲子到癸亥，读日柱里的性格、感情、事业与名人故事，也探索出生图谱和五行配色。提供英语、简体中文、繁体中文与俄语版本。","list":"原创文章列表","read":"阅读文章","editorial":"我们怎样写这些文章","editorialBody":"日柱人物画像结合传统象征与原创卡片资料，写出感情和事业中的具体情境。名人生日核对公开来源，并按日期复算；历法与操作步骤另行核实，让读者知道故事从哪里来。","title":"玄学与日常：六十日柱、出生图谱与五行指南","description":"从甲子到癸亥，阅读六十甲子日柱的性格、感情与事业故事，了解核对过生日的名人案例，探索出生图谱与五行设计。"};
const ru: typeof en = {"home":"Главная","tools":"Инструменты (EN)","journal":"Статьи","mainNav":"Основная навигация","language":"Язык статьи","footer":"Символы, расчёты и личные выводы — у каждого своя роль.","footerNav":"Навигация внизу страницы","all":"Все статьи","toolDirectory":"Каталог инструментов (EN)","contact":"Связаться с нами","breadcrumb":"Путь к странице","published":"Опубликовано","updated":"Обновлено","contents":"В ЭТОЙ СТАТЬЕ","sections":"Разделы статьи","takeaway":"С ЧЕГО НАЧАТЬ","sources":"ИСТОЧНИКИ И МАТЕРИАЛЫ","try":"Попробуйте инструмент, зная, чего от него ожидать.","related":"ЧИТАЙТЕ ДАЛЬШЕ","eyebrow":"ЖУРНАЛ DESTINYPIXEL","heading":"За характером — история.\nОткройте свою.","intro":"Что вас привлекает в человеке? Где вашим способностям находится применение? Изучайте характер, любовь и карьеру через столпы дня, начиная с Цзя-цзы, а также карту рождения и дизайн пяти элементов. На русском, английском и китайском.","list":"Авторские статьи","read":"Читать статью","editorial":"КАК МЫ ГОТОВИМ СТАТЬИ","editorialBody":"Портреты столпов дня соединяют традиционную символику с авторскими образами и конкретными ситуациями в любви и работе. Даты рождения известных людей сверяются с опубликованными источниками и календарным расчётом. Факты о календаре и инструкции отделены от толкований.","title":"Ба-цзы: столпы дня, карта рождения и пять элементов","description":"Характер, любовь и карьера в историях столпов дня Ба-цзы, начиная с Цзя-цзы. Проверенные даты известных людей, карта рождения и дизайн пяти элементов."};
const traditional = Object.fromEntries(Object.entries(zh).map(([key, value]) => [key, toTraditional(value)])) as typeof zh;
traditional.tools = "玄學工具（簡體）";
traditional.toolDirectory = "工具目錄（簡體）";
traditional.published = "發表於";
traditional.contact = "聯絡我們";
traditional.breadcrumb = "麵包屑導覽";
export const journalUi = { en, zh, "zh-TW": traditional, ru };
export function journalHomeHref(locale: JournalLocale) { return locale === "en" ? "/" : `/?locale=${locale}`; }
// The tool directory currently has English and Simplified Chinese editions only.
export function journalToolsHref(locale: JournalLocale) { return locale === "zh" || locale === "zh-TW" ? "/tools?locale=zh" : "/tools"; }
