import type { JournalSourceArticle, JournalTranslation } from "./journal";

type Edition = {
  title: string; description: string; topic: string; introduction: string; takeaway: string;
  sections: [string, string][]; action: { label: string; href: string };
};
type Entry = { slug: string; relatedSlug: string; publishedAt?: string; updatedAt?: string; sources: { label: string; href: string }[]; en: Edition; zh: Edition; ru: Edition };

// Original, task-focused guides. Section order is shared across complete editions.
const entries: Entry[] = [
  {
    slug: "bazi-vs-chinese-zodiac-compatibility", relatedSlug: "compatibility-without-birth-time",
    sources: [{ label: "Hong Kong Observatory · 干支与八字 · Небесные стволы и земные ветви", href: "https://www.hko.gov.hk/en/gts/time/stemsandbranches.htm" }, { label: "DestinyPixel · Compatibility method / 配对方法 / Метод сравнения", href: "/compatibility" }],
    en: {
      title: "BaZi vs Chinese zodiac compatibility: beyond your birth-year animal",
      description: "Same zodiac animal, different relationship styles? Compare year-sign matching with Four Pillars, five elements and DestinyPixel’s free compatibility tool.",
      topic: "Love & the five elements",
      introduction: "You look up two Chinese zodiac animals and find a perfect match. Yet one of you wants to settle every disagreement immediately, while the other needs a quiet evening first. Did you read the wrong table? A year-animal pairing describes a very small part of the system. This guide separates the calendar, the symbolic interpretation and the conversation you can actually have together, without asking a score to decide your relationship.",
      takeaway: "A year animal is one calendar label. BaZi uses year, month, day and hour. More detail makes a comparison more specific, but does not make it a proven measure of love.",
      sections: [
        ["What does a Chinese zodiac compatibility table compare?", "A familiar zodiac chart starts with the animal associated with a birth year and compares it with another animal. It is easy to remember and easy to share, which makes it a useful cultural introduction. But two people assigned the same animal can have different birth months, days and hours. A year-based table cannot distinguish those inputs. Near a calendar boundary, also check which convention the calculator follows rather than choosing a year from a generic poster. DestinyPixel’s full birth calculation uses the start of spring, LiChun, for its year boundary; that should not be silently confused with Lunar New Year."],
        ["What does BaZi add?", "BaZi means eight characters: a stem and a branch for each of four calendar pillars. The Hong Kong Observatory describes how these pairs are used for years, months, days and hours, and how they form a sixty-pair cycle. That is evidence for the calendar structure, not for predictions about a couple. In a reading, the day stem becomes a reference point for discussing the five elements. Looking at both complete sets can reveal different symbolic patterns despite identical year animals. It still cannot tell you whether someone keeps promises, listens during conflict or shares your plans for the future."],
        ["How to read supporting and controlling elements", "Wood, fire, earth, metal and water form a traditional vocabulary of relationships. A supporting relationship can become a prompt about giving and receiving; a controlling relationship can become a prompt about boundaries or friction. Avoid translating these straight into good partner and bad partner. For example, one person may experience frequent advice as care while the other hears constant correction. The useful next question is what each person actually needs: encouragement, practical help or room to decide. This is a way to explore a metaphor together, not a claim that an element caused either person’s behavior or that conflict is inevitable."],
        ["Where do the sixty animal cards fit?", "DestinyPixel’s sixty animal portraits give the calendar combinations memorable visual identities. The names, artwork and character stories are an original presentation, not sixty ancient personality diagnoses. Read your own card first and choose one description that fits a real incident, then one that does not. Invite your partner to do the same instead of announcing what their card means about them. Two people can identify with similar images while expressing affection very differently. The cards work best as an opening to that discussion; they are not additional evidence that a relationship is destined, and their illustrations do not add hidden points to the score."],
        ["What the free comparison actually calculates", "The current tool combines a BaZi element comparison with selected planetary comparisons. Its overall index uses thirty percent BaZi and seventy percent planetary comparisons, then presents the result on an editorial scale from sixty to one hundred. That number is not a measured probability of staying together. The page also compares personality, communication, affection and everyday rhythm, and shows the two animal portraits. AI can explain the supplied result but does not choose the score. This is not a complete traditional marriage assessment or a full Western synastry reading: it does not calculate houses, rising signs or a marriage date."],
        ["Turn the reading into one useful conversation", "Both people should check their recorded date, time and selected birthplace before comparing. Then pick one small, observable question rather than trying to settle your entire future: after a difficult workday, do you want questions, company or quiet first? Each person answers before looking back at the reading. Agree on one action to try, such as saying when you will return to a paused conversation. A week later, discuss whether that helped. If the result does not fit, say so and keep the real experience. The value of this exercise is a clearer conversation, not persuading either person to accept a label."],
      ], action: { label: "Compare your two birth charts free", href: "/compatibility" },
    },
    zh: {
      title: "生肖配对和八字合婚有什么区别？从属相看到五行与相处方式",
      description: "同样的生肖，为什么相处模式不同？讲清生肖配对、四柱八字、五行关系与60动物卡的区别，并了解免费情感匹配的实际计算范围。",
      topic: "感情与五行", introduction: "查生肖时明明写着“很般配”，真正相处却是一个人想立刻讲清楚，另一个人想先安静一晚。是配对表错了，还是你们不够了解彼此？年生肖只提供很小的一部分信息。这篇指南把历法、象征解读和两个人真正能讨论的事情分开，让配对结果成为交流的起点。",
      takeaway: "生肖配对通常只看出生年的动物；八字使用年、月、日、时四柱。信息更具体，不等于已经科学验证了感情好坏。",
      sections: [
        ["生肖配对表到底在比较什么？", "常见配对表从出生年的动物出发，与另一个动物作比较。它好记、好分享，适合作为文化入口，却区分不了同属一个生肖、但出生月份、日期和时辰不同的人。处在换年边界附近时，还要先确认采用什么历法规则，不能只照一张年份海报选属相。本站完整出生计算以立春作为年柱边界，不应与农历正月初一混用。"],
        ["八字比生肖多看了什么？", "四柱中的每一柱都有一个天干和一个地支，年、月、日、时合起来就是八个字。香港天文台介绍了这些干支如何用于纪年、纪月、纪日和纪时，以及六十组合的循环；这支持历法结构的说明，不是对感情预测的验证。解读时，日干可以作为理解五行关系的参照。同生肖的人可能有不同的组合，但这些组合不能替你确认一个人是否守信、是否愿意倾听、是否与你有一致的生活计划。"],
        ["五行相生相克，怎样读成相处问题？", "木、火、土、金、水之间的关系，是传统象征语言。“相生”可以引出给予与接受的话题，“相克”可以引出边界与摩擦，但不能直接翻译成好伴侣与坏伴侣。比如，一个人不断提建议，自己觉得是在关心，对方却觉得总被纠正。这时真正有用的问题是：你此刻需要鼓励、实际帮助，还是自己决定的空间？这是借助比喻讨论具体体验，并不是说某种元素造成了这些行为。"],
        ["60动物卡在这里起什么作用？", "本站把六十种历法组合设计成具有记忆点的动物意象。名字、画面和角色故事属于原创呈现，不是六十种古代人格诊断。可以先各自选出卡片里一条符合真实经历的描述，再选一条不符合的，让对方自己表达，不要替对方宣布“你就是这样的人”。卡片帮助打开话题，不能证明命定关系，图画也不会在分数里额外加上看不见的权重。"],
        ["免费匹配现在怎么算？", "当前工具把八字元素比较与部分行星关系结合，总体指标中八字占30%，行星比较占70%，再呈现为60—100的编辑尺度。它不是维持关系的成功概率。结果还提供性格、沟通、感情表达与日常节奏的比较，以及双方动物意象。AI解释已经算出的结果，不决定分数。它不等于完整传统合婚或完整西方合盘，也不计算宫位、上升星座和婚期。"],
        ["把结果变成一次有用的对话", "先由双方核对出生日期、记录时间与出生城市，再选一个可以观察的小问题：工作不顺回家时，你更希望有人问、有人陪，还是先安静？各自先回答，再回看结果。约定一件可以试行的事，例如暂停争论时明确什么时候回来继续说。一周后讨论有没有帮助。描述不符合就保留不同意见；重点是让沟通更清楚，而不是让任何一方服从标签。"],
      ], action: { label: "免费比较两个人的出生图谱", href: "/compatibility?locale=zh" },
    },
    ru: {
      title: "Совместимость по бацзы и китайскому зодиаку: что меняется кроме животного года",
      description: "Почему одинаковые знаки не означают одинаковые отношения: четыре столпа, пять элементов, 60 животных и границы бесплатного сравнения DestinyPixel.",
      topic: "Отношения и пять элементов", introduction: "Таблица обещает прекрасное сочетание знаков, но после ссоры одному хочется немедленно поговорить, а другому нужен тихий вечер. Ошибка ли это? Животное года описывает лишь небольшую часть символической системы. Разберём отдельно календарь, интерпретацию и разговор, который действительно можно провести вдвоём, не поручая оценке решать судьбу отношений.",
      takeaway: "Животное года — одна календарная метка. Бацзы использует год, месяц, день и час. Более подробное сравнение не становится от этого доказанным измерением любви.",
      sections: [
        ["Что сравнивает таблица животных года?", "Обычная таблица сопоставляет животных двух лет рождения. Её легко запомнить, но она не различает людей одного знака с разными месяцами, днями и часами рождения. Вблизи смены года важно уточнять календарное правило, а не брать знак с общего плаката. В полном расчёте DestinyPixel границей годового столпа служит начало весны Личунь; это не то же самое, что первый день лунного нового года."],
        ["Что добавляют четыре столпа?", "Каждый столп содержит небесный ствол и земную ветвь: вместе год, месяц, день и час дают восемь знаков. Гонконгская обсерватория описывает эти календарные пары и цикл из шестидесяти сочетаний. Это источник о календаре, а не доказательство предсказаний. Ствол дня служит ориентиром в символическом чтении пяти элементов. Но даже разные сочетания не показывают, держит ли человек слово, умеет ли слушать и совпадают ли ваши жизненные планы."],
        ["Как понимать поддержку и сдерживание элементов?", "Дерево, огонь, земля, металл и вода образуют традиционный язык отношений. Поддержка может предложить тему отдачи и принятия, сдерживание — тему границ. Это не деление на хороших и плохих партнёров. Один даёт советы из заботы, другой слышит постоянные исправления. Спросите, что сейчас нужно: поддержка, конкретная помощь или свобода решения. Здесь метафора помогает обсудить опыт; она не доказывает, что элемент вызвал поведение или сделал конфликт неизбежным."],
        ["Зачем нужны шестьдесят животных?", "Названия, изображения и характеры карт DestinyPixel — авторское оформление календарных сочетаний, а не древняя диагностика личности. Каждый может выбрать одно описание, совпадающее с реальным случаем, и одно неподходящее. Не назначайте партнёру характер за него. Даже похожие образы не означают одинаковый способ проявлять нежность. Карты открывают разговор, не доказывают предопределённость союза и не добавляют тайных баллов к оценке."],
        ["Что вычисляет бесплатный инструмент?", "Общий показатель сочетает сравнение элементов бацзы с отдельными планетными отношениями: тридцать процентов и семьдесят процентов соответственно. Шкала от шестидесяти до ста — редакционный индекс, не вероятность успешного брака. Есть сравнения характера, общения, проявления чувств и повседневного ритма. ИИ объясняет готовый результат, но не выставляет балл. Это не полная традиционная оценка брака и не полная западная синастрия: дома, асценденты и дата свадьбы не рассчитываются."],
        ["Как перейти от чтения к разговору?", "Сначала оба проверьте дату, записанное время и город рождения. Затем независимо ответьте на небольшой вопрос: после тяжёлого рабочего дня вам нужны вопросы, компания или тишина? Сравните ответы с чтением и договоритесь об одном действии, например заранее говорить, когда вернётесь к прерванному разговору. Через неделю обсудите результат. Если описание не подходит, сохраните своё несогласие. Цель — яснее понимать друг друга, а не подчиняться ярлыку."],
      ], action: { label: "Бесплатно сравнить две карты", href: "/compatibility?locale=ru" },
    },
  },
  {
    slug: "compatibility-without-birth-time", relatedSlug: "bazi-vs-chinese-zodiac-compatibility",
    sources: [{ label: "IANA · Time Zone Database / 时区资料 / База часовых поясов", href: "https://www.iana.org/time-zones" }, { label: "DestinyPixel · Birth details / 出生资料 / Данные рождения", href: "/journal/prepare-birth-date-time-place" }],
    en: {
      title: "Can you check BaZi compatibility without a birth time?",
      description: "No birth time? Learn what a birthday-only reading can show, why guessing noon changes the chart, and which free DestinyPixel tools you can use instead.",
      topic: "Before you compare", introduction: "You know both birthdays, but only one birth time. It is tempting to enter noon and get on with the reading, especially when the form will not continue without it. The problem is that a convenient placeholder can produce a very confident-looking answer. Here is how to explore what you do know, keep missing information visible and avoid presenting an estimate as something you found in a birth record.",
      takeaway: "The current compatibility form needs both recorded birth times and supported birth cities. A birthday-only card is a narrower starting point, not a substitute for the missing hour.",
      sections: [
        ["What changes when the hour is missing?", "The hour is one of the four BaZi pillars. An unknown time therefore leaves part of the calendar structure unresolved. Planetary positions also depend on the instant being calculated; their sensitivity is not identical, and a birthday is not a complete instant without time and place. More importantly, you cannot recover missing information just by reading a persuasive paragraph. A chart that feels familiar is not proof that the selected hour was right. Separate the question of which input is recorded from the question of whether an interpretation is interesting, and do not let the second question answer the first."],
        ["Why not simply enter 12:00?", "Noon is a convention some people use for an explicitly limited exploration. It is not a recovered birth time, and the current DestinyPixel couple form does not offer a dedicated unknown-time mode. Filling noon into its required field would calculate a chart for that assumed time. The interface would not make the missing information disappear. If you are comparing possibilities privately, label every assumption and avoid saving a guessed chart as an accurate personal record. Do not choose the time that gives the most flattering score, since that changes the question from understanding the input to selecting the answer you wanted."],
        ["Where can you look for a better record?", "If available, start with a birth certificate, a contemporaneous hospital record or a family note made around the birth. You do not need to upload private documents to DestinyPixel. Copy the local clock time and write down its source separately. If a relative remembers a range, keep the range: between seven and eight is different from an exact seven thirty. Also confirm whether the written date is Gregorian or lunar and whether an AM or PM label was omitted. A time that looks precise may still have been rounded, so keep uncertainty visible instead of adding invented minutes."],
        ["Keep time attached to its original place", "Use the birth city and its local recorded time, not your current city or the time displayed on your phone today. Historical clock rules and daylight saving can change the conversion into a single instant. The IANA Time Zone Database documents time-zone histories; it does not certify an individual birth record. DestinyPixel applies its supported city’s time zone and separate solar-time correction internally, so do not pre-convert the input to Beijing time or adjust it a second time yourself. If the form reports a repeated or nonexistent clock time, investigate that record rather than changing the hour to silence the message."],
        ["What can you explore with only a date?", "The free Day Pillar card accepts a birthday and offers a date-based calendar character. It provides a smaller introduction to the sixty portraits without pretending to supply the missing hour or a complete couple comparison. Treat that as a date-only starting point; a birth close to a day boundary needs extra care when comparing systems that use different clock or solar-time conventions. You can also use the question-based fortune-stick experience without either partner’s birth data. For a relationship question, focus on something you can discuss or observe rather than asking the tool to reveal your partner’s private thoughts."],
        ["A practical choice for two people", "Make a short note for each person: verified date, verified time or remembered range, birthplace and unresolved questions. If both records are clear and the cities are supported, use the free compatibility form. If an hour remains unknown, read your date-based cards separately and compare actual habits: how do you ask for help, show affection or ask for space? Those questions are available immediately and do not depend on a missing certificate. Return to the fuller comparison when the input improves. A smaller honest reading is more useful than a precise-looking result whose most important assumptions have been forgotten."],
      ], action: { label: "Start with a free birthday card", href: "/day-pillar" },
    },
    zh: {
      title: "不知道出生时间，能做八字合婚吗？先分清可查与不可猜的部分",
      description: "只有生日、没有时辰怎么办？解释八字配对的输入要求、为什么不能随便填中午，以及日柱卡和抽签能提供哪些免费替代体验。",
      topic: "配对前的准备", introduction: "两个人的生日都知道，却只有一个人记得出生时间。看到表单必须填时辰，很容易想：先写中午十二点看看吧。问题是，一个随手填入的时间，也可能得到一份看起来非常肯定的结果。先分清哪些资料有记录、哪些仍然不确定，才能知道自己看到的究竟是什么。",
      takeaway: "当前情感匹配需要双方记录中的出生时间及支持的出生城市。只有生日时，可以从日柱卡开始，但不能把它当成完整合婚。",
      sections: [
        ["缺少时辰，会少掉什么？", "时柱是八字四柱的一部分，缺少出生时间就有一部分历法结构无法确定。行星位置也与具体时刻有关，各行星对时间的敏感程度并不相同。更关键的是，一段读起来很像你的文字，不能倒过来证明某个时辰正确。要把“输入来自什么记录”和“解释是否有启发”分开，不能让后者替前者作答。"],
        ["为什么不建议直接填12:00？", "中午可以被明确标记为一种探索假设，却不是找回的出生时间。当前本站双人匹配没有独立的“未知时间”模式，填入中午就会按中午计算，缺失的信息并不会因此消失。即使私下比较几种可能，也应注明假设，不要把猜测存成准确出生记录。尤其不要挑分数最高的那个时间，那是在选择想要的答案，而不是核实资料。"],
        ["可以去哪里找更可靠的时间？", "如果能找到，先看出生证明、当时的医院记录或同期家庭笔记，不必把私人文件上传到本站。抄下原记录中的当地时间，另外记住来源。亲属只记得七点到八点，就保留这个范围，不要补成精确的七点半。同时确认日期用的是公历还是农历，以及有没有漏掉上午、下午。精确到分钟的数字也可能经过取整，不要人为增加确定性。"],
        ["出生时间必须和出生地一起保留", "填写出生地当时的本地钟表时间，不是现在居住城市的时间。历史时区和夏令时会影响具体时刻的换算；IANA时区数据库记录地区时区历史，但不为某个人的出生证明作认证。本站会根据支持的城市处理时区并单独进行太阳时修正，不要先转北京时间或自行重复校时。遇到重复或不存在的钟表时刻提示，应核查记录，不要随意改小时绕过提示。"],
        ["只有日期，现在可以玩什么？", "免费日柱卡接受生日，给出按日期得到的历法意象，是认识六十种动物角色的较小入口，不会补出缺失的时柱，也不等于双人合婚。出生在换日边界附近时，还要注意不同系统的钟表时间和太阳时约定。也可以使用不要求生日的抽签体验，把感情问题放在自己能观察、能沟通的事情上，而不是让工具猜测对方没说出口的想法。"],
        ["两个人可以这样安排下一步", "分别写清楚：已核实的生日、准确时间或记忆范围、出生地，以及还不确定的地方。双方记录清楚且城市受支持，再使用匹配表单；时间仍未知，就先各自读日柱卡，讨论怎样求助、怎样表达关心、怎样需要独处。这些对话不需要等一张证明。资料更完整后再看完整比较，通常比忘记假设、只记住分数更有帮助。"],
      ], action: { label: "先领取免费日柱卡", href: "/day-pillar?locale=zh" },
    },
    ru: {
      title: "Можно ли сравнить бацзы, если время рождения неизвестно?",
      description: "Что доступно по одной дате, почему полдень не заменяет неизвестное время и с каких бесплатных инструментов DestinyPixel начать.",
      topic: "Подготовка к сравнению", introduction: "Вы знаете обе даты рождения, но время известно лишь для одного человека. Хочется вписать полдень и продолжить. Однако удобная заглушка способна дать очень уверенно выглядящий результат. Разберём, что можно исследовать сейчас, как сохранить неизвестное неизвестным и не выдать предположение за запись из документа.",
      takeaway: "Нынешняя форма совместимости требует время рождения обоих людей и поддерживаемые города. Карта по дате — более узкое знакомство с системой, а не замена неизвестному часу.",
      sections: [
        ["Что теряется без часа?", "Час — один из четырёх столпов бацзы, поэтому часть структуры остаётся неопределённой. Положения планет тоже зависят от момента расчёта, хотя чувствительность у них различается. Убедительный текст не восстанавливает недостающие сведения. Даже если описание кажется знакомым, это не доказывает правильность выбранного часа. Отделяйте происхождение исходных данных от интереса к интерпретации."],
        ["Почему нельзя просто поставить 12:00?", "Полдень может быть явно обозначенным предположением для ограниченного исследования, но не найденным временем рождения. У текущей формы DestinyPixel нет специального режима неизвестного времени: введённый полдень будет использован как время расчёта. При личном сравнении вариантов отмечайте каждую гипотезу и не сохраняйте её как точную запись. Не выбирайте час по самому приятному баллу: так вы подбираете желаемый ответ, а не проверяете данные."],
        ["Где искать более надёжную запись?", "Если доступны, проверьте свидетельство, больничную запись или семейную заметку того времени. Загружать личные документы на сайт не требуется. Сохраните местное время и отдельно его источник. Воспоминание «между семью и восемью» не превращайте в точные семь тридцать. Уточните календарь, утро или вечер и возможное округление: наличие минут в записи ещё не гарантирует точности."],
        ["Сохраняйте связь времени с местом", "Используйте местное время в городе рождения, а не нынешнее место жительства. Исторические часовые пояса и летнее время влияют на перевод в конкретный момент. База IANA описывает историю часовых поясов, но не удостоверяет личный документ. Сайт сам применяет правила поддерживаемого города и отдельную поправку солнечного времени. Не переводите данные заранее в пекинское время. При сообщении о повторяющемся или несуществующем времени исследуйте запись, а не меняйте час ради прохождения формы."],
        ["Что доступно по одной дате?", "Бесплатная карта столпа дня принимает дату и даёт календарный образ, знакомя с шестьюдесятью персонажами. Она не восстанавливает час и не заменяет сравнение пары. При рождении около границы суток особенно важны различия между календарными и солнечными правилами разных систем. Оракул палочек вообще не требует данных рождения: вопрос об отношениях можно связать с наблюдаемой ситуацией, а не с попыткой узнать тайные мысли партнёра."],
        ["Как выбрать следующий шаг вдвоём?", "Запишите для каждого подтверждённую дату, время или известный диапазон, место и оставшиеся вопросы. Если данные ясны и города поддерживаются, переходите к сравнению. Если час неизвестен, прочитайте карты дня отдельно и обсудите реальные привычки: как просите помощи, проявляете заботу и обозначаете потребность в тишине. Такой разговор возможен уже сейчас. К подробному расчёту вернитесь, когда появятся более полные сведения."],
      ], action: { label: "Карта по дате рождения (на английском)", href: "/day-pillar" },
    },
  },
  {
    slug: "how-to-ask-fortune-sticks", relatedSlug: "fortune-stick-number-and-edition",
    sources: [{ label: "DestinyPixel · Fortune sticks / 抽签使用说明 / Оракул палочек", href: "/sticks" }, { label: "DestinyPixel · Guanyin collection guide / 观音签指南 / Коллекция Гуаньинь", href: "/learn/guanyin-fortune-sticks" }],
    en: {
      title: "How to ask a fortune-stick question: love, work and change",
      description: "Turn a vague fortune-stick question into a useful one. Practical love and career examples, a simple draw routine, and how to turn a reading into a next step.",
      topic: "A question worth bringing", introduction: "You open the oracle and suddenly cannot decide what to ask. Will everything work out? Do they love me? Is this the right path? Those questions carry real feelings, but they give a symbolic reading very little context. You do not need special words or a perfect ritual. Start with the situation in front of you, one uncertainty and something you can actually notice or do after reading.",
      takeaway: "A useful question names one situation and one next step. The result can prompt reflection; it cannot supply facts about another person or guarantee an outcome.",
      sections: [
        ["Start with one situation, not your whole future", "Write down what has happened in a plain sentence before you draw: we keep postponing a conversation about moving, or I have an offer but have not clarified the working hours. Then ask what deserves your attention next. This gives you a way to read the imagery without stretching every line to fit everything in your life. It also helps you notice when an interpretation has wandered away from the question. You can keep identifying details out of the text; names, addresses and private messages are usually unnecessary for this kind of reflection. Specific does not have to mean personally revealing."],
        ["For love: move from mind-reading to conversation", "Instead of asking whether someone secretly loves you, try: what do I need to clarify before asking where this relationship is going? Or: how can I explain my need for reassurance without speaking for my partner? These versions do not promise a hidden answer. They return attention to what you can say, ask and observe. For example, write the sentence you have been avoiding, then check whether it invites an honest response or already contains an accusation. A reading cannot establish someone else’s feelings, loyalty or intentions. Their own words and consistent actions remain the evidence you need in the relationship."],
        ["For work: identify the missing fact", "A question such as should I accept this role can feel impossible because several questions are bundled together. Try asking what you need to clarify before deciding. After the reading, list the concrete facts still missing: expected hours, responsibilities, reporting arrangements or how success will be assessed. Choose one fact to obtain from the relevant person or document. The symbolic text may help you articulate a concern, but it cannot verify an employer’s promises or calculate whether an offer is financially suitable. Keep the actual decision attached to real terms and your own circumstances rather than treating an encouraging phrase as a recommendation."],
        ["For change: make the next step small enough to see", "When everything feels unsettled, a question about the rest of your life invites an answer too large to use. Narrow it to a near-term action: what am I overlooking before I make this move, or what could help me test this new routine for a week? A useful outcome might be a conversation, a practical check or a small experiment. It need not be a dramatic revelation. Write down what you expect to learn and when you will review it. The point is to reduce the distance between reflection and action, while leaving room for new information to change your view."],
        ["Draw once, then read the source note", "On DestinyPixel, select a collection and topic, keep one question in mind and let the draw finish. You can then request an optional AI interpretation for the question. First read the numbered text and its source note: the site combines selected traditional material with modern symbolic readings rather than reproducing every temple edition. A traditional verse, a translation, a modern adaptation and an AI explanation are different layers. If you already hold a temple slip, check its named collection and wording before matching the number online. The next guide explains why the number alone is not enough to identify the text."],
        ["What if you dislike the answer?", "Pause before drawing again just to obtain a more comfortable line. Notice what bothered you and separate the image in the text from a fact about your situation. Write three short notes: the question I brought, the phrase that caught my attention and one thing I can check or discuss. You may decide that the reading is not useful; there is no need to force it to fit. Revisit the situation when circumstances change, rather than treating repeated draws as a way to make reality agree. This question-writing routine is DestinyPixel’s practical suggestion, not a claim about a universal temple ritual."],
      ], action: { label: "Bring one question to the oracle", href: "/sticks" },
    },
    zh: {
      title: "求签怎么问问题？感情、事业与人生变化的六个实用步骤",
      description: "不知道抽签时该问什么？用感情与工作实例，把模糊问题改成可沟通、可核实的问题，再把签文转成一个实际行动。",
      topic: "把问题说清楚", introduction: "打开签堂，反而不知道问什么：一切会好吗？他爱我吗？这条路对不对？这些问题背后有真实的情绪，却很难给象征性解读一个清楚的落点。不需要特别的措辞，先说清眼前的处境、一件不确定的事，以及看完以后能观察或做的一小步。",
      takeaway: "一次只问一个处境中的一个问题。签文可以引发思考，不能替你查明别人的想法，也不能保证结果。",
      sections: [
        ["先说一个处境，不问整个未来", "抽之前，用普通话写一句发生了什么，例如：我们一直拖着没谈搬家的事；我收到了工作邀请，但还不清楚工作时间。然后再问接下来该留意什么。这样读签时就不必把每一句硬套到整个人生，也更容易发现解释有没有偏离问题。描述具体，不代表要提交姓名、地址和私人聊天记录；通常不需要这些信息。"],
        ["问感情：从猜心转向沟通", "与其问“对方是不是偷偷爱我”，可以问：“谈关系下一步之前，我还需要说清什么？”或者：“我怎样表达需要被回应，而不替对方下结论？”这类问法把关注点放回能说、能问、能观察的事情。试着写下你一直没说出口的那句话，看看它是在邀请回答，还是已经包含指责。签文无法证实一个人的感情、忠诚和意图，这些仍需要对方自己的表达与持续行动。"],
        ["问事业：找出缺的那条信息", "“我该不该接受这份工作”常常把很多问题挤在一起。可以先问：“作决定前，我还需要核实什么？”看完后列出缺的信息：工作时间、职责、汇报关系，或评价表现的方式，再挑一项去向相关人员或文件求证。象征文字可以帮你说清担忧，但不能核实雇主承诺，也不能替你判断收入安排是否适合自己。实际选择还是要回到真实条件。"],
        ["问变化：把下一步缩小到看得见", "生活一团乱时，问一辈子往哪里走，很容易得到大到无法使用的回答。不如改成：“搬家前，我可能忽略了什么？”或“接下来一周，我怎样试行这个新习惯？”有用的结果可能只是一次谈话、一次核查或一个小实验，不必是惊天启示。写清想了解什么，以及什么时候回顾，让反思与行动接起来，也允许新信息改变自己的看法。"],
        ["抽一签，再看来源说明", "在本站选择签系与主题，带着一个问题完成抽签，再按需请求AI解释。先读签文旁的来源说明：本站包含部分传统资料和现代象征解读，不是每座庙本的完整复制。传统原文、译文、现代改写、AI解释是不同层次。如果手里已有寺庙签纸，应先确认签系与文字，再按号码查找。下一篇指南会说明为什么签号相同，内容也可能不同。"],
        ["不喜欢答案时，先不要急着重抽", "留意到底是哪句话让你不舒服，把象征画面与现实事实分开。记三件事：我带来的问题、吸引我注意的句子、接下来能核实或讨论的一件事。觉得没帮助，也可以承认不适合，不必强行对号入座。等处境有变化再回看，比反复抽到满意为止更容易看清自己在意什么。这套提问练习是本站的实用建议，不代表所有寺庙都采用同一种仪式。"],
      ], action: { label: "带着一个问题进入签堂", href: "/sticks?locale=zh" },
    },
    ru: {
      title: "Как задать вопрос оракулу палочек: любовь, работа и перемены",
      description: "Практические примеры вопросов об отношениях и работе: как уточнить ситуацию, прочитать источник текста и выбрать небольшой следующий шаг.",
      topic: "Сформулировать свой вопрос", introduction: "Вы открыли оракул и растерялись: всё ли получится, любит ли он меня, верно ли я иду? За этими словами стоят настоящие чувства, но символическому чтению не хватает контекста. Начните с одной ситуации, одной неопределённости и небольшого действия, которое возможно после чтения. Особые слова и идеальный ритуал не нужны.",
      takeaway: "Полезный вопрос описывает одну ситуацию и ближайший шаг. Чтение может помочь размышлению, но не раскрывает чужие мысли и не гарантирует результат.",
      sections: [
        ["Одна ситуация вместо всего будущего", "Сначала запишите, что произошло: вы откладываете разговор о переезде или получили предложение работы без ясного графика. Затем спросите, на что обратить внимание дальше. Так меньше соблазна подгонять каждую строку под всю жизнь и легче заметить, что интерпретация ушла в сторону. Конкретность не требует раскрывать личное: имена, адреса и переписка для такого размышления обычно не нужны."],
        ["В любви: от чтения мыслей к разговору", "Вместо вопроса о тайных чувствах попробуйте: что стоит прояснить перед разговором о будущем отношений? Или: как объяснить потребность в поддержке, не отвечая за партнёра? Запишите избегаемую фразу и проверьте, приглашает ли она ответить или уже обвиняет. Чтение не устанавливает верность, чувства или намерения другого человека. Его слова и последовательные поступки остаются необходимыми свидетельствами."],
        ["В работе: найдите недостающий факт", "Вопрос о принятии предложения часто объединяет сразу несколько неизвестных. Спросите, что нужно уточнить до решения. После чтения перечислите реальные пробелы: график, обязанности, кому подчиняться, как оценивается работа. Выберите один пункт и получите ответ у соответствующего человека или в документе. Символический текст помогает сформулировать тревогу, но не проверяет обещания работодателя и не определяет финансовую пригодность предложения."],
        ["В переменах: достаточно маленький шаг", "Когда всё неопределённо, вопрос обо всей жизни даёт слишком большой ответ. Лучше спросить, что вы упускаете перед переездом или как попробовать новый распорядок в течение недели. Результатом может стать разговор, проверка или небольшой эксперимент. Запишите, что хотите узнать и когда вернётесь к оценке. Это связывает размышление с действием и оставляет возможность изменить мнение после новых сведений."],
        ["Вытяните палочку и прочитайте источник", "На DestinyPixel выберите коллекцию и тему, сосредоточьтесь на одном вопросе и дождитесь окончания. Затем при желании запросите объяснение ИИ. Сначала прочитайте пометку об источнике: библиотека сочетает отдельные традиционные материалы с современными символическими текстами. Оригинал, перевод, адаптация и объяснение ИИ — разные слои. Если у вас храмовый листок, сверяйте название коллекции и слова, а не только номер."],
        ["Если ответ не понравился", "Не спешите тянуть снова ради приятной строки. Отметьте, что задело, и отделите образ от факта. Запишите исходный вопрос, привлёкшую внимание фразу и одно дело для проверки или обсуждения. Можно признать, что чтение вам не помогло: подгонять его не требуется. Возвращайтесь, когда ситуация изменится. Это практическое упражнение DestinyPixel, а не утверждение о едином ритуале всех храмов."],
      ], action: { label: "Перейти к оракулу палочек", href: "/sticks?locale=ru" },
    },
  },
  {
    slug: "fortune-stick-number-and-edition", relatedSlug: "how-to-ask-fortune-sticks",
    sources: [{ label: "DestinyPixel · Collection and source notes / 签系与来源说明 / Коллекции и источники", href: "/sticks" }, { label: "DestinyPixel · Guanyin lookup scope / 观音查签范围 / Поиск Гуаньинь", href: "/learn/guanyin-fortune-sticks" }],
    en: {
      title: "Why the same fortune-stick number can have different meanings",
      description: "Looking up a Guanyin or temple fortune-stick number? Check the collection, original wording and edition before trusting an online meaning or AI explanation.",
      topic: "Reading the source", introduction: "You leave a temple with a numbered slip, search the number online and find a poem that looks nothing like yours. A second page gives another meaning. Before worrying that you have received contradictory predictions, check whether the pages are even discussing the same text. A number identifies a position within a collection; by itself it does not establish the collection, the edition or the wording you are trying to understand.",
      takeaway: "Match the named collection and the actual verse before matching an interpretation. A familiar number is not enough to identify your temple slip.",
      sections: [
        ["Start with the name above the number", "Keep a note of the temple or publisher, the collection name and the number exactly as shown on your slip. A Guanyin collection and a Guandi collection should not be treated as interchangeable search results just because both contain a number thirty-three. If the slip has no clear collection name, keep the opening line and ask the place that issued it when possible. You can record this privately without uploading a photograph. The first task is identifying the text, not deciding whether the online interpretation sounds comforting. A page with a confident title can still belong to the wrong collection."],
        ["Compare words before comparing meanings", "Place the opening lines side by side. Are they the same verse, a translation of it or a completely different text? Check any title, accompanying story and source note as well. A modern paraphrase may intentionally use different words, but it should make clear what it is paraphrasing. If the opening lines do not match and the page supplies no edition information, stop short of claiming you have found the meaning of your exact slip. You can still read it as a separate symbolic text. Keeping those two uses distinct prevents a search result from silently replacing the document you actually received."],
        ["Separate four layers of a reading", "The original verse is the text being discussed. A translation carries it into another language and may need to explain images or wordplay. An adaptation can reshape the imagery for a contemporary audience. An interpretation then connects the text with a situation or question. These layers can all be useful, but they do different jobs. A newly written English reflection is not automatically a line-by-line translation of a Chinese poem. An AI response based on that reflection is another interpretive layer, not a newly discovered historical source. Look for clear labels before treating any of these versions as interchangeable evidence."],
        ["What DestinyPixel’s number lookup provides", "The site offers five collections, with one hundred entries each for Guanyin, Guandi and Wong Tai Sin, and sixty each for Yuelao and the Wealth Gods. These are the ranges in this product, not a statement that every temple uses these same collections. The library combines selected traditional material with modern symbolic texts. Its source notes distinguish the kind of material shown, and language editions may contain adaptations rather than matching translations. When you enter a number, you retrieve the corresponding entry in this library. That does not certify that the entry reproduces the exact paper slip you obtained elsewhere."],
        ["Can AI explain the slip anyway?", "An AI explanation is useful only within the material and context supplied to it. On this site the optional reading explains the displayed library entry in relation to your question. It does not authenticate your temple slip, consult an unseen original or inspect a photograph of the paper you are holding. If the displayed entry differs from your slip, its explanation belongs to that displayed entry. Avoid filling the gap by assuming that all versions must mean the same thing. For a specific temple edition, consult its own published explanation or ask the issuing temple about the actual wording when that is possible."],
        ["A simple lookup checklist", "Before searching, collect four details: collection name, number, opening line and named source if one is printed. In a search query, include the collection and an exact opening phrase rather than only the number. Once you find a candidate page, compare its wording and source label, then decide whether you want a translation, cultural context or a personal reflection. Those are different requests and may need different resources. If you cannot identify the edition, keep that uncertainty in your notes. You can still use a modern reading as a conversation prompt, while being honest that you have not established the meaning of the original temple document."],
      ], action: { label: "Explore the collections and source notes", href: "/sticks" },
    },
    zh: {
      title: "同一个签号，为什么签文不同？查观音灵签前先核对这四件事",
      description: "寺庙求到的签和网上解签不一样？先查签系、签号、原文与版本，区分传统签文、翻译、现代改写和AI解释。",
      topic: "读签也读来源", introduction: "从庙里带回一张签纸，按号码一搜，诗句却完全不同；再打开另一页，解释又变了。先别急着理解成互相矛盾的预言，要确认大家谈的是不是同一篇文字。签号标记的是某个签系内部的位置，单靠数字不能确定签系、版本和你手中那段文字。",
      takeaway: "先对签系和实际诗句，再对解释。号码一样，不足以证明网上找到的就是手里的那支签。",
      sections: [
        ["先看号码上方写的是什么", "记下寺庙或出版者、签系名称，以及签纸上的号码。观音签和关帝签即使都出现第三十三签，也不能当成同一个搜索结果。签系不清楚时，保留开头原句，条件允许就向发签处询问。可以自己记录，不必上传签纸照片。第一步是辨认文字，不是挑一个听起来舒服的解释；标题再肯定，也可能来自不同签系。"],
        ["先比较文字，再比较意思", "把签诗开头并排看：是同一首、翻译，还是完全不同的文字？也看看题名、典故和来源注记。现代转述可以换措辞，但应说明依据什么改写。如果开头不同，页面又没有版本信息，就不要声称已经找到了手中签纸的准确解释。它仍可以作为另一段象征文字来阅读，只是不能悄悄替换原来得到的那张签。"],
        ["把四个层次分清楚", "原文是被讨论的文字；翻译把它转成另一种语言，可能需要解释意象和双关；改写为现代读者重新组织表达；解读则把文字与具体问题联系起来。四者都可能有用，但作用不同。新写的一段英文反思不自动等于中文签诗的逐句翻译，AI再解释它，也不是发现了新的古籍来源。把标签读清楚，再决定如何使用。"],
        ["本站按签号查到的是什么？", "本站观音、关帝、黄大仙各收录100个条目，月老和财神各60个，这是产品里的编号范围，并不代表每座庙都用这套排列。资料库包含部分传统材料与现代象征文字，来源说明标记材料类型，不同语言也可能采用改写而非逐句对应。输入号码查到的是本站资料库中的对应条目，并不能认证它就是你在别处领到的纸签。"],
        ["AI能不能直接解释手里的签？", "本站可选AI解读依据当前显示的资料库条目和你提交的问题，不会认证寺庙签纸，不会读到未提供的原文，也不会查看你手里拿着的纸张照片。如果显示条目与手中签纸不同，解释针对的就是显示条目。不要自行假设所有版本意思都一样。想核实某一庙本，应寻找该版本公开说明，或在条件允许时询问发签处的原文含义。"],
        ["查签前的一张小清单", "保留四项：签系、号码、开头原句、印刷来源。搜索时带上签系和一段准确原句，不只输入数字。找到候选页面后核对文字与来源，再明确自己要的是翻译、文化背景，还是个人反思，这可能需要不同资料。版本无法确认，就保留这个不确定性；可以用现代解读打开话题，同时诚实地承认还没有核实原签的解释。"],
      ], action: { label: "查看签系、签文与来源说明", href: "/sticks?locale=zh" },
    },
    ru: {
      title: "Почему один номер палочки может означать разные тексты?",
      description: "Как сверить храмовый листок с онлайн-оракулом: название коллекции, первые строки, издание и различия между переводом, адаптацией и ответом ИИ.",
      topic: "Текст и его источник", introduction: "Вы принесли из храма пронумерованный листок, нашли номер в интернете, а стих оказался другим. Следующая страница объясняет его иначе. Прежде чем видеть противоречивые предсказания, проверьте, о том ли тексте речь. Номер обозначает место внутри коллекции; сам по себе он не устанавливает коллекцию, издание или слова вашего листка.",
      takeaway: "Сначала сопоставьте коллекцию и сам стих, затем объяснение. Одинакового номера недостаточно, чтобы опознать храмовый текст.",
      sections: [
        ["Посмотрите на название над номером", "Сохраните название храма или издателя, коллекцию и номер в исходном виде. Коллекции Гуаньинь и Гуаньди не взаимозаменяемы, даже если обе содержат номер тридцать три. Если название неясно, запишите первую строку и по возможности спросите там, где получили листок. Загружать фотографию необязательно. Сначала нужно установить текст, а не выбрать самое утешительное объяснение."],
        ["Сравните слова раньше значений", "Сопоставьте первые строки: это тот же стих, перевод или совсем другой текст? Проверьте заголовок, сопровождающую историю и указание источника. Современный пересказ может менять слова, но должен обозначать основу. Если строки не совпадают, а издание не названо, нельзя уверенно считать страницу толкованием именно вашего листка. Читать её отдельно можно, незаметно подменять ею исходный документ — не стоит."],
        ["Различайте четыре слоя", "Оригинал — обсуждаемый текст. Перевод переносит его в другой язык и иногда объясняет образы. Адаптация меняет подачу для современной аудитории. Интерпретация связывает текст с вопросом человека. Это разные задачи. Новый английский текст не обязательно является построчным переводом китайского стиха, а объяснение ИИ не превращается в найденный исторический источник. Сначала прочитайте обозначения этих слоёв."],
        ["Что выдаёт поиск номера на DestinyPixel?", "В продукте по сто записей для Гуаньинь, Гуаньди и Вонг Тай Сина и по шестьдесят для Юэлао и богов богатства. Это диапазоны сайта, не утверждение об устройстве всех храмовых изданий. Библиотека объединяет отдельные традиционные материалы и современные символические тексты, а языковые версии могут быть адаптациями. Поиск возвращает запись этой библиотеки, но не удостоверяет её совпадение с полученной в другом месте бумажной палочкой или листком."],
        ["Что в таком случае объясняет ИИ?", "Дополнительное чтение на сайте использует отображаемую запись и ваш вопрос. Оно не удостоверяет храмовый листок, не читает невидимый оригинал и не рассматривает фотографию бумаги у вас в руках. Если запись отличается от листка, объяснение относится к записи. Не предполагайте автоматически одинаковый смысл всех версий. Для конкретного издания ищите его опубликованное объяснение или спрашивайте выдавший документ храм, когда это возможно."],
        ["Короткая проверка перед поиском", "Запишите коллекцию, номер, первую строку и указанный источник. В запрос добавьте название и точную фразу, а не только цифру. На найденной странице сопоставьте текст и источник, затем решите, что вам нужно: перевод, культурный контекст или личное размышление. Если издание не удалось установить, сохраните эту неопределённость. Современное чтение можно использовать как начало разговора, не объявляя его проверенным объяснением исходного документа."],
      ], action: { label: "Открыть коллекции и пояснения источников", href: "/sticks?locale=ru" },
    },
  },
  {
    slug: "unfavorable-fortune-stick-reading", relatedSlug: "how-to-ask-fortune-sticks", publishedAt: "2026-09-23", updatedAt: "2026-09-23",
    sources: [
      { label: "Hong Kong Tourism Board: Wong Tai Sin Temple", href: "https://www.discoverhongkong.com/eng/place-to-go/travel.guide-wong-tai-sin-temple.html" },
      { label: "Wen Wei Po, 27 January 2026: Sik Sik Yuen abbot on Wong Tai Sin sticks", href: "https://www.tkww.hk/epaper/view/newsDetail/2015847422080716800.html" },
      { label: "Chinese Wikipedia: 求籤", href: "https://zh.wikipedia.org/wiki/%E6%B1%82%E7%B1%A4" },
      { label: "English Wikipedia: Kau chim", href: "https://en.wikipedia.org/wiki/Kau_chim" },
      { label: "DestinyPixel fortune sticks", href: "/sticks" },
      { label: "How to ask a fortune-stick question", href: "/journal/how-to-ask-fortune-sticks" },
      { label: "Same stick number, different edition", href: "/journal/fortune-stick-number-and-edition" },
      { label: "Guanyin collection guide", href: "/learn/guanyin-fortune-sticks" },
    ],
    en: {
      title: "What to do after an unfavorable fortune-stick reading",
      description: "Drew a stick you dislike? See what DestinyPixel’s redraw button does, how to read the source note, and how to turn the result into one question you can check.",
      topic: "After a difficult stick",
      introduction: "The stick lands and the level looks harsh. Drawing again until the words soften, or cancelling a plan on the strength of the label, skips the page in front of you. This guide answers the practical questions first, then keeps four layers apart: one temple’s custom, this site’s random draw, the library’s symbolic text, and the optional AI paragraph.",
      takeaway: "DestinyPixel lets you draw again after a result. The button is a product control: it sets no rule for every temple, and it does not ban a second draw. A disliked level is a catalog label. Name one fact you can check before you change a plan.",
      sections: [
        ["Can I redraw, and should I change the plan?", "On /sticks the button reads “Draw my stick,” then “Draw again” once a stick is showing. Simplified Chinese uses 「再求一签」. Another press draws again in the selected collection. The first number stays a result you received. The control sets no temple rule and does not refuse the second request. Blocked, Wait, 小阻 and 待时 sit on the entry as catalog labels. They are not a medical finding, a financial instruction, or a verdict on a relationship. Before you decline an offer, cancel a trip, or end a conversation, write one fact a person or a document can confirm. The source note names the writing: traditional library material, a Chinese verse in the Chinese edition, or DestinyPixel’s modern symbolic text."],
        ["Temple customs stay with the temple that published them", "The Hong Kong Tourism Board’s Wong Tai Sin guide says visitors shake a bamboo cylinder until one stick falls, then take it to stalls for kau cim. That page states no redraw ban. Wen Wei Po, 27 January 2026, prints a column by Sik Sik Yuen abbot 李耀輝（義覺）: a tube of 100 sticks, one matter, shake until one stick leaves; some worshippers toss moon blocks and record the number only after a confirming throw; slips are free by number; grades 上上, 上吉, 中吉, 中平 and 下下 are read with the person’s situation, time, place and state of mind. Chinese Wikipedia on 求籤 describes Guangdong and Hong Kong as often shake-until-it-falls, many Fujian and Taiwan temples as returning the stick after a failed moon-block throw, and some Japanese shrines as leaving an unlucky slip on a rack. It says grade marks are not absolute. English Wikipedia on Kau chim adds that many cups hold 100 sticks, other counts exist, several sticks falling together are often not counted, and a further try confirms the draw. A disliked poem and an unconfirmed throw are different events."],
        ["What the draw button on DestinyPixel does", "Five collections are on the page: Guanyin, Guandi, Yuelao, the Five Wealth Gods and Wong Tai Sin. Guanyin, Guandi and Wong Tai Sin use 1–100. Yuelao and the Five Wealth Gods use 1–60. After a short shaking pause, the page chooses an integer in that range with crypto.getRandomValues. The question is not an input to that choice. You can type it or leave it blank. Career, Love, Money, Family, Timing and Wellbeing set a theme and do not steer the number. “Already drew offline?” opens this library’s entry inside the same range and does not certify a temple slip. The random step does not show that temple oracles are empty, and it does not show that the number is a supernatural verdict. “Draw again” repeats the same step."],
        ["How to read the source note and the level", "A result shows a level, a title, sign text, a plain reading, advice and a source note. Hand-entered notes call the theme traditional and say temple wording can differ. Many Guandi and Wong Tai Sin numbers show classic Chinese in the Chinese edition. A Wong Tai Sin note can call the poem a traditional sample and the plain reading DestinyPixel’s writing. In English and Russian a verified Chinese verse may appear as a localized reading, and the note points to the Chinese edition. Other numbers are modern symbolic text: normalized lines, verses still being checked, or a line marked as not a verbatim temple poem. Wealth notes say that set is not one canonical temple book. Generated labels cycle through Great Blessing, Good, Steady, Blocked and Wait in English, and 上吉, 中吉, 中平, 小阻 and 待时 in Chinese. Harsher grades on other entries are catalog labels too. This article copies no numbered temple poem."],
        ["What the optional AI paragraph adds", "“Interpret with my question” (Simplified Chinese 「结合问题解读」) posts the collection, number, on-screen sign, topic and question to /api/sticks/interpret. The question may be blank. The model must explain that sign, must not pick a new number, and must not guarantee medical recovery, legal success, investment profit, pregnancy, death, disaster or a fixed fate. Failure shows the plain reading already on the card. If the note says the verse is still being checked, read the AI text as a reflection on the number, the theme and the question."],
        ["Original scenario: a work opportunity you are unsure about", "Original scenario — work-opportunity worry. Editorial example only. The offer is written, the weekly hours are vague, and the level says Blocked or 小阻. Declining tonight, or pressing “Draw again” for a softer label, leaves the offer unchecked. Ask which three duties and which weekly hours are in the written terms. Send that to the hiring contact and name a day to reread the reply. The reply shows whether the plan should change. A later draw needs a new question about that reply."],
        ["Original scenario: anxiety before a booked trip", "Original scenario — travel anxiety. Editorial example only. The trip is booked, the imagery sounds like delay, and cancelling feels safest. Before another draw, check one fact: passport dates, the first connection on the current timetable, or the local contact if a train slips. A sound timetable is not a reason to cancel. A short connection is a reason to change the booking. A later draw can ask what to do about the connection you confirmed."],
      ], action: { label: "Open a stick and read its source note", href: "/sticks" },
    },
    zh: {
      title: "抽到不喜欢的签，要不要重抽、要不要改计划？",
      description: "签不顺时，先看本站的再抽按钮、来源说明和可选AI各管哪一层，再把结果收成一个可以核实的问题。",
      topic: "签不顺的时候",
      introduction: "签落下来，等级不好看，句子又像冲着自己来。接下来常见的两种反应，是一直抽到字眼变软，或把标签当成取消计划的命令。两种反应都绕过了眼前这一页。这篇指南先回答能不能再抽、要不要改计划、来源说明怎么读，再把四层分开：某座庙自己的习俗、本站的随机抽号、资料库里的象征文字，以及可选的AI解释。",
      takeaway: "DestinyPixel 在出结果后允许再抽一签。这个按钮是产品操作，不是所有庙宇的规矩，也不是本站禁止重抽。不喜欢的等级是目录标签。改计划之前，先写出一件可以核实的事。",
      sections: [
        ["可以重抽吗？计划要不要马上改？", "在 /sticks，还没有结果时主按钮是“开始求签”，出现签之后变成“再求一签”。按下去，会在当前选中的签系里再抽一次。第一次的号码仍然是你得到过的结果，第二次是一次新的抽取。这个按钮不替任何庙发布规矩，也不拒绝第二次请求。Blocked、Wait、小阻、待时这类字，是条目上的标签，是卡片上的分类。它不是医学结论，不是财务指示，也不是对一段关系的判决。拒绝一份工作、取消一趟行程或结束一次谈话之前，先写下一件可以由人或文件确认的事实。然后读结果旁边的来源说明。说明会标出你看到的是本库里的传统材料、中文版显示的中文签诗，还是 DestinyPixel 的现代象征文字。说明标的是文字类型，并不证明某项计划会成或会败。"],
        ["庙里的规矩属于那一座庙", "公开页面描述的求签步骤并不只有一种。香港旅游发展局的黄大仙祠介绍写道：访客摇动竹筒，直到一支签掉出，再到祠内摊档请人解释 kau cim。这一页介绍的是一座香火很盛的庙里的做法，并没有公布“禁止再抽”。2026年1月27日《香港文汇报》刊登啬色园黄大仙祠监院李耀辉（义觉）的专栏，把该祠的步骤写得更具体：善信领取一筒一百支签，问一件事，摇到一支签跳出签筒为止。专栏写明一签问一事。有些善信还会卜杯，得到圣杯后才抄下号码。该处按号码免费提供签文纸。专栏列出的等级是上上、上吉、中吉、中平、下下，并说解读要随个人际遇、时间、地点和心境。中文维基百科“求签”条目写道，粤港常见的描述是摇到签条掉出；不少闽台寺庙则在抽出后掷筊，筊未确认就把签放回再抽。部分日本神社会把凶签留在系签架上。同一条目也说吉凶批注并非绝对，不同庙的解释可以不同。英文维基百科 Kau chim 页补充：许多签筒是一百支，也有别的套数；一次掉出多支时，常被看成这次不算。这些记述里的“再来一次”，指的是确认这一抽。不喜欢的诗句，和筊还没有确认的那一支，是两件不同的事。把每座庙公布的步骤留在那座庙上。"],
        ["本站的抽签按钮实际在做什么", "页面有五个签系：观音、关帝、月老、五路财神、黄大仙。观音、关帝、黄大仙的号码是 1 到 100，月老和五路财神是 1 到 60。这些是本产品的范围，并不表示每座庙都印同一套书。按下抽签后，页面会有一小段摇签停顿，再用浏览器的随机函数 crypto.getRandomValues 在所选范围内取一个整数。你写下的问题不参与选号。问题可以写出来，也可以留空，只在心里默念。事业、姻缘、财运、家宅、时机、健康这些主题，给阅读一个方向，并不拨动号码。“线下已经抽到签？”接受同一范围内的整数，打开本资料库里的对应条目。查号显示的是我们的条目，并不能认证寺庙纸签。这里的随机只说明本页怎样选号。它不能用来证明庙里的求签没有意义，也不能用来证明号码是超自然判决。再按一次“再求一签”，就是把同一套步骤再运行一遍。"],
        ["先读来源说明，再决定这些字算不算古本", "每条结果都有等级、题名、签文、白话、行动建议和来源说明。来源说明就是这一层的标签。有些号码是手工录入的传统样本，说明会写明主题来自传统、庙本文字可能不同。许多关帝号码，以及许多黄大仙号码，在中文版带有传统中文文本。黄大仙这类条目的说明可以写：这里有传统签诗样本，白话解读由 DestinyPixel 编写。英文和俄文里，如果该号已有核对过的中文签诗，页面可能显示的是本地化阅读，来源说明会写明中文签诗在中文版。其余号码使用本站的现代象征文字。它们的说明会写：文字经过整理或属于象征解读，逐字庙本仍在核对，或者这一句并不是该号码的庙宇原文。财神签的说明也会写：它不是一套唯一的庙本。自动生成的条目在英文等级里循环使用 Great Blessing、Good、Steady、Blocked、Wait，在中文里循环使用上吉、中吉、中平、小阻、待时。手工样本和传统文本条目还可以带上别的等级词，包括很重的词。这些词都是目录标签。本文不转载带号码的庙宇签诗。请打开你实际得到的那一条，读文字旁边的说明。"],
        ["可选的 AI 解释的是你已经拿到的那一支", "结果出现后，卡片上有“结合问题解读”。请求发往 /api/sticks/interpret，带上签系、号码、屏幕上已经显示的签、所选主题，以及问题文字；问题可以是空的。模型被要求结合这个问题解释已经给出的签，并没有被要求另选一支。同一组说明要求它不要对病愈、诉讼胜诉、投资获利、怀孕、死亡、灾祸或固定命运作保证。请求失败时，页面改显示卡片上已有的白话。加载时界面会写到 DeepSeek。完成后的段落是第四层：对当前条目和你的问题的说明。它不是院子里的解签人，也不是新发现的古代签诗。如果来源说明写着签诗仍在核对，就把 AI 文字读成对号码、主题和你带来的问题的反思。"],
        ["原创情境：对一个工作机会放心不下", "这个情境是原创编辑示例，不是庙里的指示，也不是雇主传来的话。书面邀请已经在桌上，每周工时仍然含糊，等级显示为 Blocked 或小阻。一种冲动是今晚就拒绝，另一种是按“再求一签”，直到标签好看一点。先写一个别人答得出来的问题：书面条款里的三项职责是什么，每周工时是多少？把问题发给招聘联系人，并定一个日子重读回复。签也许帮你把不安说出来了。回复才告诉你计划要不要改。如果以后再抽，给那一次一个关于这份回复的新问题。提问指南说明怎样把下一个问题保持在这么小的范围。"],
        ["原创情境：已经订好的行程让人焦虑", "这个情境是原创编辑示例，不是神社发出的旅行警告。行程已经订好，意象听起来像延误，把一张难看的签理解成取消，好像最安全。先把订单和心情分开。重抽之前先核对一件事：护照是否在有效期内，当前时刻表上的第一段换乘是否够长，或者火车延误时当地联系人是谁。时刻表站得住，焦虑的意象就还没有变成取消的理由。换乘太短，就按时刻表改计划。如果仍想再抽，那一次可以问：刚刚确认的这段换乘，接下来怎么处理。签号与版本指南说明，为什么庙里的签纸和本页可以号码相同、文字却不同。英文的观音签学习页，用同一习惯讲解该签系的来源说明。"],
      ], action: { label: "打开签堂，先读来源说明", href: "/sticks?locale=zh" },
    },
    ru: {
      title: "Неприятный жребий: перетягивать ли палочку и менять ли план",
      description: "Если выпавший жребий не понравился, разделите обычай храма, кнопку повторного выбора DestinyPixel, примечание об источнике и необязательный текст ИИ.",
      topic: "После трудного жребия",
      introduction: "Палочка выпала, метка выглядит сурово, а строка будто обращена лично к вам. Обычно дальше хочется либо тянуть снова, пока слова не станут мягче, либо принять метку как приказ отменить план. Оба шага обходят страницу, которая уже перед вами. Сначала ответы на практические вопросы, затем четыре слоя по отдельности: обычай конкретного храма, случайный выбор номера на этом сайте, символический текст библиотеки и необязательный абзац ИИ.",
      takeaway: "DestinyPixel разрешает вытянуть жребий снова после результата. Кнопка — элемент продукта: она не задаёт правило всем храмам и не запрещает повтор. Неприятная метка — подпись в каталоге. Прежде чем менять план, назовите один факт, который можно проверить.",
      sections: [
        ["Можно ли тянуть снова и нужно ли менять план?", "На странице /sticks до результата русская кнопка называется “Вытянуть жребий”, а после результата — “Вытянуть снова”. В английской версии это “Draw my stick” и “Draw again”, в упрощённом китайском вторая подпись — 「再求一签」. Нажатие запускает новый выбор в уже выбранной коллекции. Первый номер остаётся полученным результатом, второй — новым выбором. Кнопка не объявляет храмовое правило и не отклоняет повторный запрос. Метки вроде Blocked, Wait, 小阻 или 待时 хранятся вместе с записью. Это классификация на карточке. Это не медицинское заключение, не финансовое указание и не приговор отношениям. Прежде чем отказаться от предложения, отменить поездку или прервать разговор, запишите один факт, который может подтвердить человек или документ. Затем прочитайте примечание об источнике рядом с результатом. Оно показывает, перед вами традиционный материал этой библиотеки, китайский стих в китайской версии или современный символический текст DestinyPixel. Примечание называет вид текста и не удостоверяет успех или неудачу плана."],
        ["Обычай храма остаётся обычаем этого храма", "Открытые страницы описывают гадание на палочках по-разному. Путеводитель Совета по туризму Гонконга по храму Вонг Тай Син говорит, что посетители трясут бамбуковый цилиндр, пока не выпадет палочка, а затем несут её к лавкам на территории для толкования кау чим. Страница описывает практику оживлённого храма и не публикует запрет на повтор. Колонка настоятеля Сик Сик Юэн Ли Яохуэя (李耀輝, 義覺) в Wen Wei Po от 27 января 2026 года подробнее передаёт порядок именно этого храма: верующие берут тубу из ста палочек, задают одно дело и трясут, пока одна палочка не покинет тубу. В колонке сказано: одна палочка — одно дело. Некоторые затем бросают лунные блоки и переписывают номер только после подтверждающего броска. Бумажные листки там выдают бесплатно по номеру. Названные степени — 上上, 上吉, 中吉, 中平 и 下下; толкование предлагается соотносить с обстоятельствами человека, временем, местом и состоянием духа. Китайская статья Википедии о 求籤 пишет, что в Гуандуне и Гонконге обычно описывают тряску до выпадения палочки, а во многих храмах Фуцзяни и Тайваня палочку подтверждают блоками и возвращают в тубу, если бросок не подтвердил её. В части японских святилищ неблагоприятный листок оставляют на стойке. Там же сказано, что пометки удачи не абсолютны и храмы могут расходиться в толковании. Английская статья Kau chim добавляет: во многих стаканах сто палочек, другие наборы отличаются, а несколько выпавших сразу часто не засчитывают. В этих описаниях повтор нужен, чтобы подтвердить выбор. Непонравившийся стих и бросок, который ещё не подтвердил палочку, — разные события. Оставляйте опубликованный порядок каждого храма при этом храме."],
        ["Что на самом деле делает кнопка выбора", "На странице пять коллекций: Гуаньинь, Гуаньди, Юэлао, Пять богов богатства и Вонг Тай Син. У Гуаньинь, Гуаньди и Вонг Тай Сина номера от 1 до 100. У Юэлао и Пяти богов богатства — от 1 до 60. Это диапазоны продукта, а не утверждение, что каждый храм печатает те же книги. После нажатия страница коротко показывает тряску, затем выбирает целое число в выбранном диапазоне функцией случайных чисел браузера crypto.getRandomValues. Введённый вопрос не участвует в выборе номера. Вопрос можно записать или оставить поле пустым и держать его про себя. Темы — Карьера, Любовь, Деньги, Семья, Сроки, Здоровье — задают чтению направление и не сдвигают номер. Пункт “Уже вытянули офлайн?” принимает целое число в том же диапазоне и открывает запись этой библиотеки. Поиск показывает нашу запись и не удостоверяет бумажный листок храма. Случайный выбор объясняет процедуру этой страницы. Он не доказывает, что храмовый оракул пуст, и не доказывает, что номер — сверхъестественный приговор. Повторное нажатие “Вытянуть снова” запускает ту же процедуру ещё раз."],
        ["Сначала примечание об источнике, потом древность слов", "Результат показывает степень, заголовок, текст знака, простое чтение, практический совет и примечание об источнике. Примечание — подпись слоя. У части номеров есть вручную введённые традиционные образцы; их примечания говорят, что тема традиционная, а храмовые формулировки могут различаться. Многие номера Гуаньди и многие номера Вонг Тай Сина в китайской версии несут классический китайский текст. У таких записей Вонг Тай Сина примечание может сказать, что присутствует образец традиционного стиха, а современное простое чтение написано DestinyPixel. В английской и русской версиях номер с проверенным китайским стихом может показать локализованное чтение, а примечание сообщит, что китайский стих находится в китайской версии. Остальные номера используют современный символический текст сайта. Их примечания говорят, что формулировка нормализована или символическая, что точные храмовые стихи ещё сверяются, или что строка не является дословным храмовым текстом этого номера. Примечания коллекции богатства также говорят, что это не единый канонический храмовый набор. Сгенерированные записи чередуют метки каталога: Great Blessing, Good, Steady, Blocked и Wait по-английски и 上吉, 中吉, 中平, 小阻, 待时 по-китайски. Образцы и классические записи могут нести другие слова степени, в том числе суровые. Все эти слова — метки каталога. Эта статья не перепечатывает нумерованные храмовые стихи. Откройте полученный результат и прочитайте примечание рядом с текстом."],
        ["Необязательный ИИ объясняет уже выпавшую палочку", "После результата карточка предлагает “Толковать мой вопрос”; в английской версии это “Interpret with my question”, по-китайски — 「结合问题解读」. Запрос уходит на /api/sticks/interpret вместе с коллекцией, номером, знаком уже на экране, выбранной темой и текстом вопроса; вопрос может быть пустым. Модели поручено объяснить этот знак в связи с вопросом. Ей не поручено выбрать новую палочку. Те же указания просят не гарантировать выздоровление, успех в суде, инвестиционную прибыль, беременность, смерть, бедствие или фиксированную судьбу. Если запрос не удался, страница показывает простое чтение, уже напечатанное на карточке. Во время загрузки интерфейс называет DeepSeek. Готовый абзац — четвёртый слой: комментарий к показанной записи и вашему вопросу. Это не толкователь во дворе храма и не заново найденный исторический стих. Если примечание говорит, что стих ещё сверяется, читайте текст ИИ как размышление о номере, теме и принесённом вопросе."],
        ["Авторский сценарий: тревога из-за рабочего предложения", "Эта сцена — авторский редакционный пример. Это не храмовое предписание и не сообщение от работодателя. Письменное предложение лежит на столе, недельные часы ещё туманны, а метка читается как Blocked или 小阻. Один порыв — отказаться сегодня вечером. Другой — нажимать “Вытянуть снова”, пока метка не станет добрее. Запишите вопрос, на который человек способен ответить: какие три обязанности и какие недельные часы указаны в письменных условиях? Отправьте его контакту по найму и назначьте день, когда перечитаете ответ. Жребий мог помочь назвать тревогу. Ответ показывает, менять ли план. Если позже вытянете снова, дайте этому выбору новый вопрос об уже полученном ответе. Руководство о том, как задавать вопрос палочкам, показывает, как удержать следующий вопрос таким же узким."],
        ["Авторский сценарий: тревога из-за уже купленной поездки", "Эта сцена — авторский редакционный пример. Это не предупреждение святилища о путешествии. Поездка уже оплачена, образы звучат как задержка, и отмена кажется самым безопасным чтением сурового жребия. Отделите бронь от настроения. До повторного выбора проверьте один факт: действительны ли паспорта, достаточно ли длинна первая пересадка по текущему расписанию или кто местный контакт, если поезд сдвинется. Если расписание держится, тревожный образ ещё не стал причиной отмены. Если пересадка слишком короткая, план меняют из-за расписания. Позднейший выбор, если он всё ещё нужен, может спросить, что делать с только что подтверждённой пересадкой. Руководство о номерах и изданиях объясняет, почему храмовый листок и эта страница могут совпасть по номеру и разойтись по тексту. Английская учебная страница о Гуаньинь проходит ту же привычку читать примечание об источнике для этой коллекции."],
      ], action: { label: "Открыть жребий и прочитать источник", href: "/sticks?locale=ru" },
    },
  },
];

function translation(entry: Entry, locale: "en" | "zh" | "ru"): JournalTranslation {
  const copy = entry[locale];
  const sourceLabels: Record<string, Record<"en" | "zh" | "ru", string>> = {
    "https://www.hko.gov.hk/en/gts/time/stemsandbranches.htm": { en: "Hong Kong Observatory: stems and branches", zh: "香港天文台：天干与地支", ru: "Гонконгская обсерватория: стволы и ветви" },
    "https://www.iana.org/time-zones": { en: "IANA: Time Zone Database", zh: "IANA：时区数据库", ru: "IANA: база часовых поясов" },
    "/compatibility": { en: "DestinyPixel: current comparison method", zh: "DestinyPixel：当前配对方法", ru: "DestinyPixel: метод сравнения" },
    "/sticks": { en: "DestinyPixel: collections and source notes", zh: "DestinyPixel：签系与来源说明", ru: "DestinyPixel: коллекции и источники" },
    "/learn/guanyin-fortune-sticks": { en: "Guanyin collection guide", zh: "观音签资料范围（英文）", ru: "Коллекция Гуаньинь (на английском)" },
    "https://www.discoverhongkong.com/eng/place-to-go/travel.guide-wong-tai-sin-temple.html": { en: "Hong Kong Tourism Board: Wong Tai Sin Temple and kau cim", zh: "香港旅游发展局：黄大仙祠与求签", ru: "Совет по туризму Гонконга: храм Вонг Тай Син и кау чим" },
    "https://www.tkww.hk/epaper/view/newsDetail/2015847422080716800.html": { en: "Wen Wei Po, 27 January 2026: Sik Sik Yuen abbot on Wong Tai Sin sticks", zh: "香港文汇报2026年1月27日：啬色园监院谈黄大仙灵签", ru: "Wen Wei Po, 27 января 2026: настоятель Сик Сик Юэн о жребиях Вонг Тай Сина" },
    "https://zh.wikipedia.org/wiki/%E6%B1%82%E7%B1%A4": { en: "Chinese Wikipedia: 求籤, regional customs", zh: "中文维基百科：求签（各地习俗不同）", ru: "Китайская Википедия: цю цянь, разные местные обычаи" },
    "https://en.wikipedia.org/wiki/Kau_chim": { en: "English Wikipedia: Kau chim", zh: "英文维基百科：Kau chim", ru: "Английская Википедия: Kau chim" },
    "/journal/how-to-ask-fortune-sticks": { en: "How to ask a fortune-stick question", zh: "求签怎么问问题", ru: "Как задать вопрос оракулу палочек" },
    "/journal/fortune-stick-number-and-edition": { en: "Same number, different edition", zh: "同一个签号，为什么签文不同", ru: "Один номер, разные тексты" },
    "/journal/prepare-birth-date-time-place": { en: "Prepare your birth details", zh: "准备出生日期、时间与地点", ru: "Подготовка данных рождения" },
  };
  return { ...copy, sections: copy.sections.map(([title, paragraph], index) => ({
    id: `step-${index + 1}`, title, paragraphs: [paragraph],
    ...(index === copy.sections.length - 1 ? { sources: entry.sources.map(source => ({ ...source, label: sourceLabels[source.href]?.[locale] ?? source.label, href: source.href.startsWith("/journal/") || source.href === "/compatibility" || source.href === "/sticks" ? `${source.href}${locale === "en" ? "" : `?locale=${locale}`}` : source.href })) } : {}),
  })) };
}

export const searchGrowthArticles: JournalSourceArticle[] = entries.map(entry => ({
  slug: entry.slug, relatedSlug: entry.relatedSlug, publishedAt: entry.publishedAt ?? "2026-09-20", updatedAt: entry.updatedAt ?? "2026-09-20",
  translations: { en: translation(entry, "en"), zh: translation(entry, "zh") },
}));
export const searchGrowthRussian: Record<string, JournalTranslation> = Object.fromEntries(entries.map(entry => [entry.slug, translation(entry, "ru")]));
