import type { JournalSourceArticle, JournalTranslation } from "./journal";

type Edition = {
  title: string; description: string; topic: string; introduction: string; takeaway: string;
  sections: [string, string][]; action: { label: string; href: string };
};
type Entry = { slug: string; relatedSlug: string; publishedAt?: string; updatedAt?: string; sources: { label: string; href: string }[]; en: Edition; zh: Edition; ru: Edition };

// Original, task-focused guides. Section order is shared across complete editions.
const entries: Entry[] = [
  {
    slug: "bazi-vs-chinese-zodiac-compatibility", relatedSlug: "compatibility-without-birth-time",
    sources: [{ label: "Hong Kong Observatory · 干支与八字 · Небесные стволы и земные ветви", href: "https://www.hko.gov.hk/en/gts/time/stemsandbranches.htm" }, { label: "DestinyPixel · Compatibility method / 配对方法 / Метод сравнения", href: "/compatibility" }],
    en: {
      title: "BaZi vs Chinese zodiac compatibility: beyond your birth-year animal",
      description: "Same zodiac animal, different relationship styles? Compare year-sign matching with Four Pillars, five elements and DestinyPixel’s free compatibility tool.",
      topic: "Love & the five elements",
      introduction: "You look up two Chinese zodiac animals and find a perfect match. Yet one of you wants to settle every disagreement immediately, while the other needs a quiet evening first. Did you read the wrong table? A year-animal pairing describes a very small part of the system. This guide separates the calendar, the symbolic interpretation and the conversation you can actually have together, without asking a score to decide your relationship.",
      takeaway: "A year animal is one calendar label. BaZi uses year, month, day and hour. More detail makes a comparison more specific, but does not make it a proven measure of love.",
      sections: [
        ["What does a Chinese zodiac compatibility table compare?", "A familiar zodiac chart starts with the animal associated with a birth year and compares it with another animal. It is easy to remember and easy to share, which makes it a useful cultural introduction. But two people assigned the same animal can have different birth months, days and hours. A year-based table cannot distinguish those inputs. Near a calendar boundary, also check which convention the calculator follows rather than choosing a year from a generic poster. DestinyPixel’s full birth calculation uses the start of spring, LiChun, for its year boundary; that should not be silently confused with Lunar New Year."],
        ["What does BaZi add?", "BaZi means eight characters: a stem and a branch for each of four calendar pillars. The Hong Kong Observatory describes how these pairs are used for years, months, days and hours, and how they form a sixty-pair cycle. That is evidence for the calendar structure, not for predictions about a couple. In a reading, the day stem becomes a reference point for discussing the five elements. Looking at both complete sets can reveal different symbolic patterns despite identical year animals. It still cannot tell you whether someone keeps promises, listens during conflict or shares your plans for the future."],
        ["How to read supporting and controlling elements", "Wood, fire, earth, metal and water form a traditional vocabulary of relationships. A supporting relationship can become a prompt about giving and receiving; a controlling relationship can become a prompt about boundaries or friction. Avoid translating these straight into good partner and bad partner. For example, one person may experience frequent advice as care while the other hears constant correction. The useful next question is what each person actually needs: encouragement, practical help or room to decide. This is a way to explore a metaphor together, not a claim that an element caused either person’s behavior or that conflict is inevitable."],
        ["Where do the sixty animal cards fit?", "DestinyPixel’s sixty animal portraits give the calendar combinations memorable visual identities. The names, artwork and character stories are an original presentation, not sixty ancient personality diagnoses. Read your own card first and choose one description that fits a real incident, then one that does not. Invite your partner to do the same instead of announcing what their card means about them. Two people can identify with similar images while expressing affection very differently. The cards work best as an opening to that discussion; they are not additional evidence that a relationship is destined, and their illustrations do not add hidden points to the score."],
        ["What the free comparison actually calculates", "The current tool combines a BaZi element comparison with selected planetary comparisons. Its overall index uses thirty percent BaZi and seventy percent planetary comparisons, then presents the result on an editorial scale from sixty to one hundred. That number is not a measured probability of staying together. The page also compares personality, communication, affection and everyday rhythm, and shows the two animal portraits. AI can explain the supplied result but does not choose the score. This is not a complete traditional marriage assessment or a full Western synastry reading: it does not calculate houses, rising signs or a marriage date."],
        ["Turn the reading into one useful conversation", "Both people should check their recorded date, time and selected birthplace before comparing. Then pick one small, observable question rather than trying to settle your entire future: after a difficult workday, do you want questions, company or quiet first? Each person answers before looking back at the reading. Agree on one action to try, such as saying when you will return to a paused conversation. A week later, discuss whether that helped. If the result does not fit, say so and keep the real experience. The value of this exercise is a clearer conversation, not persuading either person to accept a label."],
      ], action: { label: "Compare your two birth charts free", href: "/compatibility" },
    },
    zh: {
      title: "生肖配对和八字合婚有什么区别？从属相看到五行与相处方式",
      description: "同样的生肖，为什么相处模式不同？讲清生肖配对、四柱八字、五行关系与60动物卡的区别，并了解免费情感匹配的实际计算范围。",
      topic: "感情与五行", introduction: "查生肖时明明写着“很般配”，真正相处却是一个人想立刻讲清楚，另一个人想先安静一晚。是配对表错了，还是你们不够了解彼此？年生肖只提供很小的一部分信息。这篇指南把历法、象征解读和两个人真正能讨论的事情分开，让配对结果成为交流的起点。",
      takeaway: "生肖配对通常只看出生年的动物；八字使用年、月、日、时四柱。信息更具体，不等于已经科学验证了感情好坏。",
      sections: [
        ["生肖配对表到底在比较什么？", "常见配对表从出生年的动物出发，与另一个动物作比较。它好记、好分享，适合作为文化入口，却区分不了同属一个生肖、但出生月份、日期和时辰不同的人。处在换年边界附近时，还要先确认采用什么历法规则，不能只照一张年份海报选属相。本站完整出生计算以立春作为年柱边界，不应与农历正月初一混用。"],
        ["八字比生肖多看了什么？", "四柱中的每一柱都有一个天干和一个地支，年、月、日、时合起来就是八个字。香港天文台介绍了这些干支如何用于纪年、纪月、纪日和纪时，以及六十组合的循环；这支持历法结构的说明，不是对感情预测的验证。解读时，日干可以作为理解五行关系的参照。同生肖的人可能有不同的组合，但这些组合不能替你确认一个人是否守信、是否愿意倾听、是否与你有一致的生活计划。"],
        ["五行相生相克，怎样读成相处问题？", "木、火、土、金、水之间的关系，是传统象征语言。“相生”可以引出给予与接受的话题，“相克”可以引出边界与摩擦，但不能直接翻译成好伴侣与坏伴侣。比如，一个人不断提建议，自己觉得是在关心，对方却觉得总被纠正。这时真正有用的问题是：你此刻需要鼓励、实际帮助，还是自己决定的空间？这是借助比喻讨论具体体验，并不是说某种元素造成了这些行为。"],
        ["60动物卡在这里起什么作用？", "本站把六十种历法组合设计成具有记忆点的动物意象。名字、画面和角色故事属于原创呈现，不是六十种古代人格诊断。可以先各自选出卡片里一条符合真实经历的描述，再选一条不符合的，让对方自己表达，不要替对方宣布“你就是这样的人”。卡片帮助打开话题，不能证明命定关系，图画也不会在分数里额外加上看不见的权重。"],
        ["免费匹配现在怎么算？", "当前工具把八字元素比较与部分行星关系结合，总体指标中八字占30%，行星比较占70%，再呈现为60—100的编辑尺度。它不是维持关系的成功概率。结果还提供性格、沟通、感情表达与日常节奏的比较，以及双方动物意象。AI解释已经算出的结果，不决定分数。它不等于完整传统合婚或完整西方合盘，也不计算宫位、上升星座和婚期。"],
        ["把结果变成一次有用的对话", "先由双方核对出生日期、记录时间与出生城市，再选一个可以观察的小问题：工作不顺回家时，你更希望有人问、有人陪，还是先安静？各自先回答，再回看结果。约定一件可以试行的事，例如暂停争论时明确什么时候回来继续说。一周后讨论有没有帮助。描述不符合就保留不同意见；重点是让沟通更清楚，而不是让任何一方服从标签。"],
      ], action: { label: "免费比较两个人的出生图谱", href: "/compatibility?locale=zh" },
    },
    ru: {
      title: "Совместимость по бацзы и китайскому зодиаку: что меняется кроме животного года",
      description: "Почему одинаковые знаки не означают одинаковые отношения: четыре столпа, пять элементов, 60 животных и границы бесплатного сравнения DestinyPixel.",
      topic: "Отношения и пять элементов", introduction: "Таблица обещает прекрасное сочетание знаков, но после ссоры одному хочется немедленно поговорить, а другому нужен тихий вечер. Ошибка ли это? Животное года описывает лишь небольшую часть символической системы. Разберём отдельно календарь, интерпретацию и разговор, который действительно можно провести вдвоём, не поручая оценке решать судьбу отношений.",
      takeaway: "Животное года — одна календарная метка. Бацзы использует год, месяц, день и час. Более подробное сравнение не становится от этого доказанным измерением любви.",
      sections: [
        ["Что сравнивает таблица животных года?", "Обычная таблица сопоставляет животных двух лет рождения. Её легко запомнить, но она не различает людей одного знака с разными месяцами, днями и часами рождения. Вблизи смены года важно уточнять календарное правило, а не брать знак с общего плаката. В полном расчёте DestinyPixel границей годового столпа служит начало весны Личунь; это не то же самое, что первый день лунного нового года."],
        ["Что добавляют четыре столпа?", "Каждый столп содержит небесный ствол и земную ветвь: вместе год, месяц, день и час дают восемь знаков. Гонконгская обсерватория описывает эти календарные пары и цикл из шестидесяти сочетаний. Это источник о календаре, а не доказательство предсказаний. Ствол дня служит ориентиром в символическом чтении пяти элементов. Но даже разные сочетания не показывают, держит ли человек слово, умеет ли слушать и совпадают ли ваши жизненные планы."],
        ["Как понимать поддержку и сдерживание элементов?", "Дерево, огонь, земля, металл и вода образуют традиционный язык отношений. Поддержка может предложить тему отдачи и принятия, сдерживание — тему границ. Это не деление на хороших и плохих партнёров. Один даёт советы из заботы, другой слышит постоянные исправления. Спросите, что сейчас нужно: поддержка, конкретная помощь или свобода решения. Здесь метафора помогает обсудить опыт; она не доказывает, что элемент вызвал поведение или сделал конфликт неизбежным."],
        ["Зачем нужны шестьдесят животных?", "Названия, изображения и характеры карт DestinyPixel — авторское оформление календарных сочетаний, а не древняя диагностика личности. Каждый может выбрать одно описание, совпадающее с реальным случаем, и одно неподходящее. Не назначайте партнёру характер за него. Даже похожие образы не означают одинаковый способ проявлять нежность. Карты открывают разговор, не доказывают предопределённость союза и не добавляют тайных баллов к оценке."],
        ["Что вычисляет бесплатный инструмент?", "Общий показатель сочетает сравнение элементов бацзы с отдельными планетными отношениями: тридцать процентов и семьдесят процентов соответственно. Шкала от шестидесяти до ста — редакционный индекс, не вероятность успешного брака. Есть сравнения характера, общения, проявления чувств и повседневного ритма. ИИ объясняет готовый результат, но не выставляет балл. Это не полная традиционная оценка брака и не полная западная синастрия: дома, асценденты и дата свадьбы не рассчитываются."],
        ["Как перейти от чтения к разговору?", "Сначала оба проверьте дату, записанное время и город рождения. Затем независимо ответьте на небольшой вопрос: после тяжёлого рабочего дня вам нужны вопросы, компания или тишина? Сравните ответы с чтением и договоритесь об одном действии, например заранее говорить, когда вернётесь к прерванному разговору. Через неделю обсудите результат. Если описание не подходит, сохраните своё несогласие. Цель — яснее понимать друг друга, а не подчиняться ярлыку."],
      ], action: { label: "Бесплатно сравнить две карты", href: "/compatibility?locale=ru" },
    },
  },
  {
    slug: "compatibility-without-birth-time", relatedSlug: "bazi-vs-chinese-zodiac-compatibility",
    sources: [{ label: "IANA · Time Zone Database / 时区资料 / База часовых поясов", href: "https://www.iana.org/time-zones" }, { label: "DestinyPixel · Birth details / 出生资料 / Данные рождения", href: "/journal/prepare-birth-date-time-place" }],
    en: {
      title: "Can you check BaZi compatibility without a birth time?",
      description: "No birth time? Learn what a birthday-only reading can show, why guessing noon changes the chart, and which free DestinyPixel tools you can use instead.",
      topic: "Before you compare", introduction: "You know both birthdays, but only one birth time. It is tempting to enter noon and get on with the reading, especially when the form will not continue without it. The problem is that a convenient placeholder can produce a very confident-looking answer. Here is how to explore what you do know, keep missing information visible and avoid presenting an estimate as something you found in a birth record.",
      takeaway: "The current compatibility form needs both recorded birth times and supported birth cities. A birthday-only card is a narrower starting point, not a substitute for the missing hour.",
      sections: [
        ["What changes when the hour is missing?", "The hour is one of the four BaZi pillars. An unknown time therefore leaves part of the calendar structure unresolved. Planetary positions also depend on the instant being calculated; their sensitivity is not identical, and a birthday is not a complete instant without time and place. More importantly, you cannot recover missing information just by reading a persuasive paragraph. A chart that feels familiar is not proof that the selected hour was right. Separate the question of which input is recorded from the question of whether an interpretation is interesting, and do not let the second question answer the first."],
        ["Why not simply enter 12:00?", "Noon is a convention some people use for an explicitly limited exploration. It is not a recovered birth time, and the current DestinyPixel couple form does not offer a dedicated unknown-time mode. Filling noon into its required field would calculate a chart for that assumed time. The interface would not make the missing information disappear. If you are comparing possibilities privately, label every assumption and avoid saving a guessed chart as an accurate personal record. Do not choose the time that gives the most flattering score, since that changes the question from understanding the input to selecting the answer you wanted."],
        ["Where can you look for a better record?", "If available, start with a birth certificate, a contemporaneous hospital record or a family note made around the birth. You do not need to upload private documents to DestinyPixel. Copy the local clock time and write down its source separately. If a relative remembers a range, keep the range: between seven and eight is different from an exact seven thirty. Also confirm whether the written date is Gregorian or lunar and whether an AM or PM label was omitted. A time that looks precise may still have been rounded, so keep uncertainty visible instead of adding invented minutes."],
        ["Keep time attached to its original place", "Use the birth city and its local recorded time, not your current city or the time displayed on your phone today. Historical clock rules and daylight saving can change the conversion into a single instant. The IANA Time Zone Database documents time-zone histories; it does not certify an individual birth record. DestinyPixel applies its supported city’s time zone and separate solar-time correction internally, so do not pre-convert the input to Beijing time or adjust it a second time yourself. If the form reports a repeated or nonexistent clock time, investigate that record rather than changing the hour to silence the message."],
        ["What can you explore with only a date?", "The free Day Pillar card accepts a birthday and offers a date-based calendar character. It provides a smaller introduction to the sixty portraits without pretending to supply the missing hour or a complete couple comparison. Treat that as a date-only starting point; a birth close to a day boundary needs extra care when comparing systems that use different clock or solar-time conventions. You can also use the question-based fortune-stick experience without either partner’s birth data. For a relationship question, focus on something you can discuss or observe rather than asking the tool to reveal your partner’s private thoughts."],
        ["A practical choice for two people", "Make a short note for each person: verified date, verified time or remembered range, birthplace and unresolved questions. If both records are clear and the cities are supported, use the free compatibility form. If an hour remains unknown, read your date-based cards separately and compare actual habits: how do you ask for help, show affection or ask for space? Those questions are available immediately and do not depend on a missing certificate. Return to the fuller comparison when the input improves. A smaller honest reading is more useful than a precise-looking result whose most important assumptions have been forgotten."],
      ], action: { label: "Start with a free birthday card", href: "/day-pillar" },
    },
    zh: {
      title: "不知道出生时间，能做八字合婚吗？先分清可查与不可猜的部分",
      description: "只有生日、没有时辰怎么办？解释八字配对的输入要求、为什么不能随便填中午，以及日柱卡和抽签能提供哪些免费替代体验。",
      topic: "配对前的准备", introduction: "两个人的生日都知道，却只有一个人记得出生时间。看到表单必须填时辰，很容易想：先写中午十二点看看吧。问题是，一个随手填入的时间，也可能得到一份看起来非常肯定的结果。先分清哪些资料有记录、哪些仍然不确定，才能知道自己看到的究竟是什么。",
      takeaway: "当前情感匹配需要双方记录中的出生时间及支持的出生城市。只有生日时，可以从日柱卡开始，但不能把它当成完整合婚。",
      sections: [
        ["缺少时辰，会少掉什么？", "时柱是八字四柱的一部分，缺少出生时间就有一部分历法结构无法确定。行星位置也与具体时刻有关，各行星对时间的敏感程度并不相同。更关键的是，一段读起来很像你的文字，不能倒过来证明某个时辰正确。要把“输入来自什么记录”和“解释是否有启发”分开，不能让后者替前者作答。"],
        ["为什么不建议直接填12:00？", "中午可以被明确标记为一种探索假设，却不是找回的出生时间。当前本站双人匹配没有独立的“未知时间”模式，填入中午就会按中午计算，缺失的信息并不会因此消失。即使私下比较几种可能，也应注明假设，不要把猜测存成准确出生记录。尤其不要挑分数最高的那个时间，那是在选择想要的答案，而不是核实资料。"],
        ["可以去哪里找更可靠的时间？", "如果能找到，先看出生证明、当时的医院记录或同期家庭笔记，不必把私人文件上传到本站。抄下原记录中的当地时间，另外记住来源。亲属只记得七点到八点，就保留这个范围，不要补成精确的七点半。同时确认日期用的是公历还是农历，以及有没有漏掉上午、下午。精确到分钟的数字也可能经过取整，不要人为增加确定性。"],
        ["出生时间必须和出生地一起保留", "填写出生地当时的本地钟表时间，不是现在居住城市的时间。历史时区和夏令时会影响具体时刻的换算；IANA时区数据库记录地区时区历史，但不为某个人的出生证明作认证。本站会根据支持的城市处理时区并单独进行太阳时修正，不要先转北京时间或自行重复校时。遇到重复或不存在的钟表时刻提示，应核查记录，不要随意改小时绕过提示。"],
        ["只有日期，现在可以玩什么？", "免费日柱卡接受生日，给出按日期得到的历法意象，是认识六十种动物角色的较小入口，不会补出缺失的时柱，也不等于双人合婚。出生在换日边界附近时，还要注意不同系统的钟表时间和太阳时约定。也可以使用不要求生日的抽签体验，把感情问题放在自己能观察、能沟通的事情上，而不是让工具猜测对方没说出口的想法。"],
        ["两个人可以这样安排下一步", "分别写清楚：已核实的生日、准确时间或记忆范围、出生地，以及还不确定的地方。双方记录清楚且城市受支持，再使用匹配表单；时间仍未知，就先各自读日柱卡，讨论怎样求助、怎样表达关心、怎样需要独处。这些对话不需要等一张证明。资料更完整后再看完整比较，通常比忘记假设、只记住分数更有帮助。"],
      ], action: { label: "先领取免费日柱卡", href: "/day-pillar?locale=zh" },
    },
    ru: {
      title: "Можно ли сравнить бацзы, если время рождения неизвестно?",
      description: "Что доступно по одной дате, почему полдень не заменяет неизвестное время и с каких бесплатных инструментов DestinyPixel начать.",
      topic: "Подготовка к сравнению", introduction: "Вы знаете обе даты рождения, но время известно лишь для одного человека. Хочется вписать полдень и продолжить. Однако удобная заглушка способна дать очень уверенно выглядящий результат. Разберём, что можно исследовать сейчас, как сохранить неизвестное неизвестным и не выдать предположение за запись из документа.",
      takeaway: "Нынешняя форма совместимости требует время рождения обоих людей и поддерживаемые города. Карта по дате — более узкое знакомство с системой, а не замена неизвестному часу.",
      sections: [
        ["Что теряется без часа?", "Час — один из четырёх столпов бацзы, поэтому часть структуры остаётся неопределённой. Положения планет тоже зависят от момента расчёта, хотя чувствительность у них различается. Убедительный текст не восстанавливает недостающие сведения. Даже если описание кажется знакомым, это не доказывает правильность выбранного часа. Отделяйте происхождение исходных данных от интереса к интерпретации."],
        ["Почему нельзя просто поставить 12:00?", "Полдень может быть явно обозначенным предположением для ограниченного исследования, но не найденным временем рождения. У текущей формы DestinyPixel нет специального режима неизвестного времени: введённый полдень будет использован как время расчёта. При личном сравнении вариантов отмечайте каждую гипотезу и не сохраняйте её как точную запись. Не выбирайте час по самому приятному баллу: так вы подбираете желаемый ответ, а не проверяете данные."],
        ["Где искать более надёжную запись?", "Если доступны, проверьте свидетельство, больничную запись или семейную заметку того времени. Загружать личные документы на сайт не требуется. Сохраните местное время и отдельно его источник. Воспоминание «между семью и восемью» не превращайте в точные семь тридцать. Уточните календарь, утро или вечер и возможное округление: наличие минут в записи ещё не гарантирует точности."],
        ["Сохраняйте связь времени с местом", "Используйте местное время в городе рождения, а не нынешнее место жительства. Исторические часовые пояса и летнее время влияют на перевод в конкретный момент. База IANA описывает историю часовых поясов, но не удостоверяет личный документ. Сайт сам применяет правила поддерживаемого города и отдельную поправку солнечного времени. Не переводите данные заранее в пекинское время. При сообщении о повторяющемся или несуществующем времени исследуйте запись, а не меняйте час ради прохождения формы."],
        ["Что доступно по одной дате?", "Бесплатная карта столпа дня принимает дату и даёт календарный образ, знакомя с шестьюдесятью персонажами. Она не восстанавливает час и не заменяет сравнение пары. При рождении около границы суток особенно важны различия между календарными и солнечными правилами разных систем. Оракул палочек вообще не требует данных рождения: вопрос об отношениях можно связать с наблюдаемой ситуацией, а не с попыткой узнать тайные мысли партнёра."],
        ["Как выбрать следующий шаг вдвоём?", "Запишите для каждого подтверждённую дату, время или известный диапазон, место и оставшиеся вопросы. Если данные ясны и города поддерживаются, переходите к сравнению. Если час неизвестен, прочитайте карты дня отдельно и обсудите реальные привычки: как просите помощи, проявляете заботу и обозначаете потребность в тишине. Такой разговор возможен уже сейчас. К подробному расчёту вернитесь, когда появятся более полные сведения."],
      ], action: { label: "Карта по дате рождения (на английском)", href: "/day-pillar" },
    },
  },
  {
    slug: "how-to-ask-fortune-sticks", relatedSlug: "fortune-stick-number-and-edition",
    sources: [{ label: "DestinyPixel · Fortune sticks / 抽签使用说明 / Оракул палочек", href: "/sticks" }, { label: "DestinyPixel · Guanyin collection guide / 观音签指南 / Коллекция Гуаньинь", href: "/learn/guanyin-fortune-sticks" }],
    en: {
      title: "How to ask a fortune-stick question: love, work and change",
      description: "Turn a vague fortune-stick question into a useful one. Practical love and career examples, a simple draw routine, and how to turn a reading into a next step.",
      topic: "A question worth bringing", introduction: "You open the oracle and suddenly cannot decide what to ask. Will everything work out? Do they love me? Is this the right path? Those questions carry real feelings, but they give a symbolic reading very little context. You do not need special words or a perfect ritual. Start with the situation in front of you, one uncertainty and something you can actually notice or do after reading.",
      takeaway: "A useful question names one situation and one next step. The result can prompt reflection; it cannot supply facts about another person or guarantee an outcome.",
      sections: [
        ["Start with one situation, not your whole future", "Write down what has happened in a plain sentence before you draw: we keep postponing a conversation about moving, or I have an offer but have not clarified the working hours. Then ask what deserves your attention next. This gives you a way to read the imagery without stretching every line to fit everything in your life. It also helps you notice when an interpretation has wandered away from the question. You can keep identifying details out of the text; names, addresses and private messages are usually unnecessary for this kind of reflection. Specific does not have to mean personally revealing."],
        ["For love: move from mind-reading to conversation", "Instead of asking whether someone secretly loves you, try: what do I need to clarify before asking where this relationship is going? Or: how can I explain my need for reassurance without speaking for my partner? These versions do not promise a hidden answer. They return attention to what you can say, ask and observe. For example, write the sentence you have been avoiding, then check whether it invites an honest response or already contains an accusation. A reading cannot establish someone else’s feelings, loyalty or intentions. Their own words and consistent actions remain the evidence you need in the relationship."],
        ["For work: identify the missing fact", "A question such as should I accept this role can feel impossible because several questions are bundled together. Try asking what you need to clarify before deciding. After the reading, list the concrete facts still missing: expected hours, responsibilities, reporting arrangements or how success will be assessed. Choose one fact to obtain from the relevant person or document. The symbolic text may help you articulate a concern, but it cannot verify an employer’s promises or calculate whether an offer is financially suitable. Keep the actual decision attached to real terms and your own circumstances rather than treating an encouraging phrase as a recommendation."],
        ["For change: make the next step small enough to see", "When everything feels unsettled, a question about the rest of your life invites an answer too large to use. Narrow it to a near-term action: what am I overlooking before I make this move, or what could help me test this new routine for a week? A useful outcome might be a conversation, a practical check or a small experiment. It need not be a dramatic revelation. Write down what you expect to learn and when you will review it. The point is to reduce the distance between reflection and action, while leaving room for new information to change your view."],
        ["Draw once, then read the source note", "On DestinyPixel, select a collection and topic, keep one question in mind and let the draw finish. You can then request an optional AI interpretation for the question. First read the numbered text and its source note: the site combines selected traditional material with modern symbolic readings rather than reproducing every temple edition. A traditional verse, a translation, a modern adaptation and an AI explanation are different layers. If you already hold a temple slip, check its named collection and wording before matching the number online. The next guide explains why the number alone is not enough to identify the text."],
        ["What if you dislike the answer?", "Pause before drawing again just to obtain a more comfortable line. Notice what bothered you and separate the image in the text from a fact about your situation. Write three short notes: the question I brought, the phrase that caught my attention and one thing I can check or discuss. You may decide that the reading is not useful; there is no need to force it to fit. Revisit the situation when circumstances change, rather than treating repeated draws as a way to make reality agree. This question-writing routine is DestinyPixel’s practical suggestion, not a claim about a universal temple ritual."],
      ], action: { label: "Bring one question to the oracle", href: "/sticks" },
    },
    zh: {
      title: "求签怎么问问题？感情、事业与人生变化的六个实用步骤",
      description: "不知道抽签时该问什么？用感情与工作实例，把模糊问题改成可沟通、可核实的问题，再把签文转成一个实际行动。",
      topic: "把问题说清楚", introduction: "打开签堂，反而不知道问什么：一切会好吗？他爱我吗？这条路对不对？这些问题背后有真实的情绪，却很难给象征性解读一个清楚的落点。不需要特别的措辞，先说清眼前的处境、一件不确定的事，以及看完以后能观察或做的一小步。",
      takeaway: "一次只问一个处境中的一个问题。签文可以引发思考，不能替你查明别人的想法，也不能保证结果。",
      sections: [
        ["先说一个处境，不问整个未来", "抽之前，用普通话写一句发生了什么，例如：我们一直拖着没谈搬家的事；我收到了工作邀请，但还不清楚工作时间。然后再问接下来该留意什么。这样读签时就不必把每一句硬套到整个人生，也更容易发现解释有没有偏离问题。描述具体，不代表要提交姓名、地址和私人聊天记录；通常不需要这些信息。"],
        ["问感情：从猜心转向沟通", "与其问“对方是不是偷偷爱我”，可以问：“谈关系下一步之前，我还需要说清什么？”或者：“我怎样表达需要被回应，而不替对方下结论？”这类问法把关注点放回能说、能问、能观察的事情。试着写下你一直没说出口的那句话，看看它是在邀请回答，还是已经包含指责。签文无法证实一个人的感情、忠诚和意图，这些仍需要对方自己的表达与持续行动。"],
        ["问事业：找出缺的那条信息", "“我该不该接受这份工作”常常把很多问题挤在一起。可以先问：“作决定前，我还需要核实什么？”看完后列出缺的信息：工作时间、职责、汇报关系，或评价表现的方式，再挑一项去向相关人员或文件求证。象征文字可以帮你说清担忧，但不能核实雇主承诺，也不能替你判断收入安排是否适合自己。实际选择还是要回到真实条件。"],
        ["问变化：把下一步缩小到看得见", "生活一团乱时，问一辈子往哪里走，很容易得到大到无法使用的回答。不如改成：“搬家前，我可能忽略了什么？”或“接下来一周，我怎样试行这个新习惯？”有用的结果可能只是一次谈话、一次核查或一个小实验，不必是惊天启示。写清想了解什么，以及什么时候回顾，让反思与行动接起来，也允许新信息改变自己的看法。"],
        ["抽一签，再看来源说明", "在本站选择签系与主题，带着一个问题完成抽签，再按需请求AI解释。先读签文旁的来源说明：本站包含部分传统资料和现代象征解读，不是每座庙本的完整复制。传统原文、译文、现代改写、AI解释是不同层次。如果手里已有寺庙签纸，应先确认签系与文字，再按号码查找。下一篇指南会说明为什么签号相同，内容也可能不同。"],
        ["不喜欢答案时，先不要急着重抽", "留意到底是哪句话让你不舒服，把象征画面与现实事实分开。记三件事：我带来的问题、吸引我注意的句子、接下来能核实或讨论的一件事。觉得没帮助，也可以承认不适合，不必强行对号入座。等处境有变化再回看，比反复抽到满意为止更容易看清自己在意什么。这套提问练习是本站的实用建议，不代表所有寺庙都采用同一种仪式。"],
      ], action: { label: "带着一个问题进入签堂", href: "/sticks?locale=zh" },
    },
    ru: {
      title: "Как задать вопрос оракулу палочек: любовь, работа и перемены",
      description: "Практические примеры вопросов об отношениях и работе: как уточнить ситуацию, прочитать источник текста и выбрать небольшой следующий шаг.",
      topic: "Сформулировать свой вопрос", introduction: "Вы открыли оракул и растерялись: всё ли получится, любит ли он меня, верно ли я иду? За этими словами стоят настоящие чувства, но символическому чтению не хватает контекста. Начните с одной ситуации, одной неопределённости и небольшого действия, которое возможно после чтения. Особые слова и идеальный ритуал не нужны.",
      takeaway: "Полезный вопрос описывает одну ситуацию и ближайший шаг. Чтение может помочь размышлению, но не раскрывает чужие мысли и не гарантирует результат.",
      sections: [
        ["Одна ситуация вместо всего будущего", "Сначала запишите, что произошло: вы откладываете разговор о переезде или получили предложение работы без ясного графика. Затем спросите, на что обратить внимание дальше. Так меньше соблазна подгонять каждую строку под всю жизнь и легче заметить, что интерпретация ушла в сторону. Конкретность не требует раскрывать личное: имена, адреса и переписка для такого размышления обычно не нужны."],
        ["В любви: от чтения мыслей к разговору", "Вместо вопроса о тайных чувствах попробуйте: что стоит прояснить перед разговором о будущем отношений? Или: как объяснить потребность в поддержке, не отвечая за партнёра? Запишите избегаемую фразу и проверьте, приглашает ли она ответить или уже обвиняет. Чтение не устанавливает верность, чувства или намерения другого человека. Его слова и последовательные поступки остаются необходимыми свидетельствами."],
        ["В работе: найдите недостающий факт", "Вопрос о принятии предложения часто объединяет сразу несколько неизвестных. Спросите, что нужно уточнить до решения. После чтения перечислите реальные пробелы: график, обязанности, кому подчиняться, как оценивается работа. Выберите один пункт и получите ответ у соответствующего человека или в документе. Символический текст помогает сформулировать тревогу, но не проверяет обещания работодателя и не определяет финансовую пригодность предложения."],
        ["В переменах: достаточно маленький шаг", "Когда всё неопределённо, вопрос обо всей жизни даёт слишком большой ответ. Лучше спросить, что вы упускаете перед переездом или как попробовать новый распорядок в течение недели. Результатом может стать разговор, проверка или небольшой эксперимент. Запишите, что хотите узнать и когда вернётесь к оценке. Это связывает размышление с действием и оставляет возможность изменить мнение после новых сведений."],
        ["Вытяните палочку и прочитайте источник", "На DestinyPixel выберите коллекцию и тему, сосредоточьтесь на одном вопросе и дождитесь окончания. Затем при желании запросите объяснение ИИ. Сначала прочитайте пометку об источнике: библиотека сочетает отдельные традиционные материалы с современными символическими текстами. Оригинал, перевод, адаптация и объяснение ИИ — разные слои. Если у вас храмовый листок, сверяйте название коллекции и слова, а не только номер."],
        ["Если ответ не понравился", "Не спешите тянуть снова ради приятной строки. Отметьте, что задело, и отделите образ от факта. Запишите исходный вопрос, привлёкшую внимание фразу и одно дело для проверки или обсуждения. Можно признать, что чтение вам не помогло: подгонять его не требуется. Возвращайтесь, когда ситуация изменится. Это практическое упражнение DestinyPixel, а не утверждение о едином ритуале всех храмов."],
      ], action: { label: "Перейти к оракулу палочек", href: "/sticks?locale=ru" },
    },
  },
  {
    slug: "fortune-stick-number-and-edition", relatedSlug: "how-to-ask-fortune-sticks",
    sources: [{ label: "DestinyPixel · Collection and source notes / 签系与来源说明 / Коллекции и источники", href: "/sticks" }, { label: "DestinyPixel · Guanyin lookup scope / 观音查签范围 / Поиск Гуаньинь", href: "/learn/guanyin-fortune-sticks" }],
    en: {
      title: "Why the same fortune-stick number can have different meanings",
      description: "Looking up a Guanyin or temple fortune-stick number? Check the collection, original wording and edition before trusting an online meaning or AI explanation.",
      topic: "Reading the source", introduction: "You leave a temple with a numbered slip, search the number online and find a poem that looks nothing like yours. A second page gives another meaning. Before worrying that you have received contradictory predictions, check whether the pages are even discussing the same text. A number identifies a position within a collection; by itself it does not establish the collection, the edition or the wording you are trying to understand.",
      takeaway: "Match the named collection and the actual verse before matching an interpretation. A familiar number is not enough to identify your temple slip.",
      sections: [
        ["Start with the name above the number", "Keep a note of the temple or publisher, the collection name and the number exactly as shown on your slip. A Guanyin collection and a Guandi collection should not be treated as interchangeable search results just because both contain a number thirty-three. If the slip has no clear collection name, keep the opening line and ask the place that issued it when possible. You can record this privately without uploading a photograph. The first task is identifying the text, not deciding whether the online interpretation sounds comforting. A page with a confident title can still belong to the wrong collection."],
        ["Compare words before comparing meanings", "Place the opening lines side by side. Are they the same verse, a translation of it or a completely different text? Check any title, accompanying story and source note as well. A modern paraphrase may intentionally use different words, but it should make clear what it is paraphrasing. If the opening lines do not match and the page supplies no edition information, stop short of claiming you have found the meaning of your exact slip. You can still read it as a separate symbolic text. Keeping those two uses distinct prevents a search result from silently replacing the document you actually received."],
        ["Separate four layers of a reading", "The original verse is the text being discussed. A translation carries it into another language and may need to explain images or wordplay. An adaptation can reshape the imagery for a contemporary audience. An interpretation then connects the text with a situation or question. These layers can all be useful, but they do different jobs. A newly written English reflection is not automatically a line-by-line translation of a Chinese poem. An AI response based on that reflection is another interpretive layer, not a newly discovered historical source. Look for clear labels before treating any of these versions as interchangeable evidence."],
        ["What DestinyPixel’s number lookup provides", "The site offers five collections, with one hundred entries each for Guanyin, Guandi and Wong Tai Sin, and sixty each for Yuelao and the Wealth Gods. These are the ranges in this product, not a statement that every temple uses these same collections. The library combines selected traditional material with modern symbolic texts. Its source notes distinguish the kind of material shown, and language editions may contain adaptations rather than matching translations. When you enter a number, you retrieve the corresponding entry in this library. That does not certify that the entry reproduces the exact paper slip you obtained elsewhere."],
        ["Can AI explain the slip anyway?", "An AI explanation is useful only within the material and context supplied to it. On this site the optional reading explains the displayed library entry in relation to your question. It does not authenticate your temple slip, consult an unseen original or inspect a photograph of the paper you are holding. If the displayed entry differs from your slip, its explanation belongs to that displayed entry. Avoid filling the gap by assuming that all versions must mean the same thing. For a specific temple edition, consult its own published explanation or ask the issuing temple about the actual wording when that is possible."],
        ["A simple lookup checklist", "Before searching, collect four details: collection name, number, opening line and named source if one is printed. In a search query, include the collection and an exact opening phrase rather than only the number. Once you find a candidate page, compare its wording and source label, then decide whether you want a translation, cultural context or a personal reflection. Those are different requests and may need different resources. If you cannot identify the edition, keep that uncertainty in your notes. You can still use a modern reading as a conversation prompt, while being honest that you have not established the meaning of the original temple document."],
      ], action: { label: "Explore the collections and source notes", href: "/sticks" },
    },
    zh: {
      title: "同一个签号，为什么签文不同？查观音灵签前先核对这四件事",
      description: "寺庙求到的签和网上解签不一样？先查签系、签号、原文与版本，区分传统签文、翻译、现代改写和AI解释。",
      topic: "读签也读来源", introduction: "从庙里带回一张签纸，按号码一搜，诗句却完全不同；再打开另一页，解释又变了。先别急着理解成互相矛盾的预言，要确认大家谈的是不是同一篇文字。签号标记的是某个签系内部的位置，单靠数字不能确定签系、版本和你手中那段文字。",
      takeaway: "先对签系和实际诗句，再对解释。号码一样，不足以证明网上找到的就是手里的那支签。",
      sections: [
        ["先看号码上方写的是什么", "记下寺庙或出版者、签系名称，以及签纸上的号码。观音签和关帝签即使都出现第三十三签，也不能当成同一个搜索结果。签系不清楚时，保留开头原句，条件允许就向发签处询问。可以自己记录，不必上传签纸照片。第一步是辨认文字，不是挑一个听起来舒服的解释；标题再肯定，也可能来自不同签系。"],
        ["先比较文字，再比较意思", "把签诗开头并排看：是同一首、翻译，还是完全不同的文字？也看看题名、典故和来源注记。现代转述可以换措辞，但应说明依据什么改写。如果开头不同，页面又没有版本信息，就不要声称已经找到了手中签纸的准确解释。它仍可以作为另一段象征文字来阅读，只是不能悄悄替换原来得到的那张签。"],
        ["把四个层次分清楚", "原文是被讨论的文字；翻译把它转成另一种语言，可能需要解释意象和双关；改写为现代读者重新组织表达；解读则把文字与具体问题联系起来。四者都可能有用，但作用不同。新写的一段英文反思不自动等于中文签诗的逐句翻译，AI再解释它，也不是发现了新的古籍来源。把标签读清楚，再决定如何使用。"],
        ["本站按签号查到的是什么？", "本站观音、关帝、黄大仙各收录100个条目，月老和财神各60个，这是产品里的编号范围，并不代表每座庙都用这套排列。资料库包含部分传统材料与现代象征文字，来源说明标记材料类型，不同语言也可能采用改写而非逐句对应。输入号码查到的是本站资料库中的对应条目，并不能认证它就是你在别处领到的纸签。"],
        ["AI能不能直接解释手里的签？", "本站可选AI解读依据当前显示的资料库条目和你提交的问题，不会认证寺庙签纸，不会读到未提供的原文，也不会查看你手里拿着的纸张照片。如果显示条目与手中签纸不同，解释针对的就是显示条目。不要自行假设所有版本意思都一样。想核实某一庙本，应寻找该版本公开说明，或在条件允许时询问发签处的原文含义。"],
        ["查签前的一张小清单", "保留四项：签系、号码、开头原句、印刷来源。搜索时带上签系和一段准确原句，不只输入数字。找到候选页面后核对文字与来源，再明确自己要的是翻译、文化背景，还是个人反思，这可能需要不同资料。版本无法确认，就保留这个不确定性；可以用现代解读打开话题，同时诚实地承认还没有核实原签的解释。"],
      ], action: { label: "查看签系、签文与来源说明", href: "/sticks?locale=zh" },
    },
    ru: {
      title: "Почему один номер палочки может означать разные тексты?",
      description: "Как сверить храмовый листок с онлайн-оракулом: название коллекции, первые строки, издание и различия между переводом, адаптацией и ответом ИИ.",
      topic: "Текст и его источник", introduction: "Вы принесли из храма пронумерованный листок, нашли номер в интернете, а стих оказался другим. Следующая страница объясняет его иначе. Прежде чем видеть противоречивые предсказания, проверьте, о том ли тексте речь. Номер обозначает место внутри коллекции; сам по себе он не устанавливает коллекцию, издание или слова вашего листка.",
      takeaway: "Сначала сопоставьте коллекцию и сам стих, затем объяснение. Одинакового номера недостаточно, чтобы опознать храмовый текст.",
      sections: [
        ["Посмотрите на название над номером", "Сохраните название храма или издателя, коллекцию и номер в исходном виде. Коллекции Гуаньинь и Гуаньди не взаимозаменяемы, даже если обе содержат номер тридцать три. Если название неясно, запишите первую строку и по возможности спросите там, где получили листок. Загружать фотографию необязательно. Сначала нужно установить текст, а не выбрать самое утешительное объяснение."],
        ["Сравните слова раньше значений", "Сопоставьте первые строки: это тот же стих, перевод или совсем другой текст? Проверьте заголовок, сопровождающую историю и указание источника. Современный пересказ может менять слова, но должен обозначать основу. Если строки не совпадают, а издание не названо, нельзя уверенно считать страницу толкованием именно вашего листка. Читать её отдельно можно, незаметно подменять ею исходный документ — не стоит."],
        ["Различайте четыре слоя", "Оригинал — обсуждаемый текст. Перевод переносит его в другой язык и иногда объясняет образы. Адаптация меняет подачу для современной аудитории. Интерпретация связывает текст с вопросом человека. Это разные задачи. Новый английский текст не обязательно является построчным переводом китайского стиха, а объяснение ИИ не превращается в найденный исторический источник. Сначала прочитайте обозначения этих слоёв."],
        ["Что выдаёт поиск номера на DestinyPixel?", "В продукте по сто записей для Гуаньинь, Гуаньди и Вонг Тай Сина и по шестьдесят для Юэлао и богов богатства. Это диапазоны сайта, не утверждение об устройстве всех храмовых изданий. Библиотека объединяет отдельные традиционные материалы и современные символические тексты, а языковые версии могут быть адаптациями. Поиск возвращает запись этой библиотеки, но не удостоверяет её совпадение с полученной в другом месте бумажной палочкой или листком."],
        ["Что в таком случае объясняет ИИ?", "Дополнительное чтение на сайте использует отображаемую запись и ваш вопрос. Оно не удостоверяет храмовый листок, не читает невидимый оригинал и не рассматривает фотографию бумаги у вас в руках. Если запись отличается от листка, объяснение относится к записи. Не предполагайте автоматически одинаковый смысл всех версий. Для конкретного издания ищите его опубликованное объяснение или спрашивайте выдавший документ храм, когда это возможно."],
        ["Короткая проверка перед поиском", "Запишите коллекцию, номер, первую строку и указанный источник. В запрос добавьте название и точную фразу, а не только цифру. На найденной странице сопоставьте текст и источник, затем решите, что вам нужно: перевод, культурный контекст или личное размышление. Если издание не удалось установить, сохраните эту неопределённость. Современное чтение можно использовать как начало разговора, не объявляя его проверенным объяснением исходного документа."],
      ], action: { label: "Открыть коллекции и пояснения источников", href: "/sticks?locale=ru" },
    },
  },
  {
    slug: "unfavorable-fortune-stick-reading", relatedSlug: "how-to-ask-fortune-sticks", publishedAt: "2026-09-23", updatedAt: "2026-09-23",
    sources: [
      { label: "Hong Kong Tourism Board: Wong Tai Sin Temple", href: "https://www.discoverhongkong.com/eng/place-to-go/travel.guide-wong-tai-sin-temple.html" },
      { label: "Wen Wei Po, 27 January 2026: Sik Sik Yuen abbot on Wong Tai Sin sticks", href: "https://www.tkww.hk/epaper/view/newsDetail/2015847422080716800.html" },
      { label: "Chinese Wikipedia: 求籤", href: "https://zh.wikipedia.org/wiki/%E6%B1%82%E7%B1%A4" },
      { label: "English Wikipedia: Kau chim", href: "https://en.wikipedia.org/wiki/Kau_chim" },
      { label: "DestinyPixel fortune sticks", href: "/sticks" },
      { label: "How to ask a fortune-stick question", href: "/journal/how-to-ask-fortune-sticks" },
      { label: "Same stick number, different edition", href: "/journal/fortune-stick-number-and-edition" },
      { label: "Yuelao: what to say after a love reading", href: "/journal/yuelao-love-fortune-conversation" },
      { label: "Guanyin collection guide", href: "/learn/guanyin-fortune-sticks" },
    ],
    en: {
      title: "What to do after an unfavorable fortune-stick reading",
      description: "An unfavorable or lower lot is a caution to pause and check one fact, not a guarantee of failure. See what redraw does on DestinyPixel, then read the source note.",
      topic: "After an unfavorable lot",
      introduction: "An unfavorable, cautionary, or lower lot is a symbolic reminder of caution, waiting, or difficulty. It is not a destined failure, and it does not guarantee that a plan will fail. This guide answers whether to draw again and whether to change a plan, then separates a temple’s custom, this site’s random draw, the library text, and optional AI.",
      takeaway: "You can draw again on DestinyPixel. A new number is not a more accurate answer. Pause, write the question you brought, and compare the image with your situation. The sticks are for culture and reflection. Do not use a result for a financial, medical, or major relationship decision.",
      sections: [
        ["An unfavorable lot asks for caution, not a cancelled plan", "On /sticks the button reads “Draw my stick,” then “Draw again.” Simplified Chinese uses 「再求一签」. Another draw is allowed. That is a product fact, not a rule every temple shares, and the site does not forbid it. The sticks FAQ says a new number does not make the answer more reliable: keep one reading, note what it brings to mind, and return when the situation changes. The asking guide adds: write the question, the phrase you noticed, and one thing you can check. Some people redraw in folk practice. A second number is still not “more accurate.” Do not keep drawing until you receive an upper or good lot. Blocked, Wait, 小阻, and 待时 are cautionary labels for difficulty or waiting. They do not mean you must decline a job, cancel a trip, or end a relationship."],
        ["Temple pages describe local sequences", "Hong Kong Tourism Board, Wong Tai Sin: shake a bamboo cylinder until one stick falls, then take it to stalls for kau cim. That page states no redraw ban. Wen Wei Po, 27 January 2026, Sik Sik Yuen abbot 李耀輝（義覺）, on that temple: 100 sticks, one matter, shake until one leaves; some record the number only after a confirming moon-block throw; slips are free. Grades include 上上, 上吉, 中吉, 中平, and 下下, read with situation, time, place, and state of mind. A lower grade there is a reading to weigh, not destined failure. Chinese Wikipedia, 求籤: Guangdong and Hong Kong often shake until a stick falls; many Fujian and Taiwan temples return an unconfirmed stick; some Japanese shrines leave an unfavorable slip on a rack. English Wikipedia, Kau chim: many cups hold 100 sticks, other counts exist, and several sticks at once are often not counted. Another try in those accounts confirms the draw or replaces an unconfirmed stick. A disliked poem and an unconfirmed throw are different events."],
        ["What the draw button on DestinyPixel does", "Five collections are on this page: Guanyin, Guandi, Yuelao, the Five Wealth Gods, and Wong Tai Sin. Guanyin, Guandi, and Wong Tai Sin use 1–100. Yuelao and the Five Wealth Gods use 1–60. Those ranges belong to this product, not to every temple. After a short shaking pause, the page chooses an integer in the selected range with crypto.getRandomValues. Your question does not choose the number. You can type it or leave it blank. “Already drew offline?” opens this library’s entry in that range and does not certify a temple slip. “Draw again” repeats the same step. The new number is another draw, not a more accurate one."],
        ["How to read the source note and the level", "Read the source note on the result. This library is not one temple’s verbatim archive, and the same number can differ by collection and edition. The edition guide is linked at the end. Some notes mark traditional themes and say wording can differ. Many Guandi and Wong Tai Sin numbers show classic Chinese in the Chinese edition. English and Russian may show a localized reading instead, and the note says so. That localized text is not a line-by-line ancient poem. Other numbers are modern symbolic text, or are marked as still being checked. Wealth notes say that set is not one canonical temple book. Generated labels include Great Blessing, Good, Steady, Blocked, and Wait in English, and 上吉, 中吉, 中平, 小阻, and 待时 in Chinese. Blocked, Wait, 小阻, and 待时 are cautionary catalog labels. This article copies no numbered poem. How to ask, how editions differ, and what to say after a Yuelao love reading stay in the three guides linked at the end."],
        ["What the optional AI paragraph adds", "“Interpret with my question” (Simplified Chinese 「结合问题解读」) posts the collection, number, on-screen sign, topic, and question to /api/sticks/interpret. The question may be blank. The model must explain that displayed entry against your question. It must not pick a new number. It cannot authenticate a temple lot, and it cannot read another person’s mind. If the request fails, the page shows the plain reading already on the card. Use the result, including any AI paragraph, for culture and reflection only."],
        ["Original scenario: a work opportunity you are unsure about", "Original scenario — work-opportunity worry. Editorial example only. The written offer is in hand, the weekly hours are vague, and the level is a cautionary or lower label such as Blocked or 小阻. That label does not mean you must turn the offer down. Pause, write the question you brought, and compare it with the offer: which three duties, and which weekly hours, are in the written terms? Send that to the hiring contact and name a day to reread the reply. Drawing again for an upper or good label does not make the answer more accurate."],
        ["Original scenario: anxiety before a booked trip", "Original scenario — travel anxiety. Editorial example only. The trip is booked, and the imagery sounds like delay. A cautionary or lower lot does not mean you must cancel. Before another draw, check one fact: passport dates, the first connection on the current timetable, or the local contact if a train slips. If the timetable holds, keep the booking. If the connection is too short, change the booking because of the timetable. A later draw needs a new question about the fact you just checked."],
      ], action: { label: "Open a stick and read its source note", href: "/sticks" },
    },
    zh: {
      title: "抽到不顺签或下签，要不要重抽、要不要改计划？",
      description: "不顺签、谨慎签和下签是谨慎、等待或有难度的提醒，不是注定失败。先看再抽按钮和来源说明，再写出一件可以核实的事。",
      topic: "不顺签与下签",
      introduction: "不顺签、谨慎签或下签，是谨慎、等待或事情有难度的象征提醒。它不是注定的失败，也不保证计划会失败。这篇指南先回答要不要再抽、要不要改计划，再把四层分开：一座庙公布的习俗、本站的随机抽号、资料库文字，以及可选的AI。",
      takeaway: "DestinyPixel 允许再抽。新的号码不会更准。先停一下，写下你带来的问题，再拿意象和眼前的处境对照。抽签只用于文化体验和自我反思。不要用签的结果做财务、医疗或重大感情决定。",
      sections: [
        ["不顺签要的是谨慎，不是取消计划", "在 /sticks，按钮先是“开始求签”，出结果后变成“再求一签”。再抽是允许的。这是产品事实，不是每座庙共用的规矩，本站也不禁止再抽。抽签页已经说明：可以再抽，但换一个号码不会让答案更可靠；不妨留住一支签，写下它让你注意到的事，等处境有变化再回看。提问指南只补一步：写下问题、你注意到的那一句，以及一件可以核实的事。民间也有人会再抽。第二次的号码仍然不是“更准”。不要一直抽到上签或好签为止。Blocked、Wait、小阻、待时是谨慎类标签，指向有难度或需要等待。它们不是必须拒绝工作、取消行程或结束关系。"],
        ["公开页面写的是当地步骤", "香港旅游发展局的黄大仙祠页：摇竹筒直到一支签掉出，再拿到摊档解释 kau cim。这一页没有公布禁止再抽。2026年1月27日《香港文汇报》啬色园监院李耀辉（义觉）写的是该祠：一百支签，一签问一事，摇到一支跳出；有人要卜杯确认后才记下号码；签文纸免费。等级包括上上、上吉、中吉、中平、下下，要随处境、时间、地点和心境来读。那里的下签仍是拿来斟酌的阅读，不是注定失败。中文维基百科“求签”：粤港常见摇到签掉出；不少闽台寺庙在筊未确认时把签放回；部分日本神社把不顺的签留在架上。英文维基百科 Kau chim：许多签筒是一百支，也有别的数量；一次掉出多支时常不算。这些记述里的再来一次，是确认这一抽，或换掉未确认的签。不喜欢的诗句，和筊还没确认的那一支，是两件事。"],
        ["本站抽签按钮实际在做什么", "五个签系：观音、关帝、月老、五路财神、黄大仙。观音、关帝、黄大仙是1到100，月老和五路财神是1到60。这是本产品的范围，不是每座庙的支数。短暂停顿后，页面用 crypto.getRandomValues 在所选范围内取一个整数。问题不参与选号，可以写下或留空。“线下已经抽到签？”打开本库里该范围内的条目，不能认证寺庙纸签。“再求一签”是把同一步再做一次。新号码是另一次抽取，不是更准的答案。"],
        ["先读来源说明和等级", "先读结果上的来源说明。本库不是任何一座庙的逐字档案，同一个号码也会因签系和版本不同。版本对照见文末的签号指南。有的说明标出传统主题，并写明文字可能不同。许多关帝号和黄大仙号在中文版显示传统中文；英文和俄文可能是本地化阅读，说明会写明。那种本地化文字不是逐句的古代签诗。其余号码是现代象征文字，或标明仍在核对。财神签的说明写明它不是一套唯一庙本。生成条目的英文标签包括 Great Blessing、Good、Steady、Blocked、Wait，中文包括上吉、中吉、中平、小阻、待时。Blocked、Wait、小阻、待时是谨慎类目录标签。本文不抄带号码的签诗。怎样提问、版本为何不同、月老感情签看完怎么说，都留在文末三篇指南里，这里不展开。"],
        ["可选AI只解释已经显示的这一支", "“结合问题解读”把签系、号码、屏幕上的签、主题和问题发到 /api/sticks/interpret。问题可以是空的。模型要对照你的问题解释已经显示的条目，不能另选一支，不能认证寺庙签，也不能读出别人的心思。请求失败时，页面显示卡片上已有的白话。包括AI在内的结果，只用于文化体验和自我反思。"],
        ["原创情境：对一个工作机会放心不下", "原创情境：工作机会的不安。只是编辑示例。书面邀请在手上，每周工时仍不清楚，等级是谨慎或下签一类的标签，例如 Blocked 或小阻。这个标签不是必须拒绝邀请。先停一下，写下你带来的问题，再对照邀请：书面条款里的三项职责是什么，每周工时是多少？发给招聘联系人，并定一天重读回复。为了抽到上签或好签而再抽，不会让答案更准。"],
        ["原创情境：已经订好的行程让人焦虑", "原创情境：出行焦虑。只是编辑示例。行程已经订好，意象听起来像延误。谨慎签或下签不是必须取消。再抽之前先核对一件事：护照是否在有效期内，当前时刻表上的第一段换乘是否够长，或者火车变动时当地联系人是谁。时刻表站得住，就保留订单。换乘太短，就因为时刻表改订。若以后再抽，那一次要问你刚刚核对过的那件事实。"],
      ], action: { label: "打开签堂，先读来源说明", href: "/sticks?locale=zh" },
    },
    ru: {
      title: "Неблагоприятный жребий: осторожность, повтор и смена плана",
      description: "Неблагоприятный или нижний жребий — напоминание об осторожности, ожидании или трудности, а не гарантия неудачи. Посмотрите, что делает повтор на DestinyPixel, и прочитайте примечание об источнике.",
      topic: "Неблагоприятный жребий",
      introduction: "Неблагоприятный, предостерегающий или нижний жребий — символическое напоминание об осторожности, ожидании или трудности. Это не предопределённая неудача и не гарантия, что план провалится. Сначала ответы, тянуть ли снова и менять ли план, затем четыре слоя: опубликованный обычай одного храма, случайный выбор на этом сайте, текст библиотеки и необязательный ИИ.",
      takeaway: "На DestinyPixel можно вытянуть жребий снова. Новый номер не делает ответ точнее. Остановитесь, запишите свой вопрос и сравните образ с ситуацией. Палочки — для культуры и размышления. Не используйте результат для финансового, медицинского или важного решения об отношениях.",
      sections: [
        ["Неблагоприятный жребий просит осторожности, а не отмены плана", "На /sticks кнопка сначала называется “Вытянуть жребий”, а после результата — “Вытянуть снова”. По-английски это “Draw again”, по-китайски — 「再求一签」. Повтор разрешён. Это факт продукта, не общее правило всех храмов, и сайт повтор не запрещает. В вопросах на странице палочек уже сказано: повторить можно, но новый номер не делает ответ достовернее; оставьте одно чтение, запишите, что оно напомнило, и вернитесь, когда ситуация изменится. Руководство о вопросе добавляет один шаг: запишите вопрос, замеченную фразу и одно дело для проверки. В народной практике некоторые тянут снова. Второй номер всё равно не “точнее”. Не продолжайте, пока не выпадет верхний или хороший жребий. Blocked, Wait, 小阻 и 待时 — предостерегающие метки трудности или ожидания. Они не означают, что нужно отказаться от работы, отменить поездку или закончить отношения."],
        ["Опубликованные страницы описывают местный порядок", "Совет по туризму Гонконга, храм Вонг Тай Син: трясти бамбуковый цилиндр, пока не выпадет одна палочка, затем нести её к лавкам для кау чим. Запрета на повтор там нет. Wen Wei Po, 27 января 2026, настоятель Сик Сик Юэн 李耀輝（義覺） — об этом храме: 100 палочек, одно дело, трясти, пока одна не выйдет; некоторые записывают номер только после подтверждающего броска блоков; листки бесплатны. Степени включают 上上, 上吉, 中吉, 中平 и 下下 и читаются вместе с ситуацией, временем, местом и состоянием духа. Нижняя степень там — чтение, которое взвешивают, а не предопределённая неудача. Китайская Википедия, 求籤: в Гуандуне и Гонконге часто трясут до выпадения; во многих храмах Фуцзяни и Тайваня неподтверждённую палочку возвращают; в части японских святилищ неблагоприятный листок оставляют на стойке. Английская Википедия, Kau chim: во многих стаканах 100 палочек, бывают другие количества, несколько выпавших сразу часто не считают. Повтор в этих описаниях подтверждает выбор или заменяет неподтверждённую палочку. Непонравившийся стих и неподтверждённый бросок — разные события."],
        ["Что делает кнопка на DestinyPixel", "На странице пять коллекций: Гуаньинь, Гуаньди, Юэлао, Пять богов богатства и Вонг Тай Син. У Гуаньинь, Гуаньди и Вонг Тай Сина номера 1–100. У Юэлао и Пяти богов богатства — 1–60. Это диапазоны продукта, не утверждение, что столько палочек в каждом храме. После короткой паузы страница выбирает целое число в диапазоне функцией crypto.getRandomValues. Вопрос номер не выбирает; его можно записать или оставить пустым. “Уже вытянули офлайн?” открывает запись этой библиотеки в том же диапазоне и не удостоверяет храмовый листок. “Вытянуть снова” повторяет тот же шаг. Новый номер — другой выбор, не более точный ответ."],
        ["Сначала примечание об источнике и степень", "Прочитайте примечание об источнике на результате. Эта библиотека — не дословный архив одного храма, и один номер может различаться по коллекции и изданию. Руководство о номерах и изданиях — в конце статьи. Часть примечаний помечает традиционную тему и говорит, что формулировки различаются. Многие номера Гуаньди и Вонг Тай Сина показывают классический китайский текст в китайской версии. Английская и русская версии могут дать локализованное чтение, о чём говорит примечание. Этот локализованный текст — не построчное древнее стихотворение. Остальные номера — современный символический текст или помечены как ещё сверяемые. Примечания коллекции богатства говорят, что это не единый канонический храмовый набор. Среди сгенерированных меток есть Great Blessing, Good, Steady, Blocked и Wait по-английски и 上吉, 中吉, 中平, 小阻, 待时 по-китайски. Blocked, Wait, 小阻 и 待时 — предостерегающие метки каталога. Эта статья не копирует нумерованные стихи. Как задать вопрос, почему издания расходятся и что сказать после любовного жребия Юэлао — в трёх руководствах в конце. Здесь эти уроки не повторяются."],
        ["Необязательный ИИ объясняет уже показанную запись", "“Толковать мой вопрос” отправляет коллекцию, номер, знак на экране, тему и вопрос на /api/sticks/interpret. Вопрос может быть пустым. Модель должна объяснить показанную запись относительно вашего вопроса. Она не выбирает новый номер. Она не удостоверяет храмовый жребий и не читает чужие мысли. Если запрос не удался, страница показывает простое чтение уже на карточке. Результат, включая абзац ИИ, — только культура и размышление."],
        ["Авторский сценарий: тревога из-за рабочего предложения", "Авторский сценарий — тревога из-за работы. Только редакционный пример. Письменное предложение на руках, недельные часы туманны, а метка предостерегающая или нижняя, например Blocked или 小阻. Эта метка не значит, что предложение нужно отклонить. Остановитесь, запишите свой вопрос и сравните его с предложением: какие три обязанности и какие недельные часы указаны письменно? Отправьте это контакту по найму и назначьте день перечитать ответ. Новый жребий ради верхней или хорошей метки не делает ответ точнее."],
        ["Авторский сценарий: тревога из-за уже купленной поездки", "Авторский сценарий — тревога перед поездкой. Только редакционный пример. Поездка оплачена, образы звучат как задержка. Предостерегающий или нижний жребий не значит, что поездку нужно отменить. До повтора проверьте один факт: срок паспортов, длину первой пересадки по текущему расписанию или местного контакта, если поезд сдвинется. Если расписание держится, оставьте бронь. Если пересадка слишком короткая, меняйте бронь из-за расписания. Позднейший жребий должен задавать новый вопрос о только что проверенном факте."],
      ], action: { label: "Открыть жребий и прочитать источник", href: "/sticks?locale=ru" },
    },
  },
];

function translation(entry: Entry, locale: "en" | "zh" | "ru"): JournalTranslation {
  const copy = entry[locale];
  const sourceLabels: Record<string, Record<"en" | "zh" | "ru", string>> = {
    "https://www.hko.gov.hk/en/gts/time/stemsandbranches.htm": { en: "Hong Kong Observatory: stems and branches", zh: "香港天文台：天干与地支", ru: "Гонконгская обсерватория: стволы и ветви" },
    "https://www.iana.org/time-zones": { en: "IANA: Time Zone Database", zh: "IANA：时区数据库", ru: "IANA: база часовых поясов" },
    "/compatibility": { en: "DestinyPixel: current comparison method", zh: "DestinyPixel：当前配对方法", ru: "DestinyPixel: метод сравнения" },
    "/sticks": { en: "DestinyPixel: collections and source notes", zh: "DestinyPixel：签系与来源说明", ru: "DestinyPixel: коллекции и источники" },
    "/learn/guanyin-fortune-sticks": { en: "Guanyin collection guide", zh: "观音签资料范围（英文）", ru: "Коллекция Гуаньинь (на английском)" },
    "https://www.discoverhongkong.com/eng/place-to-go/travel.guide-wong-tai-sin-temple.html": { en: "Hong Kong Tourism Board: Wong Tai Sin Temple and kau cim", zh: "香港旅游发展局：黄大仙祠与求签", ru: "Совет по туризму Гонконга: храм Вонг Тай Син и кау чим" },
    "https://www.tkww.hk/epaper/view/newsDetail/2015847422080716800.html": { en: "Wen Wei Po, 27 January 2026: Sik Sik Yuen abbot on Wong Tai Sin sticks", zh: "香港文汇报2026年1月27日：啬色园监院谈黄大仙灵签", ru: "Wen Wei Po, 27 января 2026: настоятель Сик Сик Юэн о жребиях Вонг Тай Сина" },
    "https://zh.wikipedia.org/wiki/%E6%B1%82%E7%B1%A4": { en: "Chinese Wikipedia: 求籤, regional customs", zh: "中文维基百科：求签（各地习俗不同）", ru: "Китайская Википедия: цю цянь, разные местные обычаи" },
    "https://en.wikipedia.org/wiki/Kau_chim": { en: "English Wikipedia: Kau chim", zh: "英文维基百科：Kau chim", ru: "Английская Википедия: Kau chim" },
    "/journal/how-to-ask-fortune-sticks": { en: "How to ask a fortune-stick question", zh: "求签怎么问问题", ru: "Как задать вопрос оракулу палочек" },
    "/journal/fortune-stick-number-and-edition": { en: "Same number, different edition", zh: "同一个签号，为什么签文不同", ru: "Один номер, разные тексты" },
    "/journal/yuelao-love-fortune-conversation": { en: "Yuelao: what to say after a love reading", zh: "月老签：看完以后怎么说", ru: "Юэлао: что сказать после любовного жребия" },
    "/journal/prepare-birth-date-time-place": { en: "Prepare your birth details", zh: "准备出生日期、时间与地点", ru: "Подготовка данных рождения" },
  };
  return { ...copy, sections: copy.sections.map(([title, paragraph], index) => ({
    id: `step-${index + 1}`, title, paragraphs: [paragraph],
    ...(index === copy.sections.length - 1 ? { sources: entry.sources.map(source => ({ ...source, label: sourceLabels[source.href]?.[locale] ?? source.label, href: source.href.startsWith("/journal/") || source.href === "/compatibility" || source.href === "/sticks" ? `${source.href}${locale === "en" ? "" : `?locale=${locale}`}` : source.href })) } : {}),
  })) };
}

export const searchGrowthArticles: JournalSourceArticle[] = entries.map(entry => ({
  slug: entry.slug, relatedSlug: entry.relatedSlug, publishedAt: entry.publishedAt ?? "2026-09-20", updatedAt: entry.updatedAt ?? "2026-09-20",
  translations: { en: translation(entry, "en"), zh: translation(entry, "zh") },
}));
export const searchGrowthRussian: Record<string, JournalTranslation> = Object.fromEntries(entries.map(entry => [entry.slug, translation(entry, "ru")]));
