import type { ReportLocale } from "@/lib/report-i18n";
import { compatibilityTimeCopy } from "@/lib/compatibility/time-copy";
import { toTraditional, journalLanguageTags } from "@/lib/journal-locales";
import { absoluteUrl } from "@/lib/seo";
import { stickTypeOrder, stickTypeTotals } from "@/lib/sticks/catalog";

export const productFactsUpdatedAt = "2026-09-30";
export const productFactsLocales = ["en", "zh", "zh-TW", "ru"] as const;
export function productFactsHref(locale: ReportLocale) { return `/product-facts${locale === "en" ? "" : `?locale=${locale}`}`; }
export function productFactsAlternates() { return Object.fromEntries([...productFactsLocales.map(l => [journalLanguageTags[l], absoluteUrl(productFactsHref(l))]), ["x-default", absoluteUrl("/product-facts")]]); }
type Edition = [name: string, purpose: string, input: string, ai: string, saving: string];
type ProductDefinition = { id: string; path: string; locales: readonly ReportLocale[]; pricing: "free" | "free-preview-optional-report"; en: Edition; zh: Edition; ru: Edition };
const all = productFactsLocales;
const products: ProductDefinition[] = [
  { id: "compatibility", path: "/compatibility", locales: all, pricing: "free",
    en: ["BaZi relationship compatibility", "Compare day-pillar animals and five elements; add two recorded times for planetary comparisons.", "Two Gregorian birthdays and supported birth cities. Each birth time can be marked unknown. No default noon or invented hour pillar.", "DeepSeek explains derived chart data after calculation; it does not set the score. Usage limits apply.", "The current couple tool does not save a report."],
    zh: ["八字情感匹配", "比较日柱动物与五行；双方时间已知时，再结合行星比较。", "双方公历生日、支持的出生城市；时辰分别可选未知。不补午时或时柱。", "DeepSeek 根据计算结果解读，不决定分数；设有使用限制。", "当前双人匹配不保存报告。"],
    ru: ["Совместимость Ба-цзы", "Животные дня и пять элементов; с двумя временами добавляются планеты.", "Две григорианские даты и поддерживаемые города; время каждого можно отметить неизвестным. Полдень не подставляется.", "DeepSeek объясняет вычисленные данные, но не задаёт баллы. Действуют лимиты.", "Текущий инструмент пары не сохраняет отчёт."] },
  { id: "astrology", path: "/astrology", locales: all, pricing: "free",
    en: ["Natal birth chart", "Tropical zodiac, Whole Sign houses, ten bodies and major aspects within a 6° orb.", "Gregorian date, recorded local time and supported birthplace. Unknown-time natal charts are not supported here.", "Positions are calculated without AI. The detailed DeepSeek explanation starts on request and has usage limits.", "Sign in or register to save the chart and generated explanation; saved records can be deleted."],
    zh: ["本命星盘", "回归黄道、整宫制、十颗天体及 6° 容许度的主要相位。", "公历日期、已知当地时间与支持的出生地；本工具尚不提供未知时辰星盘。", "天体位置由计算引擎生成；点击后调用 DeepSeek 详解，设有使用限制。", "注册或登录可保存星盘与已生成解读；已存记录可删除。"],
    ru: ["Натальная карта", "Тропический зодиак, цельнознаковые дома, десять тел и основные аспекты с орбисом 6°.", "Дата, известное местное время и поддерживаемый город. Здесь нет режима неизвестного времени.", "Положения вычисляются без ИИ; подробное объяснение DeepSeek запускается по запросу, с лимитами.", "Войдите или зарегистрируйтесь для сохранения карты и объяснения. Записи можно удалить."] },
  { id: "tarot", path: "/tarot", locales: all, pricing: "free",
    en: ["Tarot studio", "78 Rider–Waite–Smith cards; one-card, three-card, relationship, choice, Celtic Cross and a free table.", "No birth information. Shuffle, choose and reveal cards; a question is required for AI, detailed context is optional.", "Local card meanings need no AI. DeepSeek interprets revealed cards with the question and optional context on request; limits apply.", "Sign in or register to save a spread and its generated reading. Saved records can be deleted."],
    zh: ["塔罗牌桌", "78 张韦特体系牌；单张、三张、感情、选择、凯尔特十字及自由牌桌。", "无需生日。可洗牌、选牌、翻牌；AI 详解需要填写问题，详细情况可选。", "简明牌义无需 AI；点击详解后，DeepSeek 结合已翻牌、问题及可选背景解读，设有使用限制。", "注册或登录可保存牌阵与已生成解读，已存记录可删除。"],
    ru: ["Студия Таро", "78 карт Райдера–Уэйта–Смит: одна, три, отношения, выбор, Кельтский крест и свободный стол.", "Дата рождения не нужна. Перемешайте, выберите и откройте карты; для ИИ нужен вопрос, подробности необязательны.", "Краткие значения доступны без ИИ. DeepSeek по запросу читает открытые карты, вопрос и контекст; есть лимиты.", "Войдите для сохранения расклада и готовой интерпретации. Записи можно удалить."] },
  { id: "sticks", path: "/sticks", locales: all, pricing: "free",
    en: ["Chinese fortune sticks", "Five collections with random drawing and numbered lookup. Read the source note on each result.", "Choose a collection and topic; an optional question can guide the explanation. No birth time required.", "The sign comes from the site library; AI explains it separately. Provider failure can return a local explanation.", "The current stick tool does not offer account record saving."],
    zh: ["灵签问事", "五种签系，可随机抽签或按号查签；请阅读每签来源说明。", "选择签系与主题，可补充问题；无需出生时间。", "签来自本站签库，AI 另作解释；服务不可用时可显示本地解释。", "当前抽签工具未提供账号记录保存。"],
    ru: ["Китайские гадательные палочки", "Пять коллекций, случайный выбор или поиск по номеру. Источник указан у результата.", "Выберите коллекцию и тему; вопрос необязателен. Время рождения не нужно.", "Жребий берётся из библиотеки сайта, ИИ объясняет его отдельно. При сбое возможно локальное объяснение.", "В текущем инструменте нет сохранения в аккаунт."] },
  { id: "birth-map", path: "/#report", locales: all, pricing: "free-preview-optional-report",
    en: ["Personal birth map", "A free calculated preview with an optional complete personal report.", "Birth date, known local time, supported city and the form’s requested profile fields. Unknown time is not supported in this full map.", "AI interprets the calculated chart; the complete report follows the current checkout and access rules.", "Sign in to retain reports in the account. The checkout page is authoritative for the current offer."],
    zh: ["个人出生图谱", "免费计算预览，可选完整个人报告。", "出生日期、已知当地时间、支持城市及表单要求的资料；完整图谱不支持未知时辰。", "AI 解读已计算的图谱，完整报告遵循当前结算及访问规则。", "登录后可保留报告；实际可购买状态与价格以结算页为准。"],
    ru: ["Личная карта рождения", "Бесплатный расчёт-предпросмотр и необязательный полный личный отчёт.", "Дата, известное местное время, город и данные формы. Полная карта не поддерживает неизвестный час.", "ИИ объясняет рассчитанную карту; полный отчёт подчиняется текущим правилам оплаты и доступа.", "Войдите для хранения отчётов. Актуальное предложение указано при оформлении."] },
  { id: "day-character", path: "/discover", locales: all, pricing: "free",
    en: ["Birthday character", "Find a civil-date Day Pillar and one of 60 original animal portraits.", "Gregorian birth date only. This is not a recovered full birth chart.", "Calendar calculation and portrait content do not need AI.", "A public date-based starting point, not a private saved full report."],
    zh: ["生日动物意象", "按民用日期查日柱，对应六十种本站原创动物意象。", "仅需公历生日；不等于补齐完整八字。", "历法计算与意象内容不依赖 AI。", "公开的日期入门体验，不是已保存的私人完整报告。"],
    ru: ["Образ дня рождения", "Столп календарного дня и один из 60 авторских животных.", "Только григорианская дата, без восстановления полной карты.", "Календарь и описания не требуют ИИ.", "Общедоступное знакомство по дате, не сохранённый полный личный отчёт."] },
  { id: "totem", path: "/tuteng", locales: all, pricing: "free",
    en: ["Birth Totem", "DestinyPixel’s original interactive geometry built from BaZi, not an ancient totem system.", "Use the birth fields required by the tool; do not invent a missing time.", "Geometry is calculated deterministically.", "Follow the tool’s own export controls; not a celestial saved record."],
    zh: ["本命灵构", "由八字生成的本站原创交互几何，不是古代图腾体系。", "按工具要求填写出生资料，不虚构缺失时间。", "几何结构由确定性计算生成。", "使用工具自身导出功能，不属于星盘塔罗保存记录。"],
    ru: ["Тотем рождения", "Авторская интерактивная геометрия Ба-цзы, не древняя система тотемов.", "Заполните данные формы, не придумывая неизвестное время.", "Геометрия рассчитывается детерминированно.", "Используйте экспорт инструмента; это не запись сохранённых Таро и натальной карты."] },
  { id: "atelier", path: "/atelier", locales: all, pricing: "free",
    en: ["Crystal bracelet atelier", "Explore five-element colour and material combinations for bracelet design.", "Choose design inputs in the atelier; a design does not require a prediction.", "Design associations are symbolic, not evidence of health or luck effects.", "Use the atelier’s design controls. This catalog offers no purchase of physical jewelry."],
    zh: ["灵石手串工坊", "探索五行配色与材质组合，设计手串。", "在工坊选择设计输入；设计不需要预测结果。", "材质与配色是象征关联，不是健康或改运效果证据。", "使用工坊设计功能；本目录不提供实物珠宝购买。"],
    ru: ["Мастерская браслетов", "Цвета пяти элементов и материалы для дизайна браслета.", "Выберите параметры дизайна в мастерской.", "Связи символические, без доказанных эффектов для здоровья или удачи.", "Каталог не предлагает покупку физических украшений."] },
  { id: "oracle", path: "/oracle", locales: all, pricing: "free",
    en: ["Question oracle", "Question-based symbolic reflection, separate from the manually selected Tarot studio.", "A question and the mode’s requested inputs; no birth data needed for question-based modes.", "AI explanation is separate from the cast or selected structure.", "Do not treat this entry as a saved Tarot record or an automated purchase API."],
    zh: ["问事灵感", "围绕问题进行象征性解读，与手选塔罗牌桌分别提供。", "填写问题及模式所需输入；问事模式不需要生日。", "AI 对起卦或选定结构作解释。", "不是已保存的塔罗记录，也不提供自动购买接口。"],
    ru: ["Оракул вопроса", "Символическое размышление над вопросом, отдельно от ручной студии Таро.", "Вопрос и данные выбранного режима; для вопросных режимов дата рождения не нужна.", "ИИ объясняет полученную структуру отдельно.", "Это не сохранённый расклад Таро и не API автоматической покупки."] },
  ...(["palm", "face"] as const).map(id => ({ id, path: `/${id}`, locales: all, pricing: "free" as const,
    en: [id === "palm" ? "Palm reflection" : "Face reflection", "Describe visible features for a symbolic reflection.", "Written observations; an optional photo is a local visual reference.", "AI reads the described features, not the uploaded image.", "No celestial account record saving is offered here."] as Edition,
    zh: [id === "palm" ? "手相观察" : "面相观察", "描述可见特征，获得象征性观察。", "填写观察特征；可选照片仅作本地视觉参考。", "AI 读取文字描述，不分析上传图像。", "此处未提供星盘塔罗式账号记录保存。"] as Edition,
    ru: [id === "palm" ? "Наблюдение ладони" : "Наблюдение лица", "Опишите видимые особенности для символического размышления.", "Текстовые наблюдения; фото необязательно и служит локальной опорой.", "ИИ читает описание, не изображение.", "Здесь нет сохранения как для Таро и натальных карт."] as Edition })),
];
const copy = {
  en: { title: "DestinyPixel tools, prices and calculation methods", intro: "Check what each tool actually needs and provides before starting. This public catalog contains product facts, never private readings.", free: "Free to explore", paid: "Free preview · optional complete report", input: "What to prepare", ai: "Calculation and AI", saving: "Saving", open: "Open tool", sources: "Fortune-stick editions", sourceNote: "This is a mixed site library, not a complete authoritative temple edition. Selected traditional Chinese texts, localized adaptations and DestinyPixel’s modern symbolic verses coexist. Each result’s source note identifies its treatment; numbering is collection-specific. Guandi material includes the MIT-licensed dreamer2q/fortune_telling dataset; other traditional samples are identified at the result level. English and Russian are not guaranteed line-by-line translations of Chinese verses.", limits: "What these tools can tell you", boundary: "Chart positions and calendar structures are calculated; cultural meanings, original animal metaphors and AI explanations are interpretations. They do not establish scientific personality measurements or predict relationship success, health, finances or future events. Do not use them in place of professional or emergency help.", privacy: "Private birth details, questions, account data and saved readings are excluded from this catalog. Saving requires an account where offered. Tool pages explain what is sent to AI before the relevant action.", reviewed: "Product facts reviewed", unavailable: "Complete-report checkout is currently unavailable to public visitors.", offer: "Current complete-report offer", priceNote: "One-time USD payment for the complete personal birth report, not a subscription or a charge for the other free tools. Confirm the offer at checkout.", languages: "Tool languages", scope: "This is DestinyPixel’s own read-only catalog format. It is not a claim of a universal agent standard, guaranteed AI citation or an agent checkout API." },
  zh: { title: "DestinyPixel 工具、价格与计算方法", intro: "开始前，先了解各工具需要什么、能够提供什么。这里是公开产品事实说明，不包含私人解读。", free: "免费体验", paid: "免费预览 · 可选完整报告", input: "需要准备", ai: "计算与 AI", saving: "记录保存", open: "打开工具", sources: "签库与版本", sourceNote: "本站采用混合签库，不是某一庙本的完整权威逐字版。部分传统中文签文、本地化改编与本站现代象征签意并存，具体以每签的来源说明为准，签号只在相应签系内有意义。关帝签部分材料来自 MIT 授权的 dreamer2q/fortune_telling 数据集，其他传统样本在结果中标注。英文、俄文不保证逐句翻译中文签诗。", limits: "理解结果的范围", boundary: "天体位置与历法结构由引擎计算；传统意义、原创动物比喻和 AI 解释属于解读。它们不是科学人格测量，也不证明感情成功率、健康、财务或未来事件。不代替专业意见或紧急救助。", privacy: "本目录不包含私人出生资料、问题、账户信息或已保存解读。提供保存的工具需登录；各工具会说明相应操作向 AI 发送哪些信息。", reviewed: "产品事实核对日期", unavailable: "完整报告结算目前未向普通访客开放。", offer: "当前完整报告选项", priceNote: "完整个人出生报告为美元单次付款，不是订阅，也不是其他免费工具的使用费。请在结算时核对实际选项。", languages: "工具语言", scope: "这是本站自定义的只读产品目录，不表示通用 Agent 标准，不保证 AI 引用，也不是代理自动支付接口。" },
  ru: { title: "Инструменты DestinyPixel: цены и методы", intro: "Что нужно каждому инструменту и что вы получите. Каталог содержит общедоступные факты о продукте, без личных интерпретаций.", free: "Бесплатное знакомство", paid: "Бесплатный предпросмотр · полный отчёт по желанию", input: "Что подготовить", ai: "Расчёт и ИИ", saving: "Сохранение", open: "Открыть", sources: "Источники жребиев", sourceNote: "Библиотека смешанная, не полная авторитетная храмовая редакция. В ней есть традиционные китайские тексты, локальные адаптации и современные символические стихи DestinyPixel. Читайте источник каждого результата; номера относятся к своей коллекции. Часть текстов Гуаньди — из dreamer2q/fortune_telling с лицензией MIT. Английский и русский текст не обязательно переводят китайский построчно.", limits: "Границы интерпретации", boundary: "Положения планет и календарь вычисляются; культурные смыслы, животные-метафоры и объяснения ИИ являются интерпретациями. Это не научная оценка личности и не доказательство будущих событий, здоровья, финансов или успеха отношений. Они не заменяют профессиональную или экстренную помощь.", privacy: "Личные даты, вопросы, данные аккаунта и сохранённые чтения в каталог не включаются. Для доступного сохранения нужен вход; перед обращением к ИИ инструмент объясняет передачу данных.", reviewed: "Факты проверены", unavailable: "Оплата полного отчёта сейчас недоступна обычным посетителям.", offer: "Текущее предложение полного отчёта", priceNote: "Разовая оплата в USD за полный личный отчёт, не подписка и не плата за остальные бесплатные инструменты. Уточните предложение при оформлении.", languages: "Языки инструмента", scope: "Это собственный формат каталога только для чтения, не универсальный стандарт агентов, не гарантия цитирования ИИ и не API оплаты." },
};
export function productFactsCopy(locale: ReportLocale) { return locale === "zh-TW" ? JSON.parse(toTraditional(JSON.stringify(copy.zh))) as typeof copy.en : copy[locale]; }
export type PublicReportOffer = { available: boolean; price: string | null; currency: "USD"; mode: "live" | "sandbox" | "disabled" };
export function productCatalog(offer: PublicReportOffer) {
  const reportOffer = { available: offer.available && offer.mode === "live", amount: offer.available && offer.mode === "live" ? offer.price : null, currency: "USD", payment: "one-time", sourceUrl: absoluteUrl("/#report") };
  return { schemaVersion: "destinypixel-product-facts-v1", updatedAt: productFactsUpdatedAt, officialUrl: absoluteUrl("/"), documentationUrl: absoluteUrl("/product-facts"), catalogUrl: absoluteUrl("/api/products.json"), readOnly: true,
    products: products.map(p => ({ id: p.id, url: absoluteUrl(p.path), supportedLocales: p.locales, pricing: { model: p.pricing, ...(p.pricing === "free-preview-optional-report" ? { completeReport: reportOffer } : { amount: "0", currency: "USD" }) },
      translations: Object.fromEntries(productFactsLocales.map(locale => { const a = locale === "zh-TW" ? JSON.parse(toTraditional(JSON.stringify(p.zh))) as Edition : p[locale]; return [locale, { name: a[0], purpose: a[1], inputs: a[2], ai: a[3], saving: a[4], url: absoluteUrl(p.path.includes("#") ? `/${locale === "en" ? "" : `?locale=${locale}`}#report` : `${p.path}${locale === "en" ? "" : `?locale=${locale}`}`) }]; })) })),
    compatibility: { birthTimeOptionalPerPerson: true, missingTimeDefault: null, unknownHourPillar: null, uncertainSolarTermPillars: "omitted", dateScoreUsesPlanetaryAspects: false, fullScoreWeights: { bazi: 0.3, astrology: 0.7 }, dateScoreWeights: { dayElements: 0.5, availableElementDistribution: 0.5 }, scale: { min: 60, max: 100, interpretation: "symbolic editorial index, not probability" }, translations: Object.fromEntries(productFactsLocales.map(l => { const t = compatibilityTimeCopy(l); return [l, { method: t.method, basis: t.basis, sky: t.skyNote, limits: t.note }]; })) },
    fortuneSticks: { collections: stickTypeOrder.map(id => ({ id, entries: stickTypeTotals[id] })), sourceNotes: Object.fromEntries(productFactsLocales.map(l => [l, productFactsCopy(l).sourceNote])), detailsUrl: absoluteUrl("/journal/fortune-stick-number-and-edition") },
    policies: Object.fromEntries(productFactsLocales.map(l => { const c = productFactsCopy(l); return [l, { interpretation: c.boundary, privacy: c.privacy, catalogScope: c.scope }]; })) };
}
