import type { ReportLocale } from "./report-i18n";
import { toTraditional } from "./journal-locales";
export const sectionKeys = ["discover", "sticks", "compatibility", "atelier"] as const;
export type SectionKey = typeof sectionKeys[number];
export function sectionHref(path: string, locale: ReportLocale) { return locale === "en" ? path : `${path}?locale=${locale}`; }
type Section = { name: string; title: string; body: string; action: string; result: string; next: string };
type Copy = { eyebrow:string; title:string; intro:string; paths:string; nav:string; guides:string; more:string; journal:string; learn:string; report:string; reportNote:string; sections:Record<SectionKey,Section> };
const en:Copy={eyebrow:"FOUR PATHS · ONE CURIOUS WORLD",title:"Find your story.\nChoose what comes next.",intro:"Meet your Day Pillar, reflect on a question, explore a relationship or make something personal.",paths:"Where would you like to begin?",nav:"Explore DestinyPixel",guides:"Read a little further",more:"All tools",journal:"Journal",learn:"How it works",report:"Explore your full birth map",reportNote:"Already have a birthday card? Continue with your birth time and city. Free tools and the optional full report are explained before you begin.",sections:{
 discover:{name:"Day Pillars",title:"A birthday. A character. Your story.",body:"Find your calendar pair and its original animal card. Explore all 60 portraits, with stories about character, relationships and creative work.",action:"Find my free card",result:"Date only · free · no account",next:"Find your pair, read its full portrait, then compare another Day Pillar."},
 sticks:{name:"Fortune sticks",title:"One question. A moment to reflect.",body:"Choose a tradition, draw a numbered sign or look up a number you already have. Read the text and its interpretation in context.",action:"Draw a sign",result:"Number, sign text and reflection",next:"Read the sign in its own tradition, then use the guides to shape a useful next question."},
 compatibility:{name:"Relationships",title:"Two people. More than one perspective.",body:"Compare BaZi and birth-chart patterns with clear explanations of what is known and what depends on birth time.",action:"Compare two birthdays",result:"Birth times optional",next:"Start with the calculated comparison. Use the guides to discuss differences without turning a score into a verdict."},
 atelier:{name:"Bracelet atelier",title:"Make a little meaning, bead by bead.",body:"Choose colors, stones and a comfortable size. See your bracelet take shape and save an image of your design.",action:"Design my bracelet",result:"A visual design · no purchase required",next:"Choose your palette, add or remove beads, then download your design. Five-element colors are symbolic inspiration, not a health treatment."}}};
const zh:Copy={eyebrow:"四个专题 · 从你的好奇开始",title:"找到你的故事，\n选择下一步。",intro:"认识日柱意象，带着问题求签，理解两人的相处，或亲手设计一串属于自己的颜色。",paths:"今天，你想从哪里开始？",nav:"探索 DestinyPixel",guides:"接着读，把意思弄明白",more:"全部工具",journal:"原创文章",learn:"使用指南",report:"继续探索完整出生图谱",reportNote:"已经认识生日意象？可以带着出生时间和城市继续。开始前先了解免费工具与可选完整报告的区别。",sections:{
 discover:{name:"六十日柱",title:"一个生日，一张意象，一段故事。",body:"查出你的干支组合与原创动物卡，再读完整性格、感情与创作故事。六十篇图文都在这里。",action:"免费测我的意象卡",result:"只需日期 · 免费 · 无需账号",next:"先查出日柱，读自己的完整画像，再对照另一篇，认识意象之间的区别。"},
 sticks:{name:"求签问事",title:"一个问题，留一刻认真想想。",body:"选择签系，抽取签号；也可以查询已有号码。先读签文，再了解它所在的传统与解释范围。",action:"开始求签",result:"签号、签文与反思提示",next:"先在对应签系中读签，再看怎样提问与辨认版本，把意思带回具体处境。"},
 compatibility:{name:"关系合盘",title:"两个人，不止一种相处视角。",body:"从八字与出生星盘比较相处模式。哪些来自已知资料，哪些会受出生时间影响，都说清楚。",action:"比较两人的生日",result:"时辰可选未知",next:"先看计算结果，再借助指南讨论差异；分数不是一段关系的判决。"},
 atelier:{name:"手串工坊",title:"一颗一颗，配出自己的颜色。",body:"挑选颜色、石材与合适的尺寸，看手串逐渐成形，再保存设计图。",action:"设计我的手串",result:"可视化设计 · 无需购买",next:"选色、加珠或移除，再下载设计图。五行颜色是象征灵感，不是健康疗法。"}}};
const ru:Copy={eyebrow:"ЧЕТЫРЕ ПУТИ · ОДИН МИР ОБРАЗОВ",title:"Найдите свою историю.\nВыберите продолжение.",intro:"Узнайте столп дня, обдумайте вопрос, исследуйте отношения или создайте свой браслет.",paths:"С чего вам хочется начать?",nav:"Разделы DestinyPixel",guides:"Продолжите чтение",more:"Все инструменты",journal:"Статьи",learn:"Как пользоваться",report:"Исследовать полную карту рождения",reportNote:"Уже нашли свой образ? Продолжите со временем и городом рождения. Условия бесплатных инструментов и дополнительного полного отчёта указаны до начала.",sections:{
 discover:{name:"Столпы дня",title:"День рождения. Образ. Ваша история.",body:"Найдите календарную пару и её авторскую карточку. Все 60 историй о характере, отношениях и творчестве собраны в одном месте.",action:"Найти свою карточку",result:"Только дата · бесплатно · без аккаунта",next:"Найдите свою пару, прочтите полный портрет и сравните его с другим столпом дня."},
 sticks:{name:"Гадательные палочки",title:"Один вопрос. Время подумать.",body:"Выберите традицию, вытяните знак или найдите уже известный номер. Прочтите текст и его толкование в контексте.",action:"Вытянуть знак",result:"Номер, текст и тема для размышления",next:"Прочтите знак в выбранной традиции. Статьи помогут уточнить вопрос и разобраться в версиях текстов."},
 compatibility:{name:"Отношения",title:"Два человека. Несколько точек зрения.",body:"Сравните Бацзы и карты рождения. Узнайте, какие выводы опираются на известные данные, а какие зависят от времени рождения.",action:"Сравнить две даты",result:"Время можно не знать",next:"Начните с расчёта, затем обсудите различия с помощью статей. Балл не определяет судьбу отношений."},
 atelier:{name:"Мастерская браслетов",title:"Создавайте свой образ, бусина за бусиной.",body:"Выберите цвета, камни и удобный размер. Соберите браслет на экране и сохраните изображение своего дизайна.",action:"Создать браслет",result:"Визуальный проект · без покупки",next:"Выберите палитру, добавьте или уберите бусины и скачайте рисунок. Цвета пяти элементов — символическое вдохновение, не лечение."}}};
export function journeyCopy(locale:ReportLocale):Copy { return locale==="zh-TW"?JSON.parse(toTraditional(JSON.stringify(zh))):locale==="zh"?zh:locale==="ru"?ru:en; }
export const sectionGuides:Record<SectionKey,string[]>={discover:["what-is-a-day-pillar","jia-zi-day-pillar","gui-hai-day-pillar"],sticks:["how-to-ask-fortune-sticks","fortune-stick-number-and-edition","yuelao-love-fortune-conversation"],compatibility:["compatibility-without-birth-time","bazi-vs-chinese-zodiac-compatibility","five-elements-relationship-compatibility"],atelier:["five-element-bracelet-design","crystal-bracelet-care","five-elements-relationship-compatibility"]};
