import type { ReportLocale } from "@/lib/report-i18n";

const copy = {
  en: { help: "Choose an empty position, then place a card from the deck. Tap a placed card to reveal it; tap again for its meaning. Select a filled position to replace its card.", empty: "Choose a card", beforeShuffle: "Shuffle first, then place a card.", deckHelp: "Tap Place on table, tap the deck, or drag a card to a position.", nav: "Explore tarot", draw: "Draw cards", atlas: "Card atlas", guide: "Spreads & basics", eyebrow: "A LITTLE SPACE TO EXPLORE", title: "Put your question on the table.", intro: "Shuffle, turn a card, and look closely. Start with what you see.", steps: ["Shuffle", "Place", "Reveal", "Explore"], others: "Explore other themes", spreads: "Choose your spread", note: "78 cards · room for your own reading" },
  zh: { help: "选择空牌位，再从牌堆放入一张。点已放好的牌翻开，再点查看牌义；选中已有牌的牌位，也能换一张。", empty: "选择一张牌", beforeShuffle: "先洗牌，再放一张到桌上。", deckHelp: "点“放到牌桌”、点牌堆，或拖一张到牌位。", nav: "探索塔罗", draw: "抽牌桌", atlas: "牌义图鉴", guide: "牌阵与入门", eyebrow: "留一点空间，慢慢探索", title: "把问题放在桌上。", intro: "洗牌，翻开一张，看看画面。先从你注意到的细节开始。", steps: ["洗牌", "放牌", "翻牌", "读牌"], others: "探索其他主题", spreads: "选择你的牌阵", note: "78 张牌 · 留下自己的理解" },
  "zh-TW": { help: "選擇空牌位，再從牌堆放入一張。點已放好的牌翻開，再點查看牌義；選中已有牌的牌位，也能換一張。", empty: "選擇一張牌", beforeShuffle: "先洗牌，再放一張到桌上。", deckHelp: "點「放到牌桌」、點牌堆，或拖一張到牌位。", nav: "探索塔羅", draw: "抽牌桌", atlas: "牌義圖鑑", guide: "牌陣與入門", eyebrow: "留一點空間，慢慢探索", title: "把問題放在桌上。", intro: "洗牌，翻開一張，看看畫面。先從你注意到的細節開始。", steps: ["洗牌", "放牌", "翻牌", "讀牌"], others: "探索其他主題", spreads: "選擇你的牌陣", note: "78 張牌 · 留下自己的理解" },
  ru: { help: "Выберите пустую позицию и выложите карту из колоды. Нажмите на неё, чтобы открыть, и ещё раз — чтобы прочитать значение. Выберите занятую позицию, если хотите заменить карту.", empty: "Выберите карту", beforeShuffle: "Сначала перемешайте колоду, затем выложите карту.", deckHelp: "Нажмите «На стол», нажмите на колоду или перетащите карту на позицию.", nav: "Знакомство с таро", draw: "Вытянуть карты", atlas: "Атлас карт", guide: "Расклады и основы", eyebrow: "ПРОСТРАНСТВО ДЛЯ ИССЛЕДОВАНИЯ", title: "Положите свой вопрос на стол.", intro: "Перемешайте колоду, откройте карту и присмотритесь. Начните с того, что видите.", steps: ["Перемешать", "Выложить", "Открыть", "Изучить"], others: "Другие темы", spreads: "Выберите расклад", note: "78 карт · место для вашего прочтения" },
};
export const tarotWorkspaceCopy = (locale: ReportLocale) => copy[locale];
